### ISSUE TITLE
Beyond Basic Validation

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#116] opened 2017-04-11 14:31 UTC
> There are only very basic validation of input arguments that are not Models - we check for type (string/number/object) and whether the argument is required or not. I would like to see improved validations, using either JSON Schema or npm modules like joi
> --@bajtos

**Comment by bajtos** [comment] 2017-11-03 14:32
Closing as a duplicate of #118

**Closed by bajtos** 2017-11-03 14:32 UTC
Labels: epic.repository, Juggler-GA
