### ISSUE TITLE
[Docs]: Wiki cleanup [Spike]

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1016] opened 2018-02-19 14:04 UTC
Our Wiki pages at https://github.com/strongloop/loopback-next/wiki contain a lot of outdated information, with occasional little gems of wisdom that's still useful.

As part of this spike, I am proposing to review all Wiki pages and for each page, decide what to do about it:

 - When the content is already duplicated elsewhere (monorepo, loopback.io docs), replace the duplicated content with a link to the new place (source of truth).
 - When the content is outdated and/or no longer relevant, decide whether we want to bring it up to date or simply get rid of it.
 - Content that's still valid should be moved either to [docs](https://github.com/strongloop/loopback-next/tree/master/docs) directory for things specific to this monorepo) or to [loopback.io](http://loopback.io/doc/en/lb4) for things applicable to more than just GitHub repository.

## Acceptance criteria

For each wiki page listed below, decide what should be done. Trivial changes that are easy to make can be done as part of this spike, everything else should be changed via follow-up issues. When creating follow-up issues, consider grouping changes to several similar pages into a single one. Having 42 one-story-pointer issues is not very helpful (at least in @bajtos's opinion).

 - [ ] [Benchmarks](https://github.com/strongloop/loopback-next/wiki/Benchmarks)
 - [x] [Calling-other-APIs-and-Web-Services](https://github.com/strongloop/loopback-next/wiki/Calling-other-APIs-and-Web-Services)
 - [x] [Coding-style-guide](https://github.com/strongloop/loopback-next/wiki/Coding-style-guide)
 - [x] [Conceptual-differences-between-LoopBack-v3-and-v4](https://github.com/strongloop/loopback-next/wiki/Conceptual-differences-between-LoopBack-v3-and-v4)
 - [x] [Context](https://github.com/strongloop/loopback-next/wiki/Context)
 - [x] [Contributing](https://github.com/strongloop/loopback-next/wiki/Contributing)
 - [x] [Controllers](https://github.com/strongloop/loopback-next/wiki/Controllers)
 - [x] [Crafting-LoopBack-Next](https://github.com/strongloop/loopback-next/wiki/Crafting-LoopBack-Next)
 - [x] [Dependency-Injection](https://github.com/strongloop/loopback-next/wiki/Dependency-Injection)
 - [ ] [Documentation-Plan](https://github.com/strongloop/loopback-next/wiki/Documentation-Plan)
 - [x] [Documentation-outline-(old)](https://github.com/strongloop/loopback-next/wiki/Documentation-outline-(old))
 - [x] [Examples](https://github.com/strongloop/loopback-next/wiki/Examples)
 - [x] [FAQ](https://github.com/strongloop/loopback-next/wiki/FAQ)
 - [ ] [Feature-proposals](https://github.com/strongloop/loopback-next/wiki/Feature-proposals)
 - [x] [Getting-started](https://github.com/strongloop/loopback-next/wiki/Getting-started)
 - [x] [Glossary](https://github.com/strongloop/loopback-next/wiki/Glossary)
 - [ ] [Home](https://github.com/strongloop/loopback-next/wiki/Home)
 - [x] [Installation](https://github.com/strongloop/loopback-next/wiki/Installation)
 - [ ] [Introduction-to-LoopBack-Next-development](https://github.com/strongloop/loopback-next/wiki/Introduction-to-LoopBack-Next-development)
 - [ ] [Meeting-notes](https://github.com/strongloop/loopback-next/wiki/Meeting-notes)
 - [x] [Migrating-from-v3-to-v4](https://github.com/strongloop/loopback-next/wiki/Migrating-from-v3-to-v4)
 - [x] [Model](https://github.com/strongloop/loopback-next/wiki/Model)
 - [x] [Persisting-Data-with-Repositories](https://github.com/strongloop/loopback-next/wiki/Persisting-Data-with-Repositories)
 - [ ] [Principles](https://github.com/strongloop/loopback-next/wiki/Principles)
 - [ ] [Project-Docs](https://github.com/strongloop/loopback-next/wiki/Project-Docs)
 - [ ] [Publishing](https://github.com/strongloop/loopback-next/wiki/Publishing)
 - [x] [Repositories](https://github.com/strongloop/loopback-next/wiki/Repositories)
 - [x] [Reserved-binding-keys](https://github.com/strongloop/loopback-next/wiki/Reserved-binding-keys)
 - [x] [Routes](https://github.com/strongloop/loopback-next/wiki/Routes)
 - [x] [Schemas](https://github.com/strongloop/loopback-next/wiki/Schemas)
 - [x] [Sequence-(Advanced)](https://github.com/strongloop/loopback-next/wiki/Sequence-(Advanced))
 - [x] [Sequence](https://github.com/strongloop/loopback-next/wiki/Sequence)
 - [x] [Service](https://github.com/strongloop/loopback-next/wiki/Service)
 - [x] [Take-the-tutorial](https://github.com/strongloop/loopback-next/wiki/Take-the-tutorial)
 - [ ] [Terms-for-multiple-protocol-APIs](https://github.com/strongloop/loopback-next/wiki/Terms-for-multiple-protocol-APIs)
 - [x] [Testing-Your-Application-(Advanced)](https://github.com/strongloop/loopback-next/wiki/Testing-Your-Application-(Advanced))
 - [x] [Testing-Your-Application](https://github.com/strongloop/loopback-next/wiki/Testing-Your-Application)
 - [x] [Thinking-in-LoopBack](https://github.com/strongloop/loopback-next/wiki/Thinking-in-LoopBack)
 - [ ] [Upcoming-Releases](https://github.com/strongloop/loopback-next/wiki/Upcoming-Releases)
 - [x] [Using-Components](https://github.com/strongloop/loopback-next/wiki/Using-Components)
 - [x] [Using-decorators](https://github.com/strongloop/loopback-next/wiki/Using-decorators)
 - [x] [Writing-Components](https://github.com/strongloop/loopback-next/wiki/Writing-Components)

**Timeboxed to 1 day**

**Comment by dhmlau** [comment] 2018-05-04 22:11
@bajtos , are you thinking of deleting the irrelevant or redundant wiki pages? for example for https://github.com/strongloop/loopback-next/wiki/Installation, i think we can delete it..  thanks.

**Comment by bajtos** [comment] 2018-05-10 14:03
>  are you thinking of deleting the irrelevant or redundant wiki pages? 

Sure, sounds like a reasonable approach.

> for example for https://github.com/strongloop/loopback-next/wiki/Installation, i think we can delete it.. thanks.

The page says "DO NOT EDIT: Moved to loopback.io as of 12 Sept 2017", I think all of these moved pages can be deleted.

**Comment by dhmlau** [comment] 2018-05-15 01:53
FYI - I'm now trying to delete the wiki pages with "DO NOT EDIT: Moved to loopback.io as of 12 Sept 2017" and checking them off from the list.

**Comment by dhmlau** [comment] 2018-06-05 18:09
I went through all the pages listed in the original description and deleted the ones that are duplicate of the documentation because our docs contain the most updated content.  

For the remaining pages, I'd like to get some input on what to do about it (my proposal included), especially @raymondfeng @bajtos  who are with LB4 since the beginning.  

 - [ ] [Benchmarks](https://github.com/strongloop/loopback-next/wiki/Benchmarks)
   - keep it.  there seems to be some useful information
 - [ ] [Documentation-Plan](https://github.com/strongloop/loopback-next/wiki/Documentation-Plan)
   - seems outdated and can be deleted.  Thoughts? 
 - [ ] [Feature-proposals](https://github.com/strongloop/loopback-next/wiki/Feature-proposals)
   - not sure what we should do about it.  Supposedly we should be opening issues on Github for feature proposals by now.  
 - [ ] [Home](https://github.com/strongloop/loopback-next/wiki/Home)
   - keep it.  that's the main page. :)  Perhaps we can update it to be more useful. 
 - [ ] [Introduction-to-LoopBack-Next-development](https://github.com/strongloop/loopback-next/wiki/Introduction-to-LoopBack-Next-development)
   - contain the blog post proposal from Tetsuo some time ago and we abandon that PR, and it contain outdated information.  Not sure if we can just remove it. 
 - [ ] [Meeting-notes](https://github.com/strongloop/loopback-next/wiki/Meeting-notes) 
   - I guess we should keep it.  Maybe put it in an `Archive` folder? 
 - [ ] [Principles](https://github.com/strongloop/loopback-next/wiki/Principles)
   - not sure what to do with it.  maybe make it in the Home page?  
 - [ ] [Project-Docs](https://github.com/strongloop/loopback-next/wiki/Project-Docs)
   - not sure the need of it.  delete it? 
 - [ ] [Publishing](https://github.com/strongloop/loopback-next/wiki/Publishing)
   - keep it
 - [ ] [Terms-for-multiple-protocol-APIs](https://github.com/strongloop/loopback-next/wiki/Terms-for-multiple-protocol-APIs)
   - seem to have useful information. keep it? 
 - [ ] [Upcoming-Releases](https://github.com/strongloop/loopback-next/wiki/Upcoming-Releases)
   - keep it

**Comment by bajtos** [comment] 2018-06-07 10:10
> Benchmarks
> keep it. there seems to be some useful information

The content is very outdated, the landscape has changed so much since Node.js 7.x days that the numbers are no longer relevant. We aren't going to switch from async/await back to callbacks anyways.

Let's remove this page.

> Documentation-Plan
> seems outdated and can be deleted. Thoughts?

+1

>  Feature-proposals
> not sure what we should do about it. Supposedly we should be opening issues on Github for feature proposals by now.

Remove it.

> Home
> keep it. that's the main page. :) Perhaps we can update it to be more useful.

+1 to keep it. I think larger updates are out of scope of this task, but I think a quick change of adding a ToC-like links to other wiki pages would help a lot and can be done as part of this user story.

>  Introduction-to-LoopBack-Next-development
> contain the blog post proposal from Tetsuo some time ago and we abandon that PR, and it contain outdated information. Not sure if we can just remove it.

I would just remove it. 

> Meeting-notes
> I guess we should keep it. Maybe put it in an Archive folder?

I think those old notes can be safely deleted by now.

>  Principles
> not sure what to do with it. maybe make it in the Home page?

I think we should move this content to our developer documentation, e.g. [DEVELOPING])https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md) or [CONTRIBUTING](https://github.com/strongloop/loopback-next/blob/master/docs/CONTRIBUTING.md).

>  Project-Docs
> not sure the need of it. delete it?

Delete it.

> Publishing
> keep it

Ideally, this content should live in our developer docs tracked by git, e.g. [DEVELOPING])https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md) or a new file linked from DEVELOPING.

>  Terms-for-multiple-protocol-APIs
> seem to have useful information. keep it?

Let's keep it for now.

>  Upcoming-Releases
> keep it

+1 to keep it

**Comment by dhmlau** [comment] 2018-06-08 00:00
Closing this spike as the bigger updates for the wiki page will be tracked under #1400 .  The task will be estimated there.

**Closed by dhmlau** 2018-06-08 00:00 UTC
Labels: Core-GA, DP3, Docs, p2
