### ISSUE TITLE
Retrieving the express object

### ISSUE THREAD

**Issue by zkrami** [strongloop/loopback-next#2538] opened 2019-03-05 18:00 UTC
## Description / Steps to reproduce / Feature proposal
I want to get the express application object so I can use a custom express middleware using `app.use()`
how can I retrieve it inside the application object ?
and how can I set a controller method as the next handler for the middleware ?!
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment] 2019-03-05 18:27
We don't expose the `express` object directly at this point. There are a few options:

- Use a facade express application to compose with LB4 routes. See https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html

- Wait for https://github.com/strongloop/loopback-next/pull/2434 (or something similar) to be landed

- https://github.com/strongloop/loopback-next/issues/2389

**Comment by zkrami** [comment] 2019-03-06 09:32
I think the facade fulfill some of requirements.
but still I need to access the controller from the express middleware , so I can make CRUD manipulation.
what I am trying to achieve is quite simple actually , I want to upload a file that with pause capability using this package [node-uploadx](https://github.com/kukhariev/node-uploadx).

**Comment by raymondfeng** [comment] 2019-03-06 15:03
Have you considered to use an action to wrap the express middleware using `Sequence` - see https://loopback.io/doc/en/lb4/Sequence.html. Please note that actions can have dependency injection and therefore they can access controllers.

**Comment by raymondfeng** [comment] 2019-03-06 23:21
@zkrami I have improved https://github.com/strongloop/loopback-next/pull/2434. PTAL.

**Comment by bajtos** [comment] 2019-03-07 12:16
Closing as a duplicate of https://github.com/strongloop/loopback-next/issues/1293 and https://github.com/strongloop/loopback-next/issues/2035.

> what I am trying to achieve is quite simple actually , I want to upload a file that with pause capability using this package node-uploadx.

I think #2035 will provide the right tool for your use case, once it's implemented. Would you like to contribute the implementation yourself? We can help you along the way, please leave a comment in #2035 if you are interested.

**Closed by bajtos** 2019-03-07 12:16 UTC
