### ISSUE TITLE
HttpCachingProxy Tests fail randomly

### ISSUE THREAD

**Issue by m3hari** [strongloop/loopback-next#1430] opened 2018-06-14 05:23 UTC
## Description / Steps to reproduce / Feature proposal
Proxies HTTP requests & proxies HTTPs requests (no tunneling) test cases fail several times on my machines.
   
**Disclaimer I have very slow internet**

## Current Behavior
Tests fail

## Expected Behavior
All tests pass unconditionally

Here is the stack trace

```
     Error: Timeout of 2000ms exceeded.
     For async tests and hooks, ensure "done()" is called;
     if returning a Promise, ensure it resolves.
     (/loopback-next/packages/http-caching-proxy/dist8/test/integration/http-caching-proxy.integration.js)



```

**Comment by dhmlau** [comment] 2018-06-18 18:00
@m3hari , does it happen all the time or randomly? 
I wonder if it's similar to https://github.com/strongloop/loopback-next/issues/1407.  
@bajtos @raymondfeng, thoughts?

**Comment by bajtos** [comment] 2018-06-19 10:38
Closing as a duplicate of #1407, let's move further discussion to #1407 please.

**Closed by bajtos** 2018-06-19 10:38 UTC
