### ISSUE TITLE
Is it necessary to make @param support ObjectId type

### ISSUE THREAD

**Issue by likexoo** [strongloop/loopback-next#4317] opened 2019-12-18 02:24 UTC
## Suggestion

Support MongoDB `ObjectId` type in `@param`

## Use Cases

- Need to check if the passed parameter is a valid `ObjectId` type
- Directly use `ObjectId` type parameter, no need to do `new ObjectId()`

## Examples

```Typescript
@get('/test/{_id}')
async test(
    @param({ name: '_id', in: 'path' }) _id: ObjectId // <= !
): Promise<any> {
    // ...
}
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dougal83** [comment] 2019-12-19 14:02
Related issue #3720 as part of more robust handling of ObjectId.

**Comment by dhmlau** [comment] 2020-01-09 03:14
Thanks @dougal83. Closing as duplicate of #3720. 
@likexoo, please continue the discussion over #3720. Thanks!

**Closed by dhmlau** 2020-01-09 03:14 UTC
Labels: feature
