### ISSUE TITLE
Error in the "Dynamically adding models, repositories, and controllers during runtime" section

### ISSUE THREAD

**Issue by kvbogdanov** [strongloop/loopback-next#6001] opened 2020-07-24 07:28 UTC
There is a section "Dynamically adding models, repositories, and controllers during runtime" https://loopback.io/doc/en/lb4/Dynamic-models-repositories-controllers.html in the docs where we can find a way to add a model to API during runtime.

But. Following these steps I cannot create a CRUD controller with fields described in a model definition

```
    const bookDef = new ModelDefinition({
      name: 'book',
      properties: {
        id: {
          type: 'Number',
          required: true,
          id: 1,
        },
        title: {
          type: 'String',
          required: false,
        },
      },
    });

    const BookModel = defineModelClass<typeof Entity, {id: number; title?: string}>(
      Entity,
      bookDef,
    );

    const BookRepository = defineCrudRepositoryClass(BookModel);

    inject(`datasources.mongo`)(BookRepository, undefined, 0);
    const repoBinding = app.repository(BookRepository);

    const basePath = '/booktest';

    const DynamicController0 = defineCrudRestController(BookModel, {basePath});
    inject(repoBinding.key)(DynamicController0, undefined, 0);
    app.controller(DynamicController0);
```

CRUD controller created successfully but with no params (actually, only with params of the base Entity/Model). 

![Снимок экрана 2020-07-24 в 14 15 31](https://user-images.githubusercontent.com/2289017/88368612-9f638f00-cdb8-11ea-9c77-b7b3821deb67.png)

Expected that API could add object Book with params _id_ and _title_

There are no errors or warnings in console.

**Comment by hacksparrow** [comment] 2020-07-24 12:12
Where are you executing that code? Can you share a bare minimal app reproducing the behavior?

**Comment by hacksparrow** [comment] 2020-07-24 12:28
This is a working example, add it in the constructor of your Application class. Please make sure to import the necessary dependencies.

```ts

    @model()
    class Product extends Entity {
      @property({id: true})
      id: number;

      @property({required: true})
      name: string;

      @property()
      description?: string;

      constructor(data: Partial<Product>) {
        super(data);
      }
    }

    const db = new juggler.DataSource({connector: 'memory'});
    const ProductRepository = defineCrudRepositoryClass(Product);
    const repo = new ProductRepository(db);

    const CrudRestController = defineCrudRestController<
      Product,
      typeof Product.prototype.id,
      'id'
    >(Product, {basePath: '/products'});

    class ProductController extends CrudRestController {
      constructor() {
        super(repo);
      }
    }

    this.controller(ProductController);
```

**Comment by kvbogdanov** [comment] 2020-07-24 12:39
Thanks, but it's not suitable for me. I have to do it via ModelDefinition (that would be created dynamically) because in the real app structure of my model (Product in your example) is not available on application startup. Exactly that way described in the docs (but do not work). In other words, I'am trying to create a new model by extending Entity at runtime.

I will provide minimal demo app ASAP.

**Comment by kvbogdanov** [comment] 2020-07-27 04:29
Here it is: https://github.com/kvbogdanov/monopolia-test1

Two noticeable things added to the minimal app:
1. https://github.com/kvbogdanov/monopolia-test1/blob/master/src/dynamic-models.ts - runtime model and controller creation logic (there the main problem is)
2. Added action /ping/build in default ping controller: https://github.com/kvbogdanov/monopolia-test1/blob/master/src/controllers/ping.controller.ts

How it works: there is only one Ping controller at app startup. But if you send get request to /ping/build new CRUD controller booktest would be created (for the runtime-created model BookModel). But there are no any fields still (id and title expected)

![Снимок экрана 2020-07-27 в 11 11 18](https://user-images.githubusercontent.com/2289017/88503459-fb6a2580-cffb-11ea-8514-d2f1022bba9c.png)

![Снимок экрана 2020-07-27 в 11 26 36](https://user-images.githubusercontent.com/2289017/88503497-163c9a00-cffc-11ea-8098-a928c494b074.png)

**Comment by hacksparrow** [comment] 2020-07-28 15:11
@kvbogdanov thanks for the sample app. I am taking a look at it.

**Comment by hacksparrow** [comment] 2020-07-29 14:29
It is happening because `getModelSchemaRef()` is not generating the schema. Tomorrow I will discuss with @bajtos and come up with a plan.

**Comment by ccsreenidhin** [comment] 2020-07-31 09:44
I am facing the same issue. I use my-sql in my project. The schema properties are not displaying in explorer. But was the table created here?. The DB table was not created in my case.

**Comment by hacksparrow** [comment] 2020-07-31 14:38
A fix is landing!

**Comment by dhmlau** [comment] 2020-08-10 14:44
@hacksparrow, is this issue good to close? Thanks.

**Comment by ccsreenidhin** [comment] 2020-08-11 15:16
@hacksparrow  I adopted the fix and I am following https://loopback.io/doc/en/lb4/Dynamic-models-repositories-controllers.html. But the db tables were not created still. I tried the code from @kvbogdanov above. Thank you

**Comment by kvbogdanov** [comment] 2020-08-11 15:20
I will re-retry tomorrow, but yesterday after updating lb4 I'd still facing the problem

**Comment by ccsreenidhin** [comment] 2020-08-11 15:41
Thank you, I have managed to create the db tables by calling autoupdate after defining the repository now.

**Comment by kvbogdanov** [comment] 2020-08-12 08:44
I did lb4 update and npm update but example still doesn't work 

@hacksparrow tell me please where am I wrong?

**Comment by hacksparrow** [comment] 2020-08-12 10:01
@kvbogdanov the fix has landed on `master`, but it is not published yet. In the mean time you can do this:

1. Replace `monopolia-test1/node_modules/@loopback/repository` with `https://github.com/strongloop/loopback-next/tree/master/packages/repository`.
2. Run `npm i` and then `npm run build` in the `monopolia-test1/node_modules/@loopback/repository`.
3. Start app as usual and see the changes.

**Comment by dhmlau** [comment] 2020-09-11 01:08
@hacksparrow, is it good to close? Thanks.

**Comment by hacksparrow** [comment] 2020-12-30 17:54
Fixed in https://github.com/strongloop/loopback-next/pull/6036.

**Closed by hacksparrow** 2020-12-30 17:54 UTC
Labels: bug
