### ISSUE TITLE
Implement validation for controller methods using OpenAPI parameters

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1308] opened 2018-05-08 19:26 UTC
## Description / Steps to reproduce / Feature proposal
For DP3, we'd like inputs from http requests to be validated using a given OpenAPI spec.

- Follow up to #1306

## Acceptance Criteria
- [ ] Use the validator engine from #1294 in `parseParams` (instead of in the method decorator) to validate the coerced parameters using an OpenAPI spec

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment] 2018-05-28 15:10
I believe this is a duplicate of #118 - closing.

**Closed by bajtos** 2018-05-28 15:10 UTC
Labels: DP3, OpenAPI, Schema, Validation
