### ISSUE TITLE
Allow app developers to configure custom Express middleware

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1293] opened 2018-04-27 19:58 UTC
Allow Application and Extensions developers to mount Express middleware at application level.

**WORKAROUND:**

Our current recommendation is to create a top-level Express application (where you can easily mount any middleware) and then mount LB4 as a component (middleware) in that application. See https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html for detailed instructions.

## Acceptance Criteria

- [x] A set of APIs allowing Application developers to mount custom Express middleware
- [x] A set of APIs allowing Extension developers to contribute Express middleware to target application
- [x] Documentation for both App & Extension developers
- [x] A clear guidance on how to ensure correct middleware ordering (this may require a spike)
- [x] Implementation wise, the piece invoking middleware should be implemented as part of the Sequence handling, so that errors reported by Express middleware are routed to `reject` action. (For example, we may introduce a new sequence action to be executed before `findRoute`.)

**Out of scope**
- Register Express middleware per route, controller class or controller method - see #2035

**Comment by bajtos** [comment] 2018-06-25 07:48
Related: https://github.com/strongloop/loopback-next/issues/559#issuecomment-399077339

> I am proposing to enhance RestServer/RestApplication with an API allowing consumers to mount static files, for example `app.static(path, options)`. This API should leverage Express middleware [server-static](https://www.npmjs.com/package/serve-static) as an implementation detail.
>
> With this new API in place, we can either write an API Explorer component bundling swagger-ui and calling `app.static(pathToSwaggerUI)`, or preferably write a short guide explaining LB4 users how to add swagger-ui to their project themselves.

**Comment by bajtos** [comment] 2018-07-30 12:37
IMO, this is out of 4.0 GA scope as we have defined it. Relabeling this story as post-GA.

**Comment by virkt25** [comment] 2018-07-31 16:16
Simplifying usage is probably out of scope of GA but I think we should at the very least have some documentation around how a user can add some express middleware to their application (static file serving for example) by overriding the default `requestHandler`. -- I think that's something important for GA.

**Comment by bajtos** [comment] 2018-11-22 14:06
I feel the issue description is out of sync with the issue title. I am going to rewrite the description to match the title and focus on LB4 user experience.

Below is the original description for posterity.

---


Since we have decided to use Express as our underlying HTTP framework, `@loopback/rest` and `@loopback/http-server` can be refactored with the use of Express APIs. 

## Current Behavior
Code is not optimized to use Express APIs.

## Expected Behavior
Use Express APIs and remove redundant code.

## Acceptance Criteria
All HTTP stuff should be handled using Express API, wherever possible.
- Our `parseParam` logic should be kept
- When an express middleware has already parsed the JSON body, our parseParam should detect this and accept the parsed JSON body from the express middleware
- redesign our sequence so that express middleware could handle errors thrown by our controllers (`reject`)
- docs, blogs, etc.

**Comment by bajtos** [comment] 2019-03-05 13:55
Relevant work: https://github.com/strongloop/loopback-next/pull/2434

**Comment by codejamninja** [comment] 2019-06-21 09:55
I build a loopback component that lets you inject express middleware into the sequence. You can filter it by controllers by using the `@middleware('auth')` annotation, or you can directly inject middleware into the `@middleware(myExpressMiddleware)` annotation.

https://github.com/codejamninja/lb4-middleware

**Comment by raymondfeng** [comment] 2020-05-12 16:11
Done.

See
https://loopback.io/doc/en/lb4/Middleware.html
https://loopback.io/doc/en/lb4/Express-middleware.html

**Closed by raymondfeng** 2020-05-12 16:11 UTC
Labels: 2020Q2, REST, feature, feature parity, user adoption
