### ISSUE TITLE
on cli generating relation

### ISSUE THREAD

**Issue by serkandemirel0420** [strongloop/loopback-next#2080] opened 2018-11-27 15:01 UTC
Comparing to version 3 relation part is very complicated.  Also i am curious, is it possible to generate relation over cli like in version 3?

**Comment by jannyHou** [comment] 2018-11-27 16:04
@serkandemirel0420 The relation CLI is a major feature we would like to have soon, several discussions have been taken place in story https://github.com/strongloop/loopback-next/issues/1359, you can also use that story to track the implementation. 
Opinions/feedback are welcomed.

**Comment by dhmlau** [comment] 2018-11-28 16:33
@serkandemirel0420 , I'd like to close this issue as duplicate of https://github.com/strongloop/loopback-next/issues/1359, as @jannyHou stated.  Please continue the discussion over there.  Thanks.

**Closed by dhmlau** 2018-11-28 16:33 UTC
