### ISSUE TITLE
bug: ajv async validation 

### ISSUE THREAD

**Issue by mrbatista** [strongloop/loopback-next#4939] opened 2020-03-20 17:09 UTC
## Steps to reproduce

1. git clone https://github.com/mrbatista/loopback-next/tree/bug-ajv-async-validation

1. `cd sanbox/bug-ajv-async-validation`

1. `npm install`

1. `npm test`

## Current Behavior

The test fail with error:
`Unhandled error in POST /products: 500 Error: async keyword in sync schema`

## Expected Behavior

Fail with 422 UnprocessableEntityError
```js
{
   "error":{
      "statusCode":422,
      "name":"UnprocessableEntityError",
      "message":"The request body is invalid. See error object `details` property for more info.",
      "code":"VALIDATION_FAILED",
      "details":[
         {
            "path":"/name",
            "code":"uniqueness",
            "message":"should pass \"uniqueness\" keyword validation",
            "info":{
               "keyword":"uniqueness"
            }
         }
      ]
   }
}
```

## Link to reproduction sandbox

https://github.com/mrbatista/loopback-next/tree/bug-ajv-async-validation

## Additional information

After some investigation the problem is related to the definition of the `warehouse` property.
I have this issue if the property refers to the type of another Model.
```js
  @property({
    type: Warehouse,
          ^^^^^^^^^
  })
  warehouse: Warehouse;
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment] 2020-03-22 04:42
It seems to be a duplicate of https://github.com/epoberezkin/ajv/issues/647

**Closed** 2020-03-23 20:45 UTC
Labels: bug
