### ISSUE TITLE
@belongsTo doesn't create relations in database 

### ISSUE THREAD

**Issue by odykyi** [strongloop/loopback-next#4921] opened 2020-03-19 08:39 UTC
**User Model:**
```ts

import { Entity, model, property } from '@loopback/repository';

export class Users extends Entity {
  @property({
    type: 'string',
    id: true,
    generated: true
  })
  id?: string;

  @property({
    type: 'string',
    required: true,
  })
  full_name: string;

  constructor(data?: Partial<Users>) {
    super(data);
  }
}

export interface UsersRelations {
  // describe navigational properties here
}

export type UsersWithRelations = Users & UsersRelations;

```

-----------------

**User Device Model:**
```ts

import { Entity, model, property, belongsTo } from '@loopback/repository';
import { Users } from './users.model';

export class UserDevice extends Entity {
  @property({
    type: 'string',
    id: true,
    generated: true,
  })
  id?: string;

  @property({
    type: 'string',
    required: true,
  })
  device_id: string;


  @belongsTo(() => Users)
  user_id: string;

  constructor(data?: Partial<UserDevice>) {
    super(data);
  }
}

export interface UserDeviceRelations {
  // describe navigational properties here
}

export type UserDeviceWithRelations = UserDevice & UserDeviceRelations;
```

**Comment by odykyi** [comment] 2020-03-19 08:39
@fabien @rmg @klassicd @ceefour

**Comment by odykyi** [comment] 2020-03-19 08:40
@achrinza

**Comment by achrinza** [comment] 2020-03-19 10:53
LoopBack 4 does not create database constraints at the moment: #2331

**Comment by achrinza** [comment] 2020-03-19 10:56
Duplicate of #2331

**Closed by achrinza** 2020-03-19 10:56 UTC
Labels: bug

**Comment by odykyi** [comment] 2020-03-19 13:47
@achrinza I mean references in sql FK

**Comment by achrinza** [comment] 2020-03-19 13:48
Apologies if i wasn’t clear; database constraints = foreign keys

**Comment by odykyi** [comment] 2020-03-19 14:10
this works for me 
```

@model({
  settings: {
    foreignKeys: {
      fk_todo_todoListId: {
        name: 'fk_todo_todoListId',
        entity: 'TodoList',
        entityKey: 'id',
        foreignKey: 'todolistid',
      },
    },
  },
})
export class Todo extends Entity {
  //etc.
}

```
https://loopback.io/doc/en/lb4/todo-list-tutorial-sqldb.html#specify-the-foreign-key-constraints-in-todo-model

**Comment by achrinza** [comment] 2020-03-19 14:16
Apologies, didn’t know your requirement was PostgreSQL.

Glad you’ve found a solution.

Unfortunately this isn’t universal across other connectors.

**Comment by odykyi** [comment] 2020-03-19 14:17
I use mysql
