### ISSUE TITLE
Document the LoopBack 4 request-response cycle

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#1833] opened 2018-10-10 05:57 UTC
This will be a low-level description of all the components involved in the request-response handling process. It will help consumers and developers interested in knowing what's happening under the hood.

**Comment by marioestradarosa** [comment] 2018-10-11 05:28
@hacksparrow , I can't wait to see this documentation. I am hungry to learn.

**Comment by b-admike** [comment] 2018-10-23 18:31
based on @raymondfeng's feedback, here are some details to consider in this narrative (opt for visualization for clarity):
- node.js http layer
- express listening on given port (restServer)
- middleware processing
- sequence actions
- default sequence 
- routing (find the route, parse parameters, request body (checking OpenAPI spec), invoking controller method/handler with parameters)
- serialize response, reject if necessary
- send action 
- how each request creates a controller instance

Try to group it into two phases: 1st phase interaction between API client and LoopBack, 2nd phase API business logic interact with existing backend services using repositories/datasources/models.

**Comment by dhmlau** [comment] 2019-03-19 15:36
Closing as duplicate of https://github.com/strongloop/loopback-next/issues/2390

**Comment by bajtos** [comment] 2019-03-29 16:13
@dhmlau I slightly disagree. The goal of #2390 is to describe request-handling flow at high level, especially in regards to different Express middleware types. I am concerned that by including low-level details listed in https://github.com/strongloop/loopback-next/issues/1833#issuecomment-432366603, we will greatly inflate the scope of #2390. Was this change taken into account when #2390 was estimated?

**Comment by dhmlau** [comment] 2019-03-29 16:17
When discussing with @raymondfeng , he mentioned that this is a duplicate of #2390.  Since #2390 has more descriptions so we're closing this issue instead.  
If two are different, is there any sequence we should work on the task? 

@raymondfeng , what's your thoughts?

**Comment by dhmlau** [comment] 2019-03-29 16:17
Let's reopen it for now so that we won't forget.

**Comment by bajtos** [comment] 2019-03-29 16:18
> If two are different, is there any sequence we should work on the task?

I would start with #2390, I think it's a smaller task.

**Comment by dhmlau** [comment] 2020-03-11 12:39
FYI - There's a diagram at the top of https://loopback.io/doc/en/lb4/Concepts.html, it would be a good starting point. 

https://loopback.io/pages/en/lb4/imgs/key-concepts-overview-diagram.png

**Comment by dhmlau** [comment] 2020-03-24 13:35
PR in progress: https://github.com/strongloop/loopback-next/pull/4914

**Comment by dhmlau** [comment] 2020-03-25 18:40
Closing this issue as #4914 lands

**Closed by dhmlau** 2020-03-25 18:40 UTC
Labels: 2020Q1, Docs
