### ISSUE TITLE
Better way to link to local version of loopback-next for developers

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#514] opened 2017-08-16 01:42 UTC
# Description/Steps to reproduce
As a developer of the LoopBack-Next framework I want to be able to test the framework by linking to it from my sample app. The current process of `npm run build` and `npm link` in `loopback-next` will link the `loopback-next` repository but my local sample app will likely be importing from `@loopback/*`. Current workaround would be to replace `@loopback/*` with `loopback-next/packages/*` which can be tedious as you will likely have to undo the changes in the example app. 

`npm link` needs to link the packages to `@loopback/*` and ensure the packages that dependent on each other are also linked to the local version correctly. I can go into all the packages and run `npm link` which links them to `@loopback/*` but a package like `@loopback/repository` is dependent on `@loopback/context` and will re-install it locally in the global module and hence this will now be using a difference instance of Context than my sample application or Core. 

# Expected result
I should be able to `npm link` loopback-next repo locally and my sample app should pick that up without changing imports from `@loopback/*` to `loopback-next/packages/*`

# Additional information
Not linking the globally linked dependent modules to each other will result in weird error messages saying bindingKey not found by resolver.

**Comment by kjdelisle** [comment] 2017-08-26 19:43
@raymondfeng @bajtos My 2c:
I think this is critically important; having difficulty working with the packages in the monorepo is only going to discourage contributions from the community.

**Comment by raymondfeng** [comment] 2017-08-26 21:04
@virkt25 Can you try to set up `NODE_PATH` per https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders and test it out?

**Comment by bajtos** [comment] 2017-08-28 12:15
I don't think `NODE_PATH` would work, because `require('@loopback/core')` will be looking for a directory called `$NODE_PATH/@loopback/core`, while our project layout is `packages/core`.

@virkt25 Have you tried to run `npm link` in all packages first, and then `rm -rf packages/*/node_modules && lerna bootstrap`? (I.e. drop the dependencies installed by `npm link` and let `lerna` to re-create them?)

I remember it used to be possible to have globally linked packages to use linked dependencies in the past, I think I was using this quite often when working on generator-loopback and loopback-workspace. Could it be that the order in which the packages are `npm link-`ed matter? E.g. if you `npm link` in `context` first, then `npm link` run from `repository `should see that the `context` package is already available in global `node_modules` and don't install a new copy from npmjs.
If that's the case, then writing a custom `package` script should solve the problem, because lerna invokes package scripts in the order of inter-package dependencies.

Possibly related reading:
 - https://github.com/lerna/lerna/issues/906
 - https://github.com/lerna/lerna/issues/11#issuecomment-234738279

It looks like `lerna bootstrap` is *not* using `npm link` for inter-package dependencies, I think this may be the reason why `npm link` is overwriting our linked dependencies.

To me, it looks like we have found a gap in lerna+npm integration.

**Comment by virkt25** [comment] 2017-08-29 01:11
I haven't had a chance to try the suggestions but I was to setup `NODE_PATH` then I would have to add each package individually to the pack ... `loopback-next/packages/*` which seems like a lot of work ... especially if the number of packages grows. 

And yea I think I tried running npm link but it reinstalls dependencies in each package and rebuilds it so if things aren't done in the correct order we'll end up with apps and inter-dependent using different instances of the package which will result in more pains and headaches (I've been through ... ended up with 2 instances of Context and bindings/injection not working).

Writing a script to correctly link the packages in the right order would seem to be the right approach but I wonder if there's a way to determine the right order automatically instead of manually as that way might be too brittle & break. 

I did come across this article and wonder if peerDependencies can help with the linking process ... but at the same time I thought npm5 installed everything in a flat hierarchy. 
Link: http://codetunnel.io/you-can-finally-npm-link-packages-that-contain-peer-dependencies/

And an interesting article about PouchDB running into a similar issue & their switch to Alle
https://gist.github.com/nolanlawson/457cdb309c9ec5b39f0d420266a9faa4

**Comment by bajtos** [comment] 2017-08-29 08:17
> we'll end up with apps and inter-dependent using different instances of the package which will result in more pains and headaches (I've been through ... ended up with 2 instances of Context and bindings/injection not working).

Hey, having two instances of `@loopback/context` is actually an important case that may happen in real-world applications too! Could you please open a new GH issue describing how to reproduce the problem you have encountered?

Here is how it can (will?) happen:
 - We release `@loobpack/context@4.0.0` and everybody starts using it to build apps, extensions, etc.
 - After some time, we release `@loopback/context@5.0.0` and upgrade core packages in loopback-next to use this new version.
 - The ecosystem will need some time to pick up these changes and upgrade their dependencies too. Many extensions will stay on `@loopback/context@4.0.0` for months.
 - People building new applications (using core packages v5.x) will start seeing errors that are difficult to debug when they add a 3rd-party/community extension that's still on `@loopback/context@4.0.0`.

I think this is not a new problem, we have already run into it in the past, when loopback-datasource-juggler was installed as a peer dependency of loopback. The peer-dependency-based design solved the problem in some cases, but there were still situation where it failed. Eventually we had to fix our code to not rely on a global singleton instance of loopback-datasource-juggler. We had similar problems with strongloop's cluster-related modules.

IMO, we will need to fix `@loopback/context` and/or `reflect-metadata` to correctly support the situation where multiple instances of this module(s) are installed in application's dependency tree.

See https://github.com/strongloop/loopback-next/pull/54 for some ideas and example code that's related to this problem.

**Comment by raymondfeng** [comment] 2017-09-01 16:15
FYI: I debugged the reflect-metadata issue before. Unfortunately `reflect-metadata` uses a singleton to store information. As a result, multiple instances of `@loopback/context` don't work well.

**Comment by virkt25** [comment] 2017-09-08 15:01
That's a clever approach @bajtos that works and solves this problem! I am however now comfortable with this approach since anyone working on LBNext and trying to use a development app to debug / test locally will move their sample app under the same folder, might forget to exclude it from the commit and would have to consistently deal with moving sample app in / out of the folder / ignoring it, etc. Doesn't seem like the best developer experience.

I think we need to provide them a better alternative (I'm personally thinking a script which can link the dependencies in order to the global node_modules folder as the correct name `@loopback/package-name`. The script can be run with `npm link`.

**Comment by bajtos** [comment] 2017-09-12 14:38
> Doesn't seem like the best developer experience.

Makes sense. 

> might forget to exclude it from the commit 

Perhaps we can create a placeholder directory in loopback-next, something like `packages/app`, that will be listed in our `gitignore`  and then tell people to put their app there? Obviously, that won't work for a mesh of microservices that needs multiple apps to run at the same time.

> and would have to consistently deal with moving sample app in / out of the folder / ignoring it, etc. 

I think you can do a symlink from the place where you are keeping your sources to loopback-next's `packages` folder?

> I think we need to provide them a better alternative

I agree we need a process that's as frictionless as possible. I would be more than happy if somebody else could spent some time investigating other possible approaches and ideas 👍 

---

I am going to clear my assignment and move this task back to planning column.

**Comment by dhmlau** [comment] 2018-03-27 16:38
This could be a blog explaining how to do it.

**Comment by raymondfeng** [comment] 2019-05-07 20:52
I think this issue should be closed:

1. With `loopback-next/sandbox`, apps and extension modules can be either copied or linked into `sandbox`.
2. Run `npm i` under `loopback-next`
3. Now your sandbox app/ext has dependencies resolved to modules in `loopback-next`.

**Comment by dhmlau** [comment] 2019-05-08 21:55
From the above comment, I'm closing this issue.

**Closed by dhmlau** 2019-05-08 21:55 UTC
Labels: 2019Q2, Docs, Internal Tooling, developer-experience, p3
