### ISSUE TITLE
loopback/authentication-passport SAML

### ISSUE THREAD

**Issue by L-Luciano** [strongloop/loopback-next#4738] opened 2020-02-25 13:46 UTC
## Steps to reproduce

Configure loopback/authentication-passport with saml

configuredSamlStrategy(): Strategy {
    return new Strategy(
      {
        path: '/api/login/callback',
        entryPoint: 'http://localhost:8090/auth/realms/osmos/protocol/saml',
        issuer: '*****'
      },
      this.verify
    );
  }

## Current Behavior

Error : 500 TypeError: Cannot read property 'samlFallback' of undefined

authenticate for saml take parameters options but the authenticate function send only the request.

https://github.com/strongloop/loopback-next/blob/master/extensions/authentication-passport/src/strategy-adapter.ts

## Expected Behavior

We can add options in authenticate method for strategy adapter.

**Comment by achrinza** [comment] 2020-02-25 14:40
Hi, thanks for the report. Could you provide a minimum reproduction sandbox repo on GitHub so that we could look into the code?

________________________________

**Comment by L-Luciano** [comment] 2020-02-25 15:14
I Had some files in sandox : 

https://repl.it/repls/DamagedSuperiorFiles

I use my saml strategy on the last route in user controller

Sorry, I can't push my repo on github. If you need more, tell me which files you need.

Regards,

**Comment by L-Luciano** [comment] 2020-02-25 15:38
Additional Info : 
I opened a bug in passport-saml plugin.
I suppose they can fix the pb too.
https://github.com/bergie/passport-saml/issues/424

**Comment by dhmlau** [comment] 2020-03-06 18:09
@emonddr, could you please take a look? Thanks.

**Comment by emonddr** [comment] 2020-03-13 18:23
@jannyHou  PTAL? Thx.

**Comment by jannyHou** [comment] 2020-03-16 18:43
looking, will reply asap

**Comment by jannyHou** [comment] 2020-03-17 21:45
@L-Luciano Thank you for uploading the files 👍 as what you probably already discovered, the `options` is provided when you instanciate the `Strategy` like 
```ts
 // Takes in the verify callback function and returns a configured basic strategy.
  configuredSamlStrategy(): Strategy {
    return new Strategy(
      {
        path: '/api/login/callback',
        entryPoint: 'http://localhost:8090/auth/realms/osmos/protocol/saml',
        issuer: 'osmos'
      },
      this.verify
    );
  }
```

When instance gets passed to the `StrategyAdapter`, the option is already configured, that's why the `StrategyAdapter` itself doesn't deal with options.

In case you still want to configure the adapter, you can extend the adapter class and follow instructions in https://loopback.io/doc/en/lb4/Loopback-component-authentication.html to inject your adapter configuration.

I am double checking https://github.com/bergie/passport-saml/issues/424 to make sure the fix will be in that repository.

**Comment by abjagtap** [comment] 2020-03-25 11:01
@L-Luciano found any solution?

**Comment by L-Luciano** [comment] 2020-03-25 13:59
Hello,
I decided to use OpenId Passport and use keycloak to connect to my saml identityProvider.

There is no answer from the package passport-saml.

I don't try to use a custom stategy adapter but now you have an example in the loopback page. 

Regards,

**Comment by pathakbhaskar** [comment] 2020-03-25 14:40
but guess this somehow beats the purpose. Seems there is no other way other than opting for a work around as no response from package passport-saml.

**Comment by abjagtap** [comment] 2020-03-25 16:59
Hello @L-Luciano , create new custom strategy adapter but getting same error

**Comment by L-Luciano** [comment] 2020-03-26 09:03
Hello @abjagtap,
I think you have to use the passport-saml package yourself to pass the option that you handle in the authenticate passport method.

Sorry, I don't test that because I found a workaround with keycloak.

Regards

**Comment by jannyHou** [comment] 2020-05-01 14:50
@L-Luciano Thank you for providing the example in https://repl.it/repls/DamagedSuperiorFiles, it's very helpful for communities to follow.

Since there is no activity in bergie/passport-saml#424 yet, I am closing this issue. Feel free to reopen it and continue the conversation if you need. Thanks for understanding.

**Comment by pilare** [comment] 2020-09-23 13:20
@jannyHou is there a chance for reopening this issue and providing support for passport-saml as additional strategy in passport-login example?

https://github.com/strongloop/loopback-next/tree/master/examples/passport-login

This example is immensely helpful to integrate loopback 4 application with multiple Authentication providers. 

On top of Facebook and Google. I was able to connect it keycloak with customOAuth2 strategy, after modifying hardcoded verification path in  `oauth2ProfileFunction`. But I was hoping to get it connected directly to Saml Idp, as this is crucial for my current project.

**Comment by jannyHou** [comment] 2020-09-24 19:29
@pilare Sure. Would you like to submit a PR implementing it? I can help review.

**Closed** 2020-09-24 19:30 UTC
Labels: Authentication, bug
