### ISSUE TITLE
[API-Explorer] Create a self-hosted component

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#749] opened 2017-11-17 16:43 UTC
## Story
As a LoopBack4 user, I would like to test out my API endpoints on a self-hosted server.

## Acceptance Criteria
TBD

**Comment by bajtos** [comment] 2017-11-21 14:08
Here is the tricky part: right now, the REST transport does not allow controllers to control the response content type, there is no way how to implement our own variant of Express' [server-static middleware](https://www.npmjs.com/package/serve-static). We need to figure this out as a pre-requisite.

**Comment by bajtos** [comment] 2017-12-12 16:53
Closing as a duplicate of #559

**Closed by bajtos** 2017-12-12 16:53 UTC
Labels: API Explorer, MVP, needs-estimate, team-apex
