### ISSUE TITLE
Update embedded models in Loopback 4

### ISSUE THREAD

**Issue by naveenkumashi** [strongloop/loopback-next#2011] opened 2018-11-10 12:02 UTC
## Description / Steps to reproduce / Feature proposal
I have the following model relationship in my LoopBack 4 application: A Survey has 1-many relationship with Question, Question has 1-many relationship with Option.

Am using MongoDB as the database. I am unable to figure out how to implement a PUT/PATCH REST api, that can update the entire Survey model containing the Questions and Options.

## Current Behavior
 I get the following exception when i try a PATCH on the sample request JSON below:

Exception: Unhandled error in PATCH /5be3e00aad0df83d10e580d1: 500 TypeError: Class constructor Question cannot be invoked without 'new' at Function.DataAccessObject._coerce (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\dao.js:1799:22) at doUpdate (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\dao.js:2735:20) at C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\dao.js:2714:11 at doNotify (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:155:49) at doNotify (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:155:49) at Function.ObserverMixin._notifyBaseObservers (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:178:5) at Function.ObserverMixin.notifyObserversOf (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:153:8) at Function.ObserverMixin._notifyBaseObservers (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:176:15) at Function.ObserverMixin.notifyObserversOf (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:153:8) at C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\dao.js:2699:11 at doNotify (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:155:49) at doNotify (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:155:49) at Function.ObserverMixin._notifyBaseObservers (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:178:5) at Function.ObserverMixin.notifyObserversOf (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:153:8) at Function.ObserverMixin._notifyBaseObservers (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:176:15) at Function.ObserverMixin.notifyObserversOf (C:\Users\nk\Documents\Project\backend\surveyService\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)

Sample PATCH request: [{ "title": "Some survey title 1", "description": "Some survey title 1", "questions": [{ "options": [{ "description": "Some option description 1", "type": "Option" }], "description": "Some question description 1" }] }]

## Expected Behavior
It should be possible to update embedded models.

Thanks in advance.

**Comment by jedmarcnocum** [comment] 2018-12-06 04:59
I am having the same problem. Updating embedded Model (array) throws the same error even in the [example-shopping](https://github.com/strongloop/loopback4-example-shopping) sample API. 

``500 TypeError: Class constructor ShoppingCartItem cannot be invoked without 'new' at Function.DataAccessObject._coerce (C:\Users\jedma\Desktop\loopback4-example-shopping-master\loopback4-example-shopping-master\node_modules\loopback-datasource-juggler\lib\dao.js:1869:22) ``

**Comment by saurabhg22** [comment] 2018-12-09 09:40
Getting same error:
Unhandled error in POST /users: 500 TypeError: Class constructor Phone cannot be invoked without 'new'
    at User.set [as phone]

```js
import { Entity, model, property } from '@loopback/repository';


@model()
class Phone {
  @property()
  number: number;

  @property()
  code: string;
}

@model()
export class User extends Entity {
  @property({
    type: 'string',
    id: true,
  })
  id: string;


  @property()
  name: string;

  @property()
  phone: Phone;

  constructor(data?: Partial<User>) {
    super(data);
  }
}
```

**Comment by bajtos** [comment] 2018-12-10 10:08
Closing as a duplicate of https://github.com/strongloop/loopback-next/issues/2130

**Closed by bajtos** 2018-12-10 10:08 UTC
