### ISSUE TITLE
(regression) toObject strips relations since #5348

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [strongloop/loopback-next#5951] opened 2020-07-16 21:30 UTC
## Steps to reproduce

1. Define an entity type that has a relation (e.g. `hasMany`)
2. Create an instance of that entity with the relation populated
3. Call `toObject()` on the instance and inspect the returned object

## Current Behavior

* The returned object no longer has any relation properties present

## Expected Behavior

* Relation properties are present, filled with recursive `toObject` conversions

## Additional information

Compare:
https://github.com/strongloop/loopback-next/pull/5348/files#diff-19d587a68f35dd7b994be40da04e505bR278

vs `toJSON` that the old code used to call, and which checks `def.relations`:

https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/model.ts#L308

## Related Issues

Haven't found any yet

**Comment by dhmlau** [comment] 2020-07-16 23:44
@jannyHou, could you please take a look? Thanks.

**Comment by bajtos** [comment] 2020-07-17 07:38
Thank you for a well-described bug report, @mgabeler-lee-6rs 👏

**Comment by jannyHou** [comment] 2020-07-17 14:09
Good catch @mgabeler-lee-6rs and thank you for investigating the reason, confirmed the relation properties are missing, should be fixed.

**Closed** 2020-07-24 13:22 UTC
Labels: bug, interrupt, regression
