### ISSUE TITLE
Autorebuild

### ISSUE THREAD

**Issue by guitarhero1** [strongloop/loopback-next#2462] opened 2019-02-24 12:34 UTC
Please, how can I launch app, that will be rebuilt after changes in code? I'm not able to figure out...

**Comment by shadyanwar** [comment] 2019-02-24 12:48
Some ideas were discussed in https://github.com/strongloop/loopback-next/issues/2242. The issue is still open though.

**Comment by guitarhero1** [comment] 2019-03-10 09:01
up

**Comment by dhmlau** [comment] 2019-06-18 18:42
To get everything in one place, let's continue the discussion in #2242. 
Closing this issue in favor of #2242.

**Closed by dhmlau** 2019-06-18 18:42 UTC
