### ISSUE TITLE
Filter where not working for phone number format string "+000000000"

### ISSUE THREAD

**Issue by UnclePetros** [strongloop/loopback-next#3621] opened 2019-08-30 10:30 UTC
## Steps to reproduce

- Have a collection document to look for
- Have a string field inside this document with a plus (+) char inside
- Use the autogenerated find method in a controller to filter by this field

## Current Behavior

No data is returned.  
If I remove the plus char from the field, filter works fine.

## Expected Behavior

Document data is retrieved

**Comment by raymondfeng** [comment] 2019-08-30 16:28
What database do you use?

**Comment by UnclePetros** [comment] 2019-08-30 16:29
mongodb

**Comment by raymondfeng** [comment] 2019-08-30 16:44
Is the phone number defined as `string` type in the model?

**Comment by UnclePetros** [comment] 2019-08-30 17:50
Yes, it is, and is required.
I'm using the like filter at moment without the +, but is not the same.

**Comment by warmansuganda** [comment] 2019-09-01 20:52
Try request with Regex Operator

Example: 
http://localhost:3000/users?filter[where][phone][regexp]=/000000000/i

Root cause:
(+) is a special character

CMIIW

**Comment by dhmlau** [comment] 2019-09-27 22:24
@UnclePetros, does the above comment from @warmansuganda help resolving your issue?

**Comment by UnclePetros** [comment] 2019-10-01 06:30
> @UnclePetros, does the above comment from @warmansuganda help resolving your issue?

I've tried. Unfortunately, not.
No data is retrieved.

**Comment by UnclePetros** [comment] 2019-10-01 06:41
> I believe that a raw `+` character in URL is decoded as a space ` `. What is the exact URL you are invoking, @UnclePetros?
> 
> What happens when you invoke the controller method from JavaScript directly, e.g. from a test?

Ok.
I mainly use postman to do my quick tests.
I have in my document in mongodb this phone string field: _"+1234567890"_.
I do this call from postman: _localhost:3003/api/digital-users/?filter={"where":{"phone":"+1234567890"}}_
No data is retrieved.

If I remove the plus char in the phone field in document in db, and remove the plus char in the api call filter, data is retrieved correctly.

Moreover, if I try to use the loopback explorer to do the query, it doesn't seems to work properly.
It retrieves always all documents in the collection no matter what filter is used.

About the special characters: I believe if I can store informations containing a special char, I should have the possibility to look for them.

Thank you.

**Comment by bajtos** [comment] 2019-10-01 14:36
Thank you for the clarification, @UnclePetros. It's important to know that you are using MongoDB, the behavior may be specific to this database.

> I do this call from postman: `localhost:3003/api/digital-users/?filter={"where":{"phone":"+1234567890"}}`
> No data is retrieved.

Here is an experiment you can try yourself:

```
$ node
Welcome to Node.js v12.11.0.
Type ".help" for more information.
> querystring.parse('filter={"where":{"phone":"+1234567890"}}')
[Object: null prototype] {
  'filter': '{"where":{"phone":" 1234567890"}}'
}
```

As you can see, Node.js is converting the plus character `+` to a space character ` `, running the following query as a result:

```
{where: {phone: ' 1234567890'}}
```

You need to URL-encode values in your query, for example by calling [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).

```
$ node
> encodeURIComponent('{"where":{"phone":"+1234567890"}}')
'%7B%22where%22%3A%7B%22phone%22%3A%22%2B1234567890%22%7D%7D'
```

Here is a URL you can try from Postman:

```
localhost:3003/api/digital-users/?filter=%7B%22where%22%3A%7B%22phone%22%3A%22%2B1234567890%22%7D%7D
```

At minimum, you need to replace `+` to `%22`:

```
localhost:3003/api/digital-users/?filter={"where":{"phone":"%221234567890"}}
```
> Moreover, if I try to use the loopback explorer to do the query, it doesn't seems to work properly.
> It retrieves always all documents in the collection no matter what filter is used.

That's a known limitation of swagger-ui, the library we use in API Explorer. See https://github.com/strongloop/loopback-next/issues/2208. It's very annoying and unfortunately also difficult to fix :(

**Comment by bajtos** [comment] 2019-10-01 14:36
I am closing the issue as resolved. Feel free to re-open it if url-encoding your `filter` query does not solve the problem.

**Closed by bajtos** 2019-10-01 14:36 UTC
Labels: REST, Repository, db:MongoDB, question

**Comment by pilare** [comment] 2020-03-19 07:20
I had the same problem when filtering fields containing plus characters.  @bajtos thanks for the solution. However, there is a mistake in proposed replacement. Correct replacement for `+` is `%2B`. Just for anybody who will end up here later looking for help with this.

Here is my line to replace multiple plus characters:
```
const fixed = text.replace(/\+/g,'%2B')
```
