### ISSUE TITLE
Unable to create a recursive model in v4

### ISSUE THREAD

**Issue by danysz** [strongloop/loopback-next#2250] opened 2019-01-13 03:23 UTC
Created a "Category model"

```
import {Entity, model, property, hasMany, belongsTo} from '@loopback/repository';

@model()
export class Category extends Entity {
  @property({
    type: 'number',
    id: true,
    required: false,
    generated: true,
  })
  id: number;

  @property({
    type: 'string',
    required: true,
  })
  name: string;

  // @hasMany(() => Category, {keyTo:'parentId'})
  // subCategories?: Category[];

  @belongsTo(() => Category)
  parentId: number;


  constructor(data?: Partial<Category>) {
    super(data);
  }
}
```

added the repository
```
import {
    DefaultCrudRepository,
    BelongsToAccessor,
    HasManyRepositoryFactory,
    repository,
    juggler
} from '@loopback/repository';
import {Category} from '../models';
import {DbDataSource} from '../datasources';
import {inject, Getter} from '@loopback/core';

export class CategoryRepository extends DefaultCrudRepository<Category,
    typeof Category.prototype.id> {
//    public readonly subCategories: HasManyRepositoryFactory<Category, number>;

    public readonly parent: BelongsToAccessor<Category, number>;

    constructor(
        @inject('datasources.db') dataSource: DbDataSource,

    ) {
        super(Category, dataSource);

        // this.subCategories = this.createHasManyRepositoryFactoryFor(
        //     'subCategories',
        //     Getter.fromValue(this),
        // );

        this.parent = this.createBelongsToAccessorFor(
            'parent',
            Getter.fromValue(this),
        );
    };
}
```

I am trying to add also the "subCategories" property so I will be able to find in each "category" the "child" list.

If I uncomment and run the code I got error : 
Cannot start the application. RangeError: Maximum call stack size exceeded
code ELIFECYCLE

If I try to run without defining the "keyTo" in "hasMany" property I am getting this error:
Error: Invalid hasMany definition for Category#subCategories: target model Category is missing definition of foreign key categoryId

Please advice.

Also I would like to know how can I add a custom index on the "parentId" field.

Thanks

**Comment by jannyHou** [comment] 2019-01-15 01:17
@danysz From your description you are trying to create a relation from a model to itself, this is a feature tracked in https://github.com/strongloop/loopback-next/issues/1571 we are investigating in story https://github.com/strongloop/loopback-next/issues/1682.

**Comment by dhmlau** [comment] 2019-01-22 16:49
Closing as duplicate of #1571

**Closed by dhmlau** 2019-01-22 16:49 UTC
