### ISSUE TITLE
GeoPoint type not work with getModelSchemaRef

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#4017] opened 2019-10-28 15:31 UTC
## Steps to reproduce

Generating a model, a repository and a controller already finds the error when compiling

## Current Behavior

Loopback crash

-------------------

Commenting on the piece of openAPI code works correctly

![Captura de pantalla 2019-10-28 a las 16 25 54](https://user-images.githubusercontent.com/13822438/67692399-6240ac80-f9a0-11e9-9b65-73f6fadd9008.png)
![Captura de pantalla 2019-10-28 a las 16 26 31](https://user-images.githubusercontent.com/13822438/67692400-6240ac80-f9a0-11e9-8a1e-1a1289823422.png)

**Comment by bajtos** [comment] 2019-11-01 08:37
Closing as a duplicate of https://github.com/strongloop/loopback-next/issues/1981

**Comment by bajtos** [comment] 2019-11-01 08:37
Duplicate or #1981

**Closed by bajtos** 2019-11-01 08:37 UTC
Labels: bug
