### ISSUE TITLE
Model Validation - custom business logic

### ISSUE THREAD

**Issue by mastermunj** [strongloop/loopback-next#4600] opened 2020-02-10 05:07 UTC
Hi,

I need help with Model validations. Is there anything similar to LB3 Model.validateAsync?

E.g. When someone is trying to register with a mobile number, I want to check whether mobile is on the blocked list.

**Comment by achrinza** [comment] 2020-02-10 09:20
Hi @mastermunj; AFAIK models are meant to only provide data structure (as part of the LB4 redesign). However, a similar validation can be accomplished by [adding custom repository methods](https://loopback.io/doc/en/lb4/Repositories.html#example-custom-connector-crud-methods) or processing validation at the controller-level.

**Comment by mastermunj** [comment] 2020-02-11 12:03
Hi @achrinza, #1872 is more or less similar to my query. As of now, LB4 doesn't seem to have the direct support of the validation at the data access layer.

**Comment by achrinza** [comment] 2020-02-11 14:50
Seems like it! In that case, we can close this a a duplicate of #4187 and continue discussion there.

**Comment by achrinza** [comment] 2020-02-11 14:50
Duplicate of #4187

**Closed by achrinza** 2020-02-11 14:50 UTC
Labels: question
