### ISSUE TITLE
Cannot override query parameter default value in controller method

### ISSUE THREAD

**Issue by lifan0127** [strongloop/loopback-next#1408] opened 2018-06-11 01:19 UTC
## Description / Steps to reproduce / Feature proposal
See this example from the documentation: http://loopback.io/doc/en/lb4/Controllers.html#writing-controller-methods

```ts
  @get('/messages')
  async list(@param.query.number('limit') limit = 10): Promise<HelloMessage[]> {
    if (limit > 100) limit = 100; // your logic
    return await this.repository.find({limit}); // a CRUD method from our repository
  }
```

## Current Behavior
The `limit` parameter is always 10, regardless of what value is supplied through query parameter.

## Expected Behavior
Be able to change `limit` via query parameter.

**Comment by raymondfeng** [comment] 2018-06-11 03:31
Please note that `limit` is passed in as a string, for example, `?limit=4` becomes `limit = "4"` at the moment. The type conversion is being implemented by https://github.com/strongloop/loopback-next/pull/1370. The decorator does work though except it's getting `"4"` instead of `4`.

**Comment by raymondfeng** [comment] 2018-06-11 03:31
As a workaround, use `+limit` to convert it to `number` before #1370 is merged and released.

**Comment by lifan0127** [comment] 2018-06-11 03:44
@raymondfeng Thanks for your prompt response! I am still not able to resolve this issue. My real use case does not involve type conversion. For example:

```ts
  @get('/search')
  list(@param.query.string('query') query = 'abc'): string {
    return query
  }
```

It appears in this case, using url parameter `?query=xyz` has no effect and the `query` is always `"abc"`.

My current workaround is not to use default value but do something like `query = query || 'abc'` in the code.

**Comment by raymondfeng** [comment] 2018-06-11 03:57
I tried the following code and it works for me:
```ts
mport {Request, RestBindings} from '@loopback/rest';
import {get, param} from '@loopback/openapi-v3';
import {inject} from '@loopback/context';

/**
 * A simple controller to bounce back http requests
 */
export class PingController {
  constructor(@inject(RestBindings.Http.REQUEST) private req: Request) {}

  // Map to `GET /ping`
  @get('/ping')
  ping(@param.query.number('limit') limit: number = 10): object {
    return {
      greeting: 'Hello from LoopBack',
      date: new Date(),
      url: this.req.url,
      limit: limit,
      headers: Object.assign({}, this.req.headers),
    };
  }
}
```

Please run `lb4 -v` to see what version you have. Or post your package.json here.

**Comment by raymondfeng** [comment] 2018-06-11 03:58
BTW, have you rebuilt the TypeScript code with `npm run build`?

**Comment by lifan0127** [comment] 2018-06-11 04:04
Thanks again. Here is the response when I ran your example:

```json
{
    "greeting": "Hello from LoopBack",
    "date": "2018-06-11T04:01:57.453Z",
    "url": "/ping?limit=20",
    "limit": 10,
    "headers": {
        "content-type": "application/json",
        "cache-control": "no-cache",
        "postman-token": "391a3905-d4bf-4abf-9841-dd4644e90d42",
        "user-agent": "PostmanRuntime/7.1.1",
        "accept": "*/*",
        "host": "localhost:3030",
        "accept-encoding": "gzip, deflate",
        "connection": "keep-alive"
    }
}
```
lb4 -v output:

```json
@loopback/cli version: 0.13.5

@loopback/* dependencies:
  - @loopback/authentication: ^0.10.8
  - @loopback/boot: ^0.10.8
  - @loopback/build: ^0.6.8
  - @loopback/context: ^0.11.5
  - @loopback/core: ^0.8.7
  - @loopback/metadata: ^0.8.7
  - @loopback/openapi-spec-builder: ^0.7.7
  - @loopback/openapi-v3-types: ^0.7.7
  - @loopback/openapi-v3: ^0.10.8
  - @loopback/repository-json-schema: ^0.9.8
  - @loopback/repository: ^0.11.2
  - @loopback/rest: ^0.11.2
  - @loopback/testlab: ^0.10.7
  - @loopback/docs: ^0.9.5
  - @loopback/example-hello-world: ^0.8.3
  - @loopback/example-log-extension: ^0.10.3
  - @loopback/example-rpc-server: ^0.8.3
  - @loopback/example-todo: ^0.11.3
  - @loopback/dist-util: ^0.3.2
  - @loopback/service-proxy-proxy: ^0.4.0
  - @loopback/service-proxy: ^0.5.8
  - @loopback/http-caching-proxy: ^0.2.3
  - @loopback/http-server: ^0.1.2
```

**Comment by raymondfeng** [comment] 2018-06-11 05:15
I'm able to reproduce the problem now. This is a fix: https://github.com/strongloop/loopback-next/pull/1409

**Closed** 2018-06-11 15:13 UTC

**Comment by raymondfeng** [comment] 2018-06-11 15:32
Please upgrade to @loopback/context@0.11.6
