### ISSUE TITLE
Add in a CLI prompt for setting up relations between models

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1554] opened 2018-07-19 21:10 UTC
## Description / Steps to reproduce / Feature proposal

There's no CLI support for relations in LB4 and there's tons to consider.
`lb4 relation` should
- ask prompts that are similarly outlined like the prompts in `lb3`
- establish relations by adding in the appropriate decorators to the models involved
- configure existing repositories to have the appropriate constraining factory functions defined
- add in the controller to expose the routes involving the related models

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment] 2018-07-21 01:48
@shimks , I'd like to close this issue as duplicate of https://github.com/strongloop/loopback-next/issues/1359.  Please continue the discussion over there.  Thanks!

**Closed by dhmlau** 2018-07-21 01:48 UTC
Labels: CLI, developer-experience
