### ISSUE TITLE
HasMany Relationship creates unrequired database column

### ISSUE THREAD

**Issue by pbalan** [strongloop/loopback-next#2194] opened 2018-12-25 09:08 UTC
## Description / Steps to reproduce / Feature proposal

Using MySQL database for persistence.

The minimum reproducible repository is as below: 
https://github.com/pbalan/ipm-gateway

## Current Behavior

The above repository create an extra column projects in Region table.

<img width="1408" alt="screen shot 2018-12-25 at 5 03 39 pm" src="https://user-images.githubusercontent.com/3174988/50418662-9a023380-0867-11e9-8cfe-d4d3eb672d7c.png">

## Expected Behavior

`projects` column should not be created when using HasMany relationship.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by gczobel-f5** [comment] 2018-12-26 11:09
This was already reported here: https://github.com/strongloop/loopback-next/issues/1944
A PR was done and is waiting for approval.

**Comment by bajtos** [comment] 2019-01-10 08:31
Closing as a duplicate of #1944. Thank you @gczobel-f5 for looking up the existing issue!

**Closed by bajtos** 2019-01-10 08:31 UTC
