### ISSUE TITLE
[Getting-Started] loopback.io does not have anything about LBNext

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#623] opened 2017-10-06 20:39 UTC
In loopback.io, there is no content about LBNext.
- Need to show LBNext is here, what's new
- Direct link to how to get started on LBNext - Possibly to this link http://loopback.io/doc/en/lb4/Getting-started.html

/cc @crandmck

**Comment by bajtos** [comment] 2017-10-12 16:37
Closing as a duplicate of #633

**Closed by bajtos** 2017-10-12 16:37 UTC
Labels: developer-experience, LoopBackNext-beta, needs-estimate
