### ISSUE TITLE
CLI prints a bunch of node warnings on Node.js 14.0.0

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#5203] opened 2020-04-23 07:15 UTC
## Steps to reproduce

```sh
$ nvm install 14.0.0.
Downloading and installing node v14.0.0
(...)
Now using node v14.0.0 (npm v6.14.4)

$ npm i -g @loopback/cli
(...)
+ @loopback/cli@2.4.3
added 761 packages from 392 contributors in 78.492s

$ lb4 example todo
```

## Current Behavior

A lot of warnings are printed

```
(node:26892) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26892) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:26892) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

## Expected Behavior

No warnings are printed.

While this bug is specifically describing Node warnings about "Accessing non-existent property", it would be eventually nice to get rid of `request` dependency too.

## Link to reproduction sandbox

n/a

## Additional information

```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 14.0.0
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment] 2020-04-23 16:50
See https://github.com/nodejs/node/pull/29935

It might be related to `shelljs`.

```
npm ls shelljs
loopback-next@0.1.0 /Users/rfeng/Projects/loopback4/loopback-next
└─┬ cz-conventional-changelog@3.1.0
  └─┬ commitizen@4.0.4
    └── shelljs@0.7.6 
```

**Comment by raymondfeng** [comment] 2020-04-23 16:52
Running `NODE_OPTIONS="--trace-warnings" lb4` confirms that `shelljs` is the root cause.

**Comment by raymondfeng** [comment] 2020-04-23 16:53
Duplicate of https://github.com/shelljs/shelljs/issues/991

**Comment by deepakrkris** [comment] 2020-04-23 18:15
there is no immediate action available for this, will have to wait for a new release of shelljs

**Comment by frbuceta** [comment] 2020-04-27 11:11
If you allow me, I will close this issue. With the maintenance of the package-lock's it has been fixed

**Closed by frbuceta** 2020-04-27 11:11 UTC
Labels: 2020Q3, bug
