### ISSUE TITLE
build watch while in development with nodemon

### ISSUE THREAD

**Issue by ringodotnl** [strongloop/loopback-next#2107] opened 2018-12-03 10:13 UTC
## Description / Steps to reproduce / Feature proposal
Trying to get a watch mode with lb4 while developing with:
"start:dev": "concurrently \"npm run build:watch\" \"nodemon .\"",

## Current Behavior
After cmd: npm run start:dev
Updated ts code is not active

## Expected Behavior
Updated ts code should be active

**Comment by bajtos** [comment] 2019-01-25 14:19
Closing as a duplicate of #2242.

**Closed by bajtos** 2019-01-25 14:19 UTC
Labels: Examples, feature
