### ISSUE TITLE
Add support for "include" and "fields" to findById (REST API)

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1721] opened 2018-09-18 08:00 UTC
Let's say our application has a `Customer` model that has many `Order` instances.

In LoopBack 3.x, one can can fetch a customer with all their orders.

```
GET /api/customers/123?filter[include]=orders
```

We should support this feature in LoopBack 4 too.

## Acceptance criteria

 - [ ] Find which `Filter` properties are supported by `findById`
 - [ ] Create a new TypeScript interface describing these properties. This new interface should be most likely provided by loopback-datasource-juggler.
 - [ ] Modify `EntityCrudRepository.prototype.findById` - fix the type of the `filter` argument to use the new TypeScript type describing only the properties supported by `findById`. Fix all implementations of this interface, include tests. 
 - [ ] Create a function for obtaining JSON Schema and OpenAPI schema for this new interface. Build on top of #1679
- [ ] Update [Sequence](https://loopback.io/doc/en/lb4/Sequence.html) that we support these two fields for `findById`.
- [ ] Throw errors ( or warning) when use `order`, `skip`, `limit`, and `where` clauses with `findById`. See https://github.com/strongloop/loopback-next/issues/3336.
--------------------
Done in https://github.com/strongloop/loopback-next/pull/4114
 - Update the REST Controller template and all example controllers to support this new `filter` parameter.
 - Update any documentation pages  and snapshot tests showing `findById` implementation to include the new `filter` argument.

_Note: the argument name `filter` may not be descriptive enough, feel free to find a better name._

**IMPORTANT: This feature depends on https://github.com/strongloop/loopback-next/issues/1352.**

**Comment by mrbatista** [comment] 2018-10-25 10:14
@bajtos is duplicate of #1352?
In loopback 3.x is it possible to use include for `find()`, `findById()`, `findOne()`.
Does loopback 4 support only `findById()`?

**Comment by bajtos** [comment] 2018-10-26 06:19
> In loopback 3.x is it possible to use include for find(), findById(), findOne().
> Does loopback 4 support only findById()?

LoopBack 4 does not support inclusion of related models yet. The issue #1352 is keeping track of making `filter[include]` work for `find` and `findOne` and it's a pre-requisite for this issue.

**Closed** 2020-02-28 16:39 UTC
Labels: Juggler, REST, developer-experience, feature, feature parity, good first issue

**Comment by tayyabjamil** [comment] 2021-02-02 00:00
any updates?
