### ISSUE TITLE
Minor: mocha never finishes because it no longer receives the --exit option

### ISSUE THREAD

**Issue by joeytwiddle** [strongloop/loopback-next#2403] opened 2019-02-15 10:11 UTC
## Description / Steps to reproduce / Feature proposal
1. On a default project, add some annoying code:
    ```sh
    echo "setInterval(() => console.log('nasty loop'), 60000);" \
        >> src/controllers/ping.controller.ts
    ```
2. Run `npm test`

## Current Behavior
After the tests have passed, mocha blocks. The process never ends.

## Expected Behavior
After the tests have passed, mocha should exit back to the command-line.

## Additional

I guess that `--exit` is the desired behaviour, because I see it in `packages/build/config/mocha.opts`.

But it doesn't appear in `generators/project/templates/test/mocha.opts` (if it did then I guess that would close the issue).

The change happened somewhere between version 1.0.0 and 1.0.1 of @loopback/build
```sh
git diff @loopback/build@1.0.0 @loopback/build@1.0.1 packages/build
```
It looks like the new behaviour is to only use the default `mocha.opts` if there is no `test/mocha.opts` in the project.

Whether `--exit` is really desirable is up to you! But I feel the "default fallback" opts should be closer to the "template default".

## Workaround for consumers

When I encountered this problem, I simply added `--exit` to our project's `test/mocha.opts` to fix it.

Another workaround might be to find and destroy whatever is keeping the mocha process alive. You may use [why-is-node-running](https://www.npmjs.com/package/why-is-node-running) to help with that.

## Acceptance criteria

- [ ] Add `"exit": true` to default Mocha options in scaffolded projects - see [`packages/cli/generators/project/templates/.mocharc.json`](https://github.com/strongloop/loopback-next/blob/bd50ef945a10e85f85497ef9a08eead55e99928d/packages/cli/generators/project/templates/.mocharc.json)

---

## 🎆 Hacktoberfest  2020

Greetings :wave: to all Hacktoberfest 2020 participants!

Here are few tips 👀 to make your start easier, see also #6456:

- Before you start working on this issue, please leave a comment to let others know.
- If you are new to GitHub pull requests, then you can learn about the process in [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html).
-  If this is your first contribution to LoopBack, then please take a look at our [Developer guide](https://loopback.io/doc/en/lb4/code-contrib-lb4.html).
- Feel free to ask for help in `#loopback-contributors` channel, you can join our Slack workspace [here](https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw).

**Comment by bajtos** [comment] 2019-02-15 15:48
Thank you @joeytwiddle for reporting the problem! I vaguely remember that some of LB connectors may be keeping the process running because of the connection pool they use in background (and don't `unref` it as they should). 

I think it will be best to add `--exit` to the mocha opts file template we use for new projects. Would you like to contribute this change?

@strongloop/loopback-maintainers any objections or other proposals?

**Comment by simlt** [comment] 2020-09-30 21:56
Hi, I am currently having a similar problem on a loopback project when using the mssql connector, so I wanted to contribute. I can confirm that enabling the exit option for mocha solved the problem.

I'm leaving a comment just to let others know that II want to take care of this issue.

**Comment by dhmlau** [comment] 2020-09-30 23:30
Thanks @simlt. Let me assign it to you.

**Comment by bajtos** [comment] 2020-10-02 07:13
closing as done via #6475

**Closed by bajtos** 2020-10-02 07:13 UTC
Labels: Hacktoberfest, developer-experience, good first issue
