### ISSUE TITLE
@hasMany property inconsistent with database

### ISSUE THREAD

**Issue by gruseski** [strongloop/loopback-next#2203] opened 2018-12-31 00:34 UTC
## Description / Steps to reproduce / Feature proposal

- Run the "todo-list" example found in https://github.com/strongloop/loopback-next/tree/master/examples/todo-list with 'npm start'

- In API explorer, send a POST request to the TodoListTodoController with the ID set to 2 and body:

```
{
  "id": 29,
  "title": "POTUS task",
  "desc": "some desc",
  "isComplete": true
}

```

**Notice that you need to remove the "todoListId": 0 line present in the body by default**. I'm not sure if this is expected behavior or not.

- Send a GET request to the TodoListController

## Current Behavior
The "todos" property in TodoList is always empty or null

## Expected Behavior
**If I'm not mistaken** the list should be populated with all todos belonging to that TodoList according to the database, including the newly added task

**Comment by dhmlau** [comment] 2019-01-18 14:35
@b-admike , could you please take a look? Thanks.

**Comment by b-admike** [comment] 2019-04-16 15:01
Hi, this is to be implemented as part of https://github.com/strongloop/loopback-next/issues/1352 AFAICT.

**Comment by b-admike** [comment] 2019-04-16 15:04
Closing as duplicate of #1352, feel free to re-open if needed.

**Closed by b-admike** 2019-04-16 15:04 UTC
Labels: 2019Q2, Relations, developer-experience, feature
