### ISSUE TITLE
apidocs needs more descriptions 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#694] opened 2017-11-01 20:56 UTC
In the apidocs, there are broken links (e.g. Array, ProviderMap) and missing descriptions in the arguments,

Example: https://apidocs.strongloop.com/@loopback%2fcore/#Application

## Acceptance Criteria
Go through each @loopback packages to fill in the missing descriptions and fix broken links

- [ ] core
- [ ] context
- [ ] authentication
- [ ] repository
- [ ] rest
- [ ] openapi-spec
- [ ] openapi-spec-builder

cc @crandmck @bschrammIBM

**Comment by bajtos** [comment] 2017-12-15 15:32
Closing as a duplicate of https://github.com/strongloop/loopback-next/issues/577

**Closed by bajtos** 2017-12-15 15:32 UTC
Labels: Core-GA, Docs, help wanted, non-MVP
