### ISSUE TITLE
rest: Support HTTPS and pre-instantiated HTTP/S instances

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#678] opened 2017-10-25 21:08 UTC
## Overview

Developers obviously want to use https with their applications (and well they should!). Currently, the alpha implementation of `@loopback/rest` has no support whatsoever for this concept!

## Acceptance Criteria
- [ ] Add configuration support in `RestComponent`/`RestServer` for provision of:
  - [ ] Certificates/key materials
  - [ ] https configuration options (`rejectUnauthorized`, `requestCert`, etc...)
- [ ] Add configuration support to accept an existing http, https or https/2 server instance.

**Comment by bajtos** [comment] 2017-12-15 14:58
Labelled as non-MVP - users can get HTTPS support by puting an Nginx instance in front of their LoopBack app, or use a sidecar like Envoy when running a microservice-based architecture like http://istio.io/

**Comment by dhmlau** [comment] 2018-03-11 04:17
Talked to @raymondfeng , it might be solved through #1082

**Comment by dhmlau** [comment] 2018-03-27 17:00
Closing as duplicate of https://github.com/strongloop/loopback-next/issues/430

**Closed by dhmlau** 2018-03-27 17:00 UTC
Labels: Core-GA, needs-priority, non-DP3, team-apex
