### ISSUE TITLE
[Spike] Investigate how to allow complex object in filter object in API Explorer

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3770] opened 2019-09-19 15:44 UTC
Originated from https://github.com/strongloop/loopback-next/issues/2208.

## Description
swagger-ui, the library powering our API Explorer, unfortunately does not support complex objects in query strings. This spike is to investigate if/how we can allow it. 

_Extracting from https://github.com/strongloop/loopback-next/issues/2208#issuecomment-533008671 from @bajtos_ 

Based on OAI/OpenAPI-Specification#1706 (comment) (cross-posted below), maybe we can switch filter encoding from deepObject style into JSON?

Here is an experiment we can try:

1. Let's keep @param.query.object with no changes for backwards compatibility.
2. Introduce a new helper @param.query.jsonObject that will use JSON encoding instead of deepObject style.
3. Modify the function parseJsonIfNeeded to detect JSON encoding and parse the string value - see packages/rest/src/coercion/coerce-parameter.ts
4. Update our example Todo controller to use @param.query.jsonObject - see examples/todo/src/controllers/todo.controller.ts
5. Start the Todo app, open API Explorer and check how is the filter parameter handled. 

## Acceptance Criteria
<del>- [ ] Review the workaround posted by various users in https://github.com/strongloop/loopback-next/issues/2208 </del>
- [x] Try out the experiment from @bajtos (listed above)

**Comment by bajtos** [comment] 2019-09-20 08:33
An important aspect to consider: if we switch the spec of `format` argument from deepObject-style to json-content, how is it going to affect the actual REST API? Will it mean that clients will be no longer able to send queries like `find?filter[limit]=1` and will have to always use JSON encoding only (`find?filter={"limit":1}`)?

**Comment by deepakrkris** [comment] 2019-09-23 22:51
For having the "include" parameter in filter condition `filter["include"]=` does not work whereas passing filter as deep object works.
example:
`http://localhost:3000/todos/1?filter=%7B%22include%22%3A%5B%7B%22relation%22%3A%22todoList%22%7D%5D%7D`

**Comment by deepakrkris** [comment] 2019-09-23 22:54
url encoding of json can be done with javascript built in function `encodeURIComponent(stringified-json)`

**Comment by deepakrkris** [comment] 2019-11-18 04:12
In the open api spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#encoding-object) , explanation for explode setting is, 
```
When this is true, property values of type array or object generate separate parameters for each value of the array, or key-value-pair of the map. For other types of properties this property has no effect.
```
explode setting has no effect on complex json objects

**Comment by deepakrkris** [comment] 2019-11-18 04:15
spike https://github.com/strongloop/loopback-next/pull/4141 tries to test passing complex object as uri encoded values in query params

**Comment by deepakrkris** [comment] 2019-11-18 07:06
@bajtos looks like your proposal https://github.com/OAI/OpenAPI-Specification/issues/1706#issuecomment-522474407 has not got much consensus. We are left with style: deepObject for now. so I have used the explode setting to check if url encoding is required in the above spike.

**Comment by deepakrkris** [comment] 2019-11-18 23:41
@dhmlau I am changing the original problem description in the issue. I think Miroslav's suggestion was given in a different context. It has nothing to do with the API Explorer not handling json objects in query params.

**Comment by deepakrkris** [comment] 2019-11-19 05:36
@bajtos the spike https://github.com/strongloop/loopback-next/issues/3770 works perfectly fine, API explorer supports url encoding of complex object in query params when implementing steps suggested by you.

**Comment by deepakrkris** [comment] 2019-11-19 05:39
<img width="1076" alt="Screen Shot 2019-11-18 at 9 39 21 PM" src="https://user-images.githubusercontent.com/7688315/69119579-efc96680-0a4b-11ea-8e9f-c8fab73b0c88.png">

**Comment by bajtos** [comment] 2019-11-21 10:28
I though I have posted a comment, but it looks it got lost :(

> An important aspect to consider: if we switch the spec of `format` argument from deepObject-style to json-content, how is it going to affect the actual REST API? Will it mean that clients will be no longer able to send queries like `find?filter[limit]=1` and will have to always use JSON encoding only (`find?filter={"limit":1}`)? Can we find a way how to preserve support for both flavors?

**Comment by bajtos** [comment] 2019-11-21 10:29
> I though I have posted a comment, but it looks it got lost :(

Ah, never mind, the discussion is happening here:
https://github.com/strongloop/loopback-next/pull/4141#discussion_r347766228

Please ignore my comment above and continue the discussion in the pull request.

**Comment by deepakrkris** [comment] 2019-11-27 04:01
findings of spike:
 - this is a breaking fix, needs semver major release
 - change existing param.query.object decorator to support json objects in query params
 - including `content` field in param spec, helps to support both exploded filter conditions like filter[limit] = 0 and json objects
 - parameter schema cannot have content field along with schema, explode, type fields. swagger validation fails (check with https://editor.swagger.io/) if they appear together.
 - loopback currently does not support extracting parameter schema from the content field. if we are including schema under content and not schema field, then it means additional changes in tests and source.
 - add additional unit, acceptance and regression tests

**Comment by deepakrkris** [comment] 2019-11-27 19:05
All the suggestions are implemented and tested in the Spike PR, so I am closing this issue. findings of this spike are updated here as well as the linked original issue https://github.com/strongloop/loopback-next/issues/2208.

**Closed by deepakrkris** 2019-11-27 19:05 UTC
Labels: 2019Q4, developer-experience, spike
