### ISSUE TITLE
Loopback4  - how to use one endpoint for putting all relational data. 

### ISSUE THREAD

**Issue by lakinmohapatra** [strongloop/loopback-next#3663] opened 2019-08-30 09:52 UTC
Loopback4  - how to use one endpoint for putting all relational data. 

Ex ; 
I have an address table and user table. 
I want to post all user data and address data to only one endpoint and store data . 
BY DEFAULT, using relation generator, it creates 2 different controllers one for user and another for address. 

Please advise.

**Comment by dhmlau** [comment] 2019-09-04 15:43
@lakinmohapatra, this is related to the "inclusion of related models" epic https://github.com/strongloop/loopback-next/issues/1352.  We've actively working to support this feature.  

I'd like to continue any discussion to that epic and close this ticket as duplicate. Thanks! 

Closing as duplicate of https://github.com/strongloop/loopback-next/issues/1352.

**Closed by dhmlau** 2019-09-04 15:43 UTC
