### ISSUE TITLE
Filter in query of type object treated as string

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#394] opened 2017-06-24 01:02 UTC
# Description/Steps to reproduce
Define a parameter for a route which has type `object`
```
  paths: {
    '/accounts': {
      get: {
        'x-operation-name': 'getAccount',
        parameters: [
          {
            name: 'filter',
            in: 'query',
            description: 'The criteria used to narrow down the number of accounts returned.',
            required: false,
            type: 'object'
          }
```
method in controller:
```
  async getAccount(filter) {
    return await this.repository.find(filter);
  }
```
# Expected result

The parameter `filter` should be of type `object` if we check it in the controller method for the route.

# Additional information
```
___________________    | ~/routertestapp @ biniams-mbp (badmike)
| => node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 8.0.0
___________________    | ~/routertestapp @ biniams-mbp (badmike)
| => npm ls --prod --depth 0 | grep loopback
└── @loopback/core@4.0.0-alpha.9
```

**Comment by bajtos** [comment] 2017-07-13 12:48
Note that in SwaggerSpec 2.x (which LoopBack Next is based on so far), query parameters can have only primitive type (string, number, etc.), see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject 

However, for LB 3.x backwards compatibility, I have proposed to support complex types in query strings, see #100.

I've been told that OpenAPI Spec 3.0 will support complex objects in query parameters. In which case we need to upgrade LB.next to OpenAPI Spec 3.0 first, see #182.

**Comment by dhmlau** [comment] 2018-03-27 16:21
Closing as duplicate of #100

**Closed by dhmlau** 2018-03-27 16:21 UTC
Labels: Core-GA, feature, needs-priority, non-DP3, p2
