### ISSUE TITLE
@loopback/context uuid error

### ISSUE THREAD

**Issue by alexnfsc175** [strongloop/loopback-next#5496] opened 2020-05-19 23:01 UTC
## Steps to reproduce

In the last version of the loopback, @ loopback / cli version: 2.7.0, when running npm run start, I get an error related to uuid

```bash
@loopback/cli version: 2.7.0

@loopback/* dependencies:
  - @loopback/authentication: ^4.2.4
  - @loopback/boot: ^2.3.0
  - @loopback/build: ^5.4.0
  - @loopback/context: ^3.8.0
  - @loopback/core: ^2.6.0
  - @loopback/metadata: ^2.1.4
  - @loopback/openapi-spec-builder: ^2.1.4
  - @loopback/openapi-v3: ^3.4.0
  - @loopback/repository-json-schema: ^2.4.1
  - @loopback/repository: ^2.5.0
  - @loopback/rest: ^5.0.0
  - @loopback/testlab: ^3.1.4
  - @loopback/docs: ^3.8.0
  - @loopback/example-hello-world: ^2.1.0
  - @loopback/example-log-extension: ^2.1.0
  - @loopback/example-rpc-server: ^2.1.0
  - @loopback/example-todo: ^3.4.0
  - @loopback/example-soap-calculator: ^2.2.0
  - @loopback/service-proxy: ^2.2.1
  - @loopback/http-caching-proxy: ^2.1.4
  - @loopback/http-server: ^2.1.4
  - @loopback/example-todo-list: ^3.2.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^2.2.1
  - @loopback/eslint-config: ^7.0.0
  - @loopback/example-express-composition: ^2.2.0
  - @loopback/example-greeter-extension: ^2.1.0
  - @loopback/booter-lb3app: ^2.2.0
  - @loopback/example-lb3-application: ^2.1.0
  - @loopback/example-greeting-app: ^2.1.0
  - @loopback/example-context: ^2.1.0
  - @loopback/repository-tests: ^0.12.4
  - @loopback/extension-health: ^0.4.4
  - @loopback/authorization: ^0.5.9
  - @loopback/rest-crud: ^0.8.4
  - @loopback/security: ^0.2.9
  - @loopback/authentication-passport: ^2.1.4
  - @loopback/example-metrics-prometheus: ^0.3.0
  - @loopback/extension-metrics: ^0.3.4
  - @loopback/model-api-builder: ^2.1.4
  - @loopback/extension-logging: ^0.3.4
  - @loopback/example-access-control-migration: ^1.3.0
  - @loopback/example-file-transfer: ^1.3.0
  - @loopback/example-rest-crud: ^1.3.0
  - @loopback/apiconnect: ^0.3.2
  - @loopback/example-validation-app: ^1.4.0
  - @loopback/cron: ^0.2.4
  - @loopback/example-multi-tenancy: ^0.3.0
  - @loopback/example-passport-login: ^1.4.0
  - @loopback/authentication-jwt: ^0.3.0
  - @loopback/context-explorer: ^0.1.4
  - @loopback/express: ^1.2.0
```
The error: 
```bash
npm start

> teste-app@1.0.0 prestart C:\Users\Convex\Documents\dev\Alex\teste-app
> npm run build


> teste-app@1.0.0 build C:\Users\Convex\Documents\dev\Alex\teste-app
> lb-tsc


> teste-app@1.0.0 start C:\Users\Convex\Documents\dev\Alex\teste-app
> node -r source-map-support/register .

Error: No valid exports main found for 'C:\Users\Convex\Documents\dev\Alex\teste-app\node_modules\uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Convex\Documents\dev\Alex\teste-app\node_modules\@loopback\context\src\value-promise.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! teste-app@1.0.0 start: `node -r source-map-support/register .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the teste-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Convex\AppData\Roaming\npm-cache\_logs\2020-05-19T22_28_29_162Z-debug.log
```
in this test I get the same error
```bash
node
Welcome to Node.js v13.3.0.       
Type ".help" for more information.
> const uuid = require('@loopback/context').uuid
Thrown:
Error: No valid exports main found for 'C:\Users\Convex\Documents\dev\Alex\teste-app\node_modules\uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  - @loopback/cron: ^0.2.4
  - @loopback/example-multi-tenancy: ^0.3.0
  - @loopback/example-passport-login: ^1.4.0
  - @loopback/authentication-jwt: ^0.3.0
  - @loopback/context-explorer: ^0.1.4
  - @loopback/express: ^1.2.0
```
Node version:
```bash
$ node -v
v13.3.0
```

**Comment by raymondfeng** [comment] 2020-05-19 23:30
@alexnfsc175 Please don't use node 13.3.0. It includes a bug for `import`. 

This issue is duplicate of https://github.com/strongloop/loopback-next/issues/5381

**Closed by raymondfeng** 2020-05-19 23:30 UTC
Labels: bug

**Comment by alexnfsc175** [comment] 2020-05-20 00:01
@raymondfeng Thanks for your help
