### ISSUE TITLE
CLI command is dead

### ISSUE THREAD

**Issue by changchengchang** [strongloop/loopback-next#2569] opened 2019-03-11 09:44 UTC
## Description / Steps to reproduce / Feature proposal
In my Windows 10, Nodejs 11 and @loopback/cli 1.8.1 are installed. 

## Current Behavior
When running any lb4 command, it stopped. There is no error. I tried different version of nodejs and loopback cli. It is the same. Other cli works (e.g. lb3 cli)

## Expected Behavior
The command works

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment] 2019-03-14 02:41
@changchengchang, I just tried with the following configurations on my Windows 10 machine and it seems to be working fine:
- Node.js 11.6.0
- `@loopback/cli` - 1.8.1 or 1.8.2 (latest)

I'm using `nvm` to switch.
Perhaps you can try to reinstall `@loopback/cli`?

**Comment by dhmlau** [comment] 2019-03-19 02:12
@changchengchang, are you still encountering this problem?

**Comment by changchengchang** [comment] 2019-03-19 02:22
Yes. I tried different version of nodejs and lb4. The same problem occurred.

**Comment by ceefour** [comment] 2019-09-18 13:41
Related to #3187.

In my computer, I can reproduce using specific conditions (see below).

Windows 10 1903, Node.js v10.16.3, npm v6.11.3, `lb4`:

``
@loopback/cli version: 1.22.1

@loopback/* dependencies:
  - @loopback/authentication: ^3.0.1
  - @loopback/boot: ^1.5.6
  - @loopback/build: ^2.0.11
  - @loopback/context: ^1.23.0
  - @loopback/core: ^1.10.2
  - @loopback/metadata: ^1.3.2
  - @loopback/openapi-spec-builder: ^1.2.13
  - @loopback/openapi-v3: ^1.9.7
  - @loopback/repository-json-schema: ^1.10.0
  - @loopback/repository: ^1.14.0
  - @loopback/rest: ^1.19.0
  - @loopback/testlab: ^1.8.1
  - @loopback/docs: ^2.1.0
  - @loopback/example-hello-world: ^1.2.14
  - @loopback/example-log-extension: ^1.2.14
  - @loopback/example-rpc-server: ^1.2.14
  - @loopback/example-todo: ^1.8.0
  - @loopback/example-soap-calculator: ^1.6.15
  - @loopback/service-proxy: ^1.3.6
  - @loopback/http-caching-proxy: ^1.1.13
  - @loopback/http-server: ^1.4.13
  - @loopback/example-todo-list: ^1.10.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.3.7
  - @loopback/eslint-config: ^4.1.0
  - @loopback/example-express-composition: ^1.6.0
  - @loopback/example-greeter-extension: ^1.3.14
  - @loopback/booter-lb3app: ^1.3.0
  - @loopback/example-lb3-application: ^1.1.14
  - @loopback/example-greeting-app: ^1.2.0
  - @loopback/example-context: ^1.2.14
  - @loopback/repository-tests: ^0.4.5
  - @loopback/extension-health: ^0.2.6
  - @loopback/authorization: ^0.3.0
  - @loopback/rest-crud: ^0.3.0
  - @loopback/security: ^0.1.2
```

These work:

```
D:\project_amanah\S3\quakezone\quakezone-lb>lb4 datasource
? Datasource name:

D:\project_amanah\S3\quakezone\quakezone-lb>lb4 datasource
? Datasource name: thisisworking
? Select the connector for thisisworking: (Use arrow keys)
> In-memory db (supported by StrongLoop)
  In-memory key-value connector (supported by StrongLoop)
  IBM Object Storage (supported by StrongLoop)
  IBM DB2 (supported by StrongLoop)
  IBM DashDB (supported by StrongLoop)
  IBM MQ Light (supported by StrongLoop)
  IBM Cloudant DB (supported by StrongLoop)
(Move up and down to reveal more choices)
```

But the following **does not work**:

```
D:\project_amanah\S3\quakezone\quakezone-lb>lb4 datasource notworkingDS
(HANGS FOREVER)
```

Proof:

![image](https://user-images.githubusercontent.com/24123/65153814-9c8b6580-da54-11e9-886b-d51e4f547de0.png)

**Comment by dhmlau** [comment] 2019-09-18 14:25
@changchengchang @ceefour, one more question.. Are you using `nvm` to manage the node version you're using?  I have a Windows machine at home and using `nvm`, it generally works fine. You might want to give it a try.

@ceefour, for your particular issue, I just tried it on mac and there's no hanging. Let me try to reproduce on a Windows machine tonight.

**Comment by ceefour** [comment] 2019-09-18 14:49
@dhmlau I don't use nvm. it's the standard official installer.

I'd love to share info with debug flags, verbose, more diagnosis, etc. if you tell me how to enable that.

**Comment by ceefour** [comment] 2019-09-18 14:53
@dhmlau also, spawning 'lb4 anything' from a node app (as child process) in Windows will make it stuck immediately (even with --yes). it's not exactly this issue but it is related.

by comparison, other scripts like npm install etc. I can run using node's spawn without issue.

**Comment by bajtos** [comment] 2019-10-15 15:50
FWIW, CLI tests are hanging in AppVeyor (Windows) when using Node.js versions newer than 10.0.0. Related discussions:
- https://github.com/strongloop/loopback-next/pull/1350#issuecomment-394679150
- https://github.com/nodejs/node/issues/21210

It makes me wonder - if you downgrade your Node.js version to 8, will it fix the problem?

**Comment by dougal83** [comment] 2020-03-22 12:58
It seems that this was an ephemeral issue so closing as cannot replicate.

**Closed by dougal83** 2020-03-22 12:58 UTC
Labels: CLI, os:Windows

**Comment by emonddr** [comment] 2020-03-23 15:36
I had to look up `ephemeral` in a dictionary. lol. ;)
