### ISSUE TITLE
Clean up extension template and docs

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#5336] opened 2020-05-05 14:04 UTC
_This is a follow-up for #5337 and #5122_

The documentation for component authors (e.g. [Creating components](https://loopback.io/doc/en/lb4/Creating-components.html)) and the template used by `lb4 extension` are outdated. We learned a lot since those artifacts were written and introduced new conventions and features, e.g. `@config` decorator. It's time to modernize both the CLI template and the docs to the latest and greatest.

### CLI templates

Update the template used by [`lb4 extension`](https://github.com/strongloop/loopback-next/tree/master/packages/cli/generators/extension) to follow the current style as seen e.g. in [`extensions/metrics`](https://github.com/strongloop/loopback-next/blob/master/extensions/metrics)

- [x] inject the target app and component config to the component class
- [x] add a new file `src/keys.ts` exporting `{ComponentName}Keys.COMPONENT` binding key
- [x] decorate the component class with `@bind()`,
- [x] include generic Basic Use instructions in the scaffolded README file

_Nice to have:_

- [ ] use the component name in the file names to disambiguate them from similar files in other extensions, e.g. `src/{name}.keys.ts` and `src/{name}.component.ts`

### Docs

Revisit the documentation, make it consistent with the current style for writing extensions and the CLI template.

- [x] [Creating components](https://loopback.io/doc/en/lb4/Creating-components.html)
  - Rework "Configuring components" at the end to explain how to receive and provide component config via `@config` and
`this.configure()` API
  - Review the content - are the advices and code snippets still current and consistent with recommendations we are giving elsewhere? Are we missing any major information? (It's probably best to open follow-up stories to make non-trivial docs updates.)
- [x] [Extending LoopBack 4](https://loopback.io/doc/en/lb4/Extending-LoopBack-4.html),
  - "Learn from existing ones" - can we add more of our existing components to the list?
  - Review the content - are the advices and code snippets still current and consistent with recommendations we are giving elsewhere? Are we missing any major information? (It's probably best to open follow-up stories to make non-trivial docs updates.)
- [x] [Using components](https://loopback.io/doc/en/lb4/Using-components.html) 
  - Update the list of components to include all extensions developed in loopback-next monorepo (look for components both in [`extensions`](https://github.com/strongloop/loopback-next/tree/master/extensions) and [`packages`](https://github.com/strongloop/loopback-next/tree/master/packages))
- [x] [Components](https://loopback.io/doc/en/lb4/Components.html)

_Nice to have:_

- [ ] Review the content in the pages above and in the component migration guide (https://loopback.io/doc/en/lb4/migration-extensions.html and sub-pages). Some content may be duplicated (sometimes inconsistently), some content may belong to a different place. Decide what to do (if anything) and either make the changes right away or create follow-up issues.

**Comment by hacksparrow** [comment] 2020-08-17 13:52
@bajtos `lb4 extension` is creating the extension dir in the project root. Is it by design? Can we change it? Shouldn't extensions be kept in a `extensions` dir?

**Comment by hacksparrow** [comment] 2020-08-17 14:44
Also, why call it "Extension" when we are creating a Component? Can we name the command `lb4 component` instead? Breaking change, but it leaves no room for confusion.

**Comment by raymondfeng** [comment] 2020-08-17 14:57
> lb4 extension is creating the extension dir in the project root. Is it by design? Can we change it? Shouldn't extensions be kept in a extensions dir?

`lb4 extension` should just create a new project as an extension package for LoopBack 4. It should not be used inside an existing LB app. For `loopback-next`, use `https://github.com/strongloop/loopback-next/blob/master/bin/create-package.js`.

**Comment by raymondfeng** [comment] 2020-08-17 14:57
> Also, why call it "Extension" when we are creating a Component? Can we name the command lb4 component instead? Breaking change, but it leaves no room for confusion.

I would like to reserve `lb4 component` to add a component to an existing application.

**Comment by bajtos** [comment] 2020-08-17 15:00
> @bajtos `lb4 extension` is creating the extension dir in the project root. Is it by design? Can we change it? Shouldn't extensions be kept in a `extensions` dir?

I have no idea, TBH. I believe this behavior was introduced by @raymondfeng, please check with him. Also, have you checked the discussion in the pull request introducing `lb4 extension` command? The answer may lay there.

> Also, why call it "Extension" when we are creating a Component? Can we name the command `lb4 component` instead? Breaking change, but it leaves no room for confusion.

In my view, the term "component" includes both built-in components (e.g. context & TS decorator metadata) and add-on components/extensions (e.g. `@loopback/metrics`).

On the other hand, "extension" is for things that are outside of the "core" framework. In loopback-next, we have a top-level directory `extensions` too.

If you want to unify our vocabulary and use a single term (which I think is a great idea!), then IMO we should use "extension", not "component".

_IIRC, we started to use the term "component" early in LB4 development. Later we pivoted to use "extension", but we did not propagate that change to existing docs._

**Comment by hacksparrow** [comment] 2020-08-31 13:44
Created this follow up task - https://github.com/strongloop/loopback-next/issues/6232.

**Comment by hacksparrow** [comment] 2020-08-31 15:59
Closed via https://github.com/strongloop/loopback-next/pull/6158.

**Closed by hacksparrow** 2020-08-31 15:59 UTC
Labels: 2020Q3, CLI, Docs, Extensions, feature, tech-debt
