### ISSUE TITLE
HasOne not showing in relation generator loopback

### ISSUE THREAD

**Issue by lakinmohapatra** [strongloop/loopback-next#3677] opened 2019-09-06 09:06 UTC
Has one not showing in LB4 relationship CLI. 
![Uploading Screen Shot 2019-09-06 at 2.35.31 PM.png…]()

Please look into it.

**Comment by dhmlau** [comment] 2019-09-06 13:58
@lakinmohapatra, thanks for reporting this issue. We have an existing issue covering this: https://github.com/strongloop/loopback-next/issues/2980.  Would you be interested in submitting a PR?  Thanks! 

Closing as duplicate of https://github.com/strongloop/loopback-next/issues/2980.

**Closed by dhmlau** 2019-09-06 13:58 UTC
Labels: bug
