### ISSUE TITLE
auto validation request param base on param class or using decorator

### ISSUE THREAD

**Issue by hbakhtiyor** [strongloop/loopback-next#1346] opened 2018-05-21 08:18 UTC
## Description / Steps to reproduce / Feature proposal
similar [routing-controllers approach](https://www.npmjs.com/package/routing-controllers#auto-validating-action-params)

e.g. we already set validation on `Todo` class, and using the validation, instead of writing inside action.

```js
    if (!todo.title) {
      throw new HttpErrors.BadRequest('title is required');
    }
```
base on todo-list tutorial
```js
  @post('/todo')
  async createTodo(@requestBody() todo: Todo) {
    if (!todo.title) {
      throw new HttpErrors.BadRequest('title is required');
    }
    return await this.todoRepo.create(todo);
  }
```
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment] 2018-06-05 07:53
Closing as a duplicate of #118

**Closed by bajtos** 2018-06-05 07:53 UTC
