### ISSUE TITLE
Improve loopback4 authorization docs of using the component

### ISSUE THREAD

**Issue by kanusoni** [strongloop/loopback-next#5441] opened 2020-05-15 09:33 UTC
Hello ,
can you please provide separate demo tutorial for integration of authorization component with loopback4 API.
Whatever written in loopback.io tutorial is bit confusing.....needs more clarification on this. 
Thanks.

## Acceptance Criteria

- [ ]  link to [access control migration example](https://github.com/strongloop/loopback-next/tree/master/examples/access-control-migration) is missing in [authorization docs page](https://loopback.io/doc/en/lb4/Loopback-component-authorization.html)
- [ ]  need to add a few steps on how authorization is used in this example
- [ ]  need to add a few tutorial steps (like instructing user to add access control to a controller method and check how the example responds) either in [authorization docs page](https://loopback.io/doc/en/lb4/Loopback-component-authorization.html) or in the example read-me. 

Out of scope
- [ ] create an authorization example if needed

**Comment by kanusoni** [comment] 2020-05-15 09:36
Hello ,
can you please provide separate demo tutorial for integration of authorization component with loopback4 API.
Whatever written in loopback.io tutorial is bit confusing.....needs more clarification on this. 
Thanks.

**Comment by jannyHou** [comment] 2020-05-19 18:09
@kanusoni We have a tutorial for the access control example in https://loopback.io/doc/en/lb4/migration-auth-access-control-example.html

**Comment by dhmlau** [comment] 2020-05-25 15:34
@jannyHou, is it a duplicate of #5294?

**Comment by jannyHou** [comment] 2020-05-28 17:43
@dhmlau Let's track authentication and authorization separately, https://github.com/strongloop/loopback-next/issues/5294 is for authentication.

**Comment by jannyHou** [comment] 2020-07-23 16:35
Thank you @kanusoni , based on the discussion, here is a proposal for adding a new example for authorization and re-structuring the doc:

- Create an authorization overview page (current overview + design section + chain of responsibilities)
- Create a simpler RBAC authorization example
       - scenario: Users are associated with different roles, each role has different access to endpoints, use oauth0 to resolve the role mapping
      - use todo example
      - mount the authorization component
      - specify access control rules for endpoints like `@authorize({allowedRoles: [‘admin’]})`
      - create a global authorizer to determine the access, use oauth0 service as enforcer
      - create a local voter to define a calculation rule for an endpoint
      - docs of steps
- Create a page for components (The rest of current docs)

**Comment by jannyHou** [comment] 2020-08-28 21:26
Done in #6195. Thanks for all suggestions!

**Closed by jannyHou** 2020-08-28 21:26 UTC
Labels: 2020Q3, Authorization, Docs
