### ISSUE TITLE
[GSSC-GVT]English String when input command apic lb4 app -h

### ISSUE THREAD

**Issue by wxuwh** [strongloop/loopback-next#5654] opened 2020-06-04 03:21 UTC
27.030.010 APIC apic lb4 app -h (Apr)

Steps & Verification Points:
input ./apic lb4 app -h 
and click Enter
Verify the strings in red circle.

Actual Result:
![image](https://user-images.githubusercontent.com/45190559/83711366-94f90480-a655-11ea-8877-83f94f518f07.png)

## Acceptance Criteria 
- [ ] Investigate if we can externalize the highlighted string 
- [ ] If possible, externalize it

**Comment by agnes512** [comment] 2020-07-08 17:23
![image](https://user-images.githubusercontent.com/50331796/86950342-0e38bb00-c11e-11ea-9e1e-9c647f3d4946.png)

It seems to be translated correctly. I am not able to reproduce the issue.

**Comment by dhmlau** [comment] 2020-07-08 20:24
Thanks for checking @agnes512. I saw that phrase was recently added to the messages.json.

**Comment by dhmlau** [comment] 2020-07-08 20:25
Closing as done.

**Comment by candytangnb** [comment] 2020-08-13 07:26
@agnes512 in the screen you provided there is another English string.
<img width="964" alt="image" src="https://user-images.githubusercontent.com/26452457/90105863-2cc34f00-dd79-11ea-9e85-ed0c33804e3b.png">


I update my loopback/cli to 2.12.0 and still in English
<img width="748" alt="image" src="https://user-images.githubusercontent.com/26452457/90105928-45cc0000-dd79-11ea-9315-81dd7dcf92fe.png">

**Comment by agnes512** [comment] 2020-08-13 13:12
You're right, I didn’t notice the `--ask-answered` is in English. I only checked `packageManager`. Let me reopened the issue

**Comment by agnes512** [comment] 2020-08-13 14:20
Checked, I think `--ask--answered` is translated 
![截圖 2020-08-13 上午9 54 30](https://user-images.githubusercontent.com/50331796/90146050-99752400-dd4e-11ea-87b6-cf490154680d.png)

**Closed** 2020-08-17 13:00 UTC
Labels: 2020Q3, GVT, bug

**Comment by candytangnb** [comment] 2020-08-24 07:24
works well on loopback@cli 2.13.0
<img width="799" alt="image" src="https://user-images.githubusercontent.com/26452457/91015553-e3e38400-e61d-11ea-8c9c-391b7459976d.png">
