### ISSUE TITLE
Unable to execute multiple include query in loopback

### ISSUE THREAD

**Issue by pavanchandanam** [strongloop/loopback-next#3476] opened 2019-07-31 05:52 UTC
let marketingprograms: any = await this.marketingProgramRepository.find({
      include: {
        relation: 'Brand', // include the brand model
        scope: { // further filter the owner object
          fields: ['brandName'], // only show one field
          include: { 
            relation: 'Country',
            scope: {
              fields: ['countryId'],
            scope: {
              where: { MktngPgmId: marketingProgramId } 
            }
          }
        }
      }
      }
    });

it is showing the error on the first include line as

Argument of type '{ include: { relation: string; scope: { fields: string[]; include: { relation: string; scope: { fields: string[]; scope: { where: { MktngPgmId: any; }; }; }; }; }; }; }' is not assignable to parameter of type 'Filter<MarketingProgram>'.
  Types of property 'include' are incompatible.
    Type '{ relation: string; scope: { fields: string[]; include: { relation: string; scope: { fields: string[]; scope: { where: { MktngPgmId: any; }; }; }; }; }; }' is not assignable to type 'Inclusion<MarketingProgram>[]'.
      Object literal may only specify known properties, and 'relation' does not exist in type 'Inclusion<MarketingProgram>[]'.

**Comment by dhmlau** [comment] 2019-07-31 20:49
@jannyHou, could you please take a look? Thanks.

**Comment by jannyHou** [comment] 2019-08-01 13:06
@pavanchandanam The inclusion feature is not supported yet, we are working on retrieving navigational properties incrementally, see epic https://github.com/strongloop/loopback-next/issues/1352.

The proposal and implementation stories are explained in https://github.com/strongloop/loopback-next/pull/3387

**Comment by dhmlau** [comment] 2019-08-13 13:24
@jannyHou, should we close this as duplicate of #1352?

**Comment by jannyHou** [comment] 2019-08-14 15:24
Yeah point it to #1352 is reasonable to me. 
Feel free to reopen the issue if you have more questions.

**Closed by jannyHou** 2019-08-14 15:24 UTC
Labels: bug
