### ISSUE TITLE
Can not inject for patch with authentication

### ISSUE THREAD

**Issue by lygstate** [strongloop/loopback-next#2362] opened 2019-02-10 15:25 UTC
## Description / Steps to reproduce / Feature proposal
```
  @authenticate('jwt')
  async patchOrders(
    @inject('authentication.currentUser') currentUser: UserProfile,
```
## Current Behavior
```
Unhandled error in PATCH /users/5c6042010d00a411724b47a0/orders: 500 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.constrainDataObject (/mnt/e/CI-Cor-Ready/meifu/loopback4-example-shopping/node_modules/@loopback/repository/src/repositories/constraint-utils.ts:58:25)
    at DefaultHasManyRepository.patch (/mnt/e/CI-Cor-Ready/meifu/loopback4-example-shopping/node_modules/@loopback/repository/src/relations/has-many/has-many.repository.ts:112:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
      1) patches all orders for a given user
```

## Expected Behavior
```
Do not report 500 error.
```

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment] 2019-06-18 18:45
@jannyHou , could you please take a look and see if this is still valid? Thanks.

**Comment by jannyHou** [comment] 2019-09-19 20:41
@lygstate Could you provide more details about your implementation? From the error message, this is not related to authentication, the error looks like come from an invalid payload. 

It would be good if you can upload your code.

**Comment by jannyHou** [comment] 2019-11-01 15:13
The patch method(and other default CRUD methods) already has arguments defined, so in your case, you can inject the current user in [controller's constructor](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/controllers/user.controller.ts#L36-L45)

**Comment by jannyHou** [comment] 2020-01-08 16:53
hey @lygstate any update on this issue? Any luck on trying https://github.com/strongloop/loopback-next/issues/2362#issuecomment-548825713 and get it work?

**Comment by jannyHou** [comment] 2020-05-04 22:29
I am closing this issue given the answer in https://github.com/strongloop/loopback-next/issues/2362#issuecomment-548825713, but feel free to reopen it if you still have problems. Thanks for understanding.

**Closed by jannyHou** 2020-05-04 22:29 UTC
Labels: Authentication, question

**Comment by pilare** [comment] 2020-08-13 21:19
@jannyHou @lygstate I've noticed the same problem. Using @inject with @patch operator works different than with any other CRUD verbs. It messes up the order of arguments. requestBody is flipped with optional where parameter. After making where required and inserting it before requestBody part everything goes back to normal. I am using it in the CLI generated controller from hasMany relation. If I have more time on it I will try on the newest version loopback-next codebase, I’m currently using May release. When this is confirmed I will open it back again or try to fix it.

**Comment by jannyHou** [comment] 2020-08-14 14:38
@pilare Thank you for updating with more information. 
> When this is confirmed I will open it back again or try to fix it.

Thank you again and we appreciate your help! Feel free to submit a PR and I will help review & land it.
