### ISSUE TITLE
Spike: Accessing remote Services (REST, SOAP, etc.)

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#451] opened 2017-07-18 16:39 UTC
We should write a guide explaining Services. When to use them, how to write them, how they differ from Repositories. Then provide necessary support in LoopBack4 runtime (the framework).

Describe how to test the services in "Testing your Application" and "Testing your Extension".

This should also include content for: "Calling other APIs and Web Services"

Related to: https://github.com/strongloop/loopback-next/issues/522 and https://github.com/strongloop/loopback-next/issues/451 and https://github.com/strongloop/loopback-next/issues/202

**Comment by dhmlau** [comment] 2018-03-27 16:31
Duplicate of #1069 and #1070

**Closed by dhmlau** 2018-03-27 16:31 UTC
Labels: Core-GA, Docs, backlog, non-DP3
