### ISSUE TITLE
[OpenAPI] Support top-down consumption of full v3 spec

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#751] opened 2017-11-17 16:49 UTC
## Story
As a LoopBack4 user, I would like to be able to use my OpenAPI spec to scaffold a LoopBack4 application

## Acceptance Criteria
TBD

**Comment by shenghu** [comment] 2017-11-18 09:17
@shimks will loopback 4 support openapi 3 initially in later release?

**Comment by shimks** [comment] 2017-11-27 16:17
@shenghu It is going to be supported in the later releases. We are currently hashing out the plans for the degree for its support

**Comment by jannyHou** [comment] 2017-11-27 17:57
Hi @shenghu thank you for being interested in this feature, we have a spike story for it https://github.com/strongloop/loopback-next/issues/739, and will keep updating our plan in the comment.

**Comment by bajtos** [comment] 2017-12-08 14:37
I think this is a duplicate of https://github.com/strongloop/loopback-next/issues/725, what do you think @jannyHou and @kjdelisle ?

**Comment by jannyHou** [comment] 2017-12-11 16:39
hmm...yeah looks like #725 was created earlier and contains more details :-p

**Comment by dhmlau** [comment] 2018-01-17 20:08
in that case, can we close it as dup of #725?

**Comment by shenghu** [comment] 2018-03-01 04:01
#725 doesn't indicate to support openapi 3.  Although we still call swagger 2.0, etc. But the whole swagger spec is renamed as OpenAPI. I'm fine #725 can cover this requirement. Just hope this can be support as early as possible.

**Comment by bajtos** [comment] 2018-10-19 11:57
Closing in favor of #1882.

**Closed by bajtos** 2018-10-19 11:57 UTC
Labels: OpenAPI, team-apex
