### ISSUE TITLE
Error: Unable to authenticate, need: NTLM, Basic realm="Pinacolada"

### ISSUE THREAD

**Issue by zero-bugs** [strongloop/loopback-next#2213] opened 2019-01-04 02:05 UTC
## Description / Steps to reproduce / Feature proposal
After I installed @loopback/cli， I use ‘lb4 example’ to create a new project, I get an error.
## Current Behavior

E:\code_source\Node>npm install -g @loopback/cli
D:\DevTool\node\nodejs\node_global\lb4 -> D:\DevTool\
e_modules\@loopback\cli\bin\cli-main.js
+ @loopback/cli@1.4.0
added 551 packages from 304 contributors in 77.099s

--------------------------------------
E:\code_source\Node>lb4 example
? What example would you like to clone? soap-calculator
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Unable to authenticate, need: NTLM, Basic realm="Pinacolada"
    at res.buffer.catch.then.body (D:\DevTool\node\nodejs\node_global\node_modul
es\@loopback\cli\node_modules\npm-registry-fetch\check-response.js:94:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (D:\DevTool\node\nodejs\node_global\node_modules\@
loopback\cli\node_modules\yeoman-generator\lib\index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

## Expected Behavior
I expect the tutorial works well.
https://loopback.io/doc/en/lb4/soap-calculator-tutorial.html

**Comment by dhmlau** [comment] 2019-01-18 14:33
@zero-bugs , I just tried to clone the soap-calculator example. There is no error for me, and I was able to start the application too.  We recently released a new version of `@loopback/cli`, you might want to update it and try it out.  Thanks!

**Comment by dhmlau** [comment] 2019-01-26 03:33
@zero-bugs, I'd like to close this issue because the issue cannot be reproduced using `@loopback/cli@1.5.1`.  Please feel free to reopen if you're still running into this problem.  Thanks.

**Closed by dhmlau** 2019-01-26 03:33 UTC
Labels: CLI

**Comment by zero-bugs** [comment] 2019-02-18 01:37
by set npm as below, I solved my problem.
npm config set registry "http://registry.npmjs.org/"

This is because my network proxy just support http as NTLM auth.

**Comment by rajat-sawant-wu** [comment] 2021-01-04 15:55
For me it worked by making the registry url **https**

npm config set registry "https://registry.npmjs.org/"
