### ISSUE TITLE
Cannot POST array for multi insert anymore ?

### ISSUE THREAD

**Issue by mathias22osterhagen22** [strongloop/loopback-next#5716] opened 2020-06-11 12:59 UTC
## Steps to reproduce
1. Go on the /explore link of the API
2. Open a POST REST route that is made to add a new model insertion 
Replace the object by an array of the object : 
![image](https://user-images.githubusercontent.com/60438474/84387549-7796de00-abf3-11ea-8f00-a876f659d2be.png)
3. Click execute

## Current Behavior
422 error

![image](https://user-images.githubusercontent.com/60438474/84387623-98f7ca00-abf3-11ea-85cd-4709625fb408.png)

## Expected Behavior
A success answer with the entries in an array like this I suppose: https://github.com/strongloop/loopback/issues/1275#issuecomment-264409854
```js
[
   {
     "id": "3"
     "name": "array one"
   },
   {
     "id": "4"
     "name": "array two"
   }
]
```

## Link to reproduction sandbox
https://github.com/mathias22osterhagen22/loopback-array-post-sample

## Additional information
Seems like it was working on the previous version? 
https://stackoverflow.com/a/54955999/12530707

**Comment by madaky** [comment] 2020-06-13 15:21
See :
https://stackoverflow.com/questions/62324229/loopback-post-array-of-entry/62329457#62329457

**Comment by madaky** [comment] 2020-06-18 06:47
@mathias22osterhagen22 : You can also use 
`Promise<People[]> {
  return await this.peopleRepository.createAll(people)
}`
@achrinza  we can close this issue as its solved..

**Comment by achrinza** [comment] 2020-06-19 13:40
Just to summarise,

- `@requestBody.array()` is needed to allow OpenAPI validation to accept an array of the model.
- `yourRepoHere.createAll()` is needed to allow the ORM to accept an array of the model.

I'll close this issue due to no reply, and the question being straightforward and well-documented;

Feel free to ping this issue if the problem is not resolved.

## Further reading
- https://loopback.io/doc/en/lb4/apidocs.repository.defaultcrudrepository.createall.html
- https://loopback.io/doc/en/lb4/Decorators_openapi.html#requestbodyarray

**Closed by achrinza** 2020-06-19 13:40 UTC
Labels: OpenAPI, question
