### ISSUE TITLE
Refactor http layer constructs and logic out of the @loopback/rest to @loopback/http-server

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#1253] opened 2018-04-12 20:52 UTC
## Description
With the introduction of #1082, `@loopback/http-server` unifies common interfaces for creating endpoints using http/https protocols. This means that `@loopback/rest` can consume fortified `Request` and `Response` objects, and http handlers from concrete implementations of `@loopback/http-server` such as `@loopback/http-server-express` and worry only about how to handle controller/route registration, sequence actions, etc.

**Comment by dhmlau** [comment] 2018-04-20 17:31
The PR from @raymondfeng covered most of the requirements already.

**Comment by b-admike** [comment] 2018-04-23 16:02
@dhmlau Yes I think so; this story is for the remaining items.

**Comment by hacksparrow** [comment] 2018-04-23 16:06
At the moment,`http-server-koa` is non-functional (which is on the #1082 branch). We need it to be working to compare Express vs. Koa. I am working on it to make it functional.

**Comment by dhmlau** [comment] 2018-05-15 13:03
closing as duplicate of #1293.

**Closed by dhmlau** 2018-05-15 13:03 UTC
Labels: DP3
