### ISSUE TITLE
Query filter not work with include

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#3942] opened 2019-10-16 18:05 UTC
## Steps to reproduce

When sending a request to a GET method with a query object like this:
```
{
  "limit": 1,
  "include": [
    {
      "relation": "user"
    }
  ]
}
```
this does not work.
Inside the controller you only receive: `{ limit: '1' }`

@raymondfeng @bajtos

**Comment by frbuceta** [comment] 2019-10-16 18:10
### Extending the previous comment

I send through the explorer of
```
{
  "where": {},
  "fields": {
    "id": true,
    "userId": true,
    "type": true,
    "key": true,
    "value": true
  },
  "offset": 0,
  "limit": 1,
  "skip": 0,
  "order": [
    "string"
  ],
  "include": [
    {
      "relation": "user",
      "scope": {
        "where": {},
        "fields": {},
        "offset": 0,
        "limit": 1,
        "skip": 0,
        "order": [
          "string"
        ]
      }
    }
  ]
}
```

Loopback receipt: `{ offset: '0', limit: '1', skip: '0' }`

**Comment by frbuceta** [comment] 2019-10-22 14:02
The problem is in the browser. Since Postman works!

**Comment by irineul** [comment] 2019-10-22 14:20
hi, @frbuceta could you send your controller method?

**Comment by frbuceta** [comment] 2019-10-22 14:22
It is a controller generated by default with the CLI

```typescript
  @get('/vehicles', {
    responses: {
      '200': {
        description: 'Array of Vehicle model instances',
        content: {
          'application/json': {
            schema: {type: 'array', items: getModelSchemaRef(Vehicle)},
          },
        },
      },
    },
  })
  async find(
    @param.query.object('filter', getFilterSchemaFor(Vehicle)) filter?: Filter<VehicleWithRelations>,
  ): Promise<Vehicle[]> {
    return this.vehicleRepository.find(filter);
  }
```

**Comment by irineul** [comment] 2019-10-22 15:09
Ok, and now please send me your Vehicle Model and User Model.

**Comment by agnes512** [comment] 2019-10-24 16:59
@frbuceta I quickly tried your query with our [`todo-list` example](https://loopback.io/doc/en/lb4/todo-list-tutorial.html). It works fine to me. I got 
```
[
  {
    "id": 1,
    "title": "Take over the galaxy",
    "desc": "MWAHAHAHAHAHAHAHAHAHAHAHAHAMWAHAHAHAHAHAHAHAHAHAHAHAHA",
    "todoListId": 1
  }
]
```

with query 
```
{
  "limit": 1,
  "include": [
    {
      "relation": "todoList"
    }
  ]
}
```
I don't see your models and repositories. For using inclusion, make sure that
1. define the relation well ( correct source id name, foreign name, relation name, etc)
2. enable the `inclusionResolver` for that relation. you can enable it in [repository file](https://loopback.io/doc/en/lb4/todo-list-tutorial-repository.html), or enable it when you set up the relation through CLI `lb4 relation`. 
3. use the correct relation name in query. In my case, a `Todo` belongsTo a `TodoList`. And this `belongsTo` relation named `todoList`. I query the inclusion with the relation name.

Except the site, you can also check a blog about inclusion https://strongloop.com/strongblog/inclusion-of-related-models/

Let me know if you need more help. Thanks.

**Comment by agnes512** [comment] 2019-10-24 17:57
@frbuceta I quickly tried your query with our todo-list example with query
```
{
 "limit": 1,
 "include": [
   {
     "relation": "todoList"
   }
 ]
}
```
I got
```
[
 {
   "id": 1,
   "title": "Take over the galaxy",
   "desc": "MWAHAHAHAHAHAHAHAHAHAHAHAHAMWAHAHAHAHAHAHAHAHAHAHAHAHA",
   "todoListId": 1 // this is wrong
 }
]
```
But when I tried it with url: 
```
http://127.0.0.1:3000/todos/?filter[limit]=1&filter[include][][relation]=todoList
```
, I got the correct result:
```
{ "id":1,
  "title":"Take over the galaxy",

 "desc":"MWAHAHAHAHAHAHAHAHAHAHAHAHAMWAHAHAHAHAHAHAHAHAHAHAHAHA",
 "todoListId":1,
 "todoList":{
    "id":1,
    "title":"Sith lord's check list"
  }
}
```
I think that's a bug in our API Explorer when it filters `limit` and `include`.. 

Could you try the url and see if it returns the expected result? Thanks.

**Comment by bajtos** [comment] 2019-11-01 08:55
It's a known bug of our API Explorer that filter fields like `include` are not supported - see https://github.com/strongloop/loopback-next/issues/2208.

**Comment by dhmlau** [comment] 2019-11-14 14:50
Closing as duplicate of https://github.com/strongloop/loopback-next/issues/2208. Please continue the discussion over https://github.com/strongloop/loopback-next/issues/2208. Thanks!

**Closed by dhmlau** 2019-11-14 14:50 UTC
Labels: bug
