### ISSUE TITLE
Loopback 4 Todo Example creates 404

### ISSUE THREAD

**Issue by MrApe** [strongloop/loopback-next#1747] opened 2018-09-23 20:23 UTC
## Description / Steps to reproduce / Feature proposal

````shell
$ lb4 example todo
$ cd loopback4-example-todo
$ npm start
````

Open Browser at [http://[::1]:3000](http://[::1]:3000).

## Current Behavior

The app shows "NotFoundError":

![bildschirmfoto 2018-09-23 um 22 17 27](https://user-images.githubusercontent.com/98466/45932570-7d134700-bf7e-11e8-9e92-6b1f0ef83426.png)

## Expected Behavior

The app should not show 404 error.

## Plattform

**OS**: MacOS 10.14
**Node Version**: v10.8.0

I tried on **Safari 12.0** and **Chrome 69**.

````shell
$ lb4 --version
@loopback/cli version: 0.24.0

@loopback/* dependencies:
  - @loopback/authentication: ^0.11.14
  - @loopback/boot: ^0.14.0
  - @loopback/build: ^0.7.3
  - @loopback/context: ^0.12.10
  - @loopback/core: ^0.11.11
  - @loopback/metadata: ^0.9.9
  - @loopback/openapi-spec-builder: ^0.9.1
  - @loopback/openapi-v3-types: ^0.9.3
  - @loopback/openapi-v3: ^0.14.4
  - @loopback/repository-json-schema: ^0.10.14
  - @loopback/repository: ^0.17.1
  - @loopback/rest: ^0.24.0
  - @loopback/testlab: ^0.13.0
  - @loopback/docs: ^0.20.0
  - @loopback/example-hello-world: ^0.10.0
  - @loopback/example-log-extension: ^0.11.14
  - @loopback/example-rpc-server: ^0.11.8
  - @loopback/example-todo: ^0.19.0
  - @loopback/example-soap-calculator: ^0.4.0
  - @loopback/dist-util: ^0.3.7
  - @loopback/service-proxy: ^0.8.5
  - @loopback/http-caching-proxy: ^0.3.9
  - @loopback/http-server: ^0.4.0
  - @loopback/example-todo-list: ^0.5.0
````

**Comment by marioestradarosa** [comment] 2018-09-23 20:41
Relates to https://github.com/strongloop/loopback-next/issues/1745

**Comment by raymondfeng** [comment] 2018-09-23 22:16
duplicate of #1745

**Closed by raymondfeng** 2018-09-23 22:16 UTC
