### ISSUE TITLE
Model genertor

### ISSUE THREAD

**Issue by AnanthGopal** [strongloop/loopback-next#4813] opened 2020-03-07 17:44 UTC
[typeorm-model-generator](https://www.npmjs.com/package/typeorm-model-generator) is the NPM package used to generate models for Nest.js framework. Is there a similar generator in LoopBack 4?

The package very useful to generate model hence I am asking...

**Comment by mastermunj** [comment] 2020-03-08 05:18
@AnanthGopal Please check [Model Generator](https://loopback.io/doc/en/lb4/Model-generator.html) and [Repository Generator](https://loopback.io/doc/en/lb4/Repository-generator.html)

You should also check out other [CLI References](https://loopback.io/doc/en/lb4/Command-line-interface.html).

**Comment by achrinza** [comment] 2020-03-08 06:12
Hi @AnanthGopal, discovering models from an existing database is possible with [`lb4 discover`](https://loopback.io/doc/en/lb4/Discovering-models.html)

**Comment by AnanthGopal** [comment] 2020-03-09 09:56
thank you @achrinza .  that command generates only model properties, that do not generate the relationship between the tables. how to generate the modelwith relationships

**Comment by achrinza** [comment] 2020-03-09 10:08
@AnanthGopal Unfortunately this isn't possible at the moment: #3490

**Comment by AnanthGopal** [comment] 2020-03-09 10:09
okay, thank you. is it possible include this feature in the future?

**Comment by achrinza** [comment] 2020-03-09 14:11
>
> is it possible include this feature in the future?
>

The lb legacy juggler is a bit out of my knowledge; @bajtos and @raymondfeng may be able better-equipped in answering this question.

We'll close this issue so that we can continue discussions in #3490. Feel free to put your input in that issue instead.

**Comment by achrinza** [comment] 2020-03-09 14:11
Duplicate of #3490

**Closed by achrinza** 2020-03-09 14:11 UTC
Labels: question
