### ISSUE TITLE
Automatic configuration of Models in Application

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#816] opened 2017-12-21 15:59 UTC
## Story
As a LoopBack 4 developer, I'd like my models to automatically be loaded into my application on boot, so that I don't have to write tons of bind calls myself.

## Acceptance Criteria
- [ ] On application boot
  - Read `src/models` by default (configurable)
  - Parse the JS (TS) files as models and bind them to the app-level context
  - Parse the JSON/YAML files as metadata and call the underlying `model / property` decorator functions to associate that metadata with the corresponding JS/TS model files
  Ex.
```ts
const modelClass = loadModel(modelPath);
const metadataObject = loadMetadata(metaPath);
// @model is just model
model(metadataObject)(modelClass);
```
- [ ] Docs on loopback.io
- [ ] Blog post about the new functionality

## Other Details

**Comment by bajtos** [comment] 2018-07-30 13:13
Closing as a duplicate of https://github.com/strongloop/loopback-next/issues/1428

**Closed by bajtos** 2018-07-30 13:13 UTC
Labels: Boot, LB4 GA, non-DP3
