### ISSUE TITLE
Include related models in "GET /mymodels" results

### ISSUE THREAD

**Issue by GuillaumeJasmin** [strongloop/loopback-next#1889] opened 2018-10-20 18:48 UTC
### Description
Hi,
I start a big migration since Loopback 4 is now the current release.
However, there is many things not documented.

I try to use include filter, but it seems doesn't work. I'm not able to use it on my current project. I followed examples on the docs.

I first thought that my configuration was bad, so I tried it on `loopback4-example-todo-list`, but it doesn't work on the example too.

### Current Behavior
When I try this request: 

```js
http://localhost:3000/todo-lists?filter={"include": [{"relation": "todos"}]}
```

or this
```
http://localhost:3000/todo-lists?filter[include]=todos
```

I get this 500 error: 
```
500 Error: Relation "todos" is not defined for TodoList model
```

### Expected Behavior
Should works like Loopback 3

How I can work with relation and the include filter on Loopback 4 ?

Thanks :)

### Acceptance Criteria
- [ ] All relations are supported (HasMany, BelongsTo, HasOne, etc.)
- [ ] When passing the parameter name, quotes are not required to wrap around the param name. i.e.
It should be:
```
http://localhost:3000/todo-lists?filter={"include": [{"relation": "todos"}]}
```
not:
```
http://localhost:3000/todo-lists?"filter"={"include": [{"relation": "todos"}]}
```

**Comment by dhmlau** [comment] 2018-10-22 17:51
@GuillaumeJasmin, it seems to be working with:
```
http://localhost:3000/todo-lists?"filter"={"include": [{"relation": "todos"}]}
```
not (please note the quotes around the param name): 
```
http://localhost:3000/todo-lists?filter={"include": [{"relation": "todos"}]}
```

Then it comes to the question that whether the param name should be wrapped around the quotes.  I'll get back to you on that.  Hope it will get you going first.

Another way to test (which I usually do) is to use the API Explorer, which can be found at:
```
http://localhost:3000/explorer
```

**Comment by dhmlau** [comment] 2018-10-22 18:36
@GuillaumeJasmin, talked to @raymondfeng and it looked like a bug that the quotes are needed for param name.  Marking it as `bug`.

**Comment by mrbatista** [comment] 2018-10-25 09:38
@GuillaumeJasmin the include functionality is not yet implemented.

> `http://localhost:3000/todo-lists?"filter"={"include":[{"relation":"todos"}]}`
The expect behavior is to return for each todo lists the list of todos, but nothing is returned.
This seems a lack of funcitonality.

**Comment by mrbatista** [comment] 2018-10-25 09:40
@GuillaumeJasmin see #1352

**Comment by bajtos** [comment] 2018-10-25 13:30
This is a missing feature indeed, I am relabeling the issue.

@GuillaumeJasmin thank you for writing down your concerns and feelings about LoopBack 4. We are fully aware of the gap in feature parity between LoopBack 3 and LoopBack 4 and that LB4 is not a drop-in replacement for LB3 in many cases. On the other hand, if we were waiting until LB4 reached functional parity with LB3, then it would take few more years to reach the GA release, considering the size of our team and the scope of LB3 features. To avoid that situation, we decided to cut down the scope, release 4.0 GA early and start gathering feedback about which features are most important to our users. That allows us to better prioritize our efforts on areas where we can add most value.

I'll try to find some time later to respond to other parts of your comment in more details, maybe in a blog post or a doc page.

**Comment by GuillaumeJasmin** [comment] 2018-10-25 14:34
Thank you for this clarification comment about LB4. Maybe the release name "current" is confusing ? Usually, a stable version of software doesn't remove a powerful feature included into the previous release.
If you release 4.0 in order to get some feedback to prioritize, and you know that the 4.0 release doesn't currently include all nice features of 3.0, it's not a stable version (except if the feature is willingly removed). I think this situation is the same than beta version: a way to share it to the end users, but with the warning that it's not stable.

I think you shouldn't communicate about a stable version, because users thinks "ok, I can now use it on production like the previous version, with some days of migration". I think this could create many frustration for the end developers.
Maybe I'm the only one frustrated by that, so my point of view is not important, but I think others have come up against the same issues when they try a migration.

I thinks it's just a communication issue around "current" and "beta".

However, thanks for your work on Loopback, it's a great tool, and I hope (and believe) LB4 will be as simply as LB3 after legacy features finished and some useful extensions that reproduce the default behavior of LB3 (I would like to contribute and develop theses extensions, but I need time to completely understand how write good extensions on LB4)

**Comment by GuillaumeJasmin** [comment] 2018-10-25 14:50
API explorer is confusing because it show an include filter, even if the feature is missing.

![screen shot 2018-10-25 at 16 40 39](https://user-images.githubusercontent.com/3513444/47508638-c522d380-d874-11e8-9994-5d9187d99590.png)


@dhmlau I can't use API explorer because it doesn't work with nested object:
look the filter field on the screenshot, and then the `request URL`: the filter is not sent. It seems related to https://github.com/swagger-api/swagger-js/issues/1385

![screen shot 2018-10-25 at 16 42 39](https://user-images.githubusercontent.com/3513444/47508878-35315980-d875-11e8-85b5-52608b551445.png)

**Comment by dhmlau** [comment] 2018-10-25 18:55
@GuillaumeJasmin, thanks for letting me know. Yes, the UI has limitation to allow nested properties.  We've captured this in issue https://github.com/strongloop/loopback-next/issues/1470 as well.

**Comment by bajtos** [comment] 2018-10-26 07:34
FWIW, the actual work on supporting inclusion of related models is tracked by the following two issues: https://github.com/strongloop/loopback-next/issues/1352 and https://github.com/strongloop/loopback-next/issues/1721

**Comment by franfran3** [comment] 2018-10-26 08:01
Looks like escaping the parameter name `"filter"` does not solve the problem as it ignore filters: 
```
http://localhost:3000/todo-lists?"filter"={"where": {"id":4}, "include":[{"relation":"todos"}]}
```
does not apply `where` neither `include`.

**Comment by bajtos** [comment] 2018-10-26 12:02
> Thank you @bajtos for this clarification comment about LB4. Maybe the release name "current" is confusing ?
> I think it's just a communication issue around "current" and "beta".

I agree with you, we need to find a way how to better communicate the status of LoopBack 4 and set reasonable expectations.

>  For example, why do not provide a set of extensions in order to keep the simplicity of LB3, without the needed to create repository, controller for default CRUD actions (only if we need custom actions) ?

Yes please! It's our design goal to keep LoopBack 4+ extensible and allow the community to experiment with different styles of project layout. We don't have bandwidth to implement and maintain all such extensions ourselves, but we are happy to help anybody willing to step up and write such extension themselves.

As for repositories, it's already possible to use `DefaultCrudRepository` without creating per-model repository classes.

In https://github.com/strongloop/loopback-next/pull/740, @raymondfeng has proposed an extension providing REST API via a base controller class `CrudController` that provides usual querying and CRUD operations, similar to what the controllers scaffolded by `lb4 controller` do (but without the scaffolding step).

With these two buildings blocks, I imagine one can write a small piece of code accepting a model class an exposing it via REST API, see the mock-up implementation below. It's just an illustration to show what I mean, it will probably not work out of the box and may require cleanup.

```ts
// usage - this can be automated via a custom Booter
import {Product, Category} from './models';

export class MyApplication extends RepositoryMixin(RestApplication) {
 constructor() {
    super();  
    exposeModelViaRest(app, Product);
    exposeModelViaRest(app, Category;
  }
}

// implementation
function exposeModelViaRest<T extends Entity>(
  app: ApplicationWithRepositories,
  dataSourceName: string, 
  modelCtor: Class<T>
) {
  const REPOSITORY_KEY = `repositories.${modelCtor.modelName}Repository`;
  app.bind(REPOSITORY_KEY).toDynamicValue(() => {
    const ds = await ctx.get(`datasources.${dataSourceName}`);
    return new DefaultCrudRepository(modelCtor, ds);
  });

  app.controller(createCrudControllerForModel(modelCtor, REPOSITORY_KEY));
}

function createCrudControllerForModel<T extends Entity>(
  modelCtor: class<T>,
  repositoryKey: string
) {
  // It is not possible to access closure variables like "BaseController"
  // from a dynamically defined function. The solution is to
  // create a dynamically defined factory function that accepts
  // closure variables as arguments.
  const name = modelCtor.modelName + 'Controller';
  const factory = new Function('BaseController', 'repositoryName', `
    class ${name} extends BaseController {
      constructor(repository) {
        super(repository);
      }
    }`);

  const controllerCtor = factory(CrudController, repositoryName);
  // apply @inject() decorator on the first constructor parameter
  inject(repositoryKey)(controllerCtor, undefined, 0);
  return controllerCtor;
}        
```

I am pretty sure there are other ways how auto-wire REST API for models, let's experiment!

**Comment by ZeroCoolJr** [comment] 2018-10-29 00:16
Related issue #1909

**Comment by bajtos** [comment] 2018-10-30 07:40
> For example, why do not provide a set of extensions in order to keep the simplicity of LB3, without the needed to create repository, controller for default CRUD actions (only if we need custom actions) ?

It turns out we already have stories to address this use case, see [Declarative Support #565](
https://github.com/strongloop/loopback-next/issues/565) and [Define model relations in JSON file or in JavaScript code #695](
https://github.com/strongloop/loopback-next/issues/695)

**Comment by bajtos** [comment] 2018-11-02 09:05
@dhmlau I think we should close this issue as a duplicate of https://github.com/strongloop/loopback-next/issues/1352 and copy any relevant information over to the other issue. Thoughts?

**Comment by bajtos** [comment] 2018-11-06 10:02
I have posted a comment in the other issue with a proposal how to implement inclusion of related models at Repository level, see https://github.com/strongloop/loopback-next/issues/1352#issuecomment-436197152

**Comment by bajtos** [comment] 2019-02-12 12:02
Closing this issue as a duplicate of
- Inclusion of related models #1352.

See also:
- Add support for "include" and "fields" to findById (REST API) #1721 
- From model definition to REST API with no repository/controller classes #2036

**Closed by bajtos** 2019-02-12 12:02 UTC
Labels: Relations, Repository, TOB, feature, feature parity
