### ISSUE TITLE
where to set access token and other field in header with explorer

### ISSUE THREAD

**Issue by shendkardevesh** [strongloop/loopback-next#2205] opened 2019-01-02 07:28 UTC
want to set an access token and other secret key in header for every api from explorer

**Comment by bajtos** [comment] 2019-01-03 15:04
IIRC, the recent version of swagger-ui is honoring auth options as described in the OpenAPI spec. So in order to have UI for setting access token, the spec produced by an LB4 app must advertise how that token should be provided by the clients.

**Comment by shendkardevesh** [comment] 2019-01-09 10:07
which version on swagger-ui i that

**Comment by vvdwivedi** [comment] 2019-01-09 12:10
@bajtos Is there any example on how to add this?

**Comment by shendkardevesh** [comment] 2019-01-09 14:09
> @vvdwivedi @shendkardevesh here is an example - [#2210 (comment)](https://github.com/strongloop/loopback-next/pull/2210#issuecomment-451866876)

Schema error should NOT have additional properties
additionalProperty: securityDefinitions
Jump to line 0

giving me error while editing the swagger

**Comment by lygstate** [comment] 2019-02-07 04:34
What's the progress?

**Comment by dhmlau** [comment] 2019-03-01 16:35
Related: https://github.com/strongloop/loopback-next/issues/2027

**Comment by dhmlau** [comment] 2019-04-12 15:05
Closing as duplicate of #2027.
Please continue the discussion in #2027.  Thanks!

**Closed by dhmlau** 2019-04-12 15:05 UTC
Labels: API Explorer, Authentication, TOB, feature
