### ISSUE TITLE
Integration of services with controllers (technical preview)

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#1267] opened 2018-04-19 23:12 UTC
## Description

Explore how service integration works with controllers. This task is an outcome of https://github.com/strongloop/loopback-next/issues/1069.

## Use case

A controller needs to invoke a REST API or SOAP web service.
```ts
export class ShoppingController {

  @serviceProxy('pricingService')
  private pricingService: pricingService;

  @serviceProxy('shippingService')
  private shippingService: ShippingService;
}
```

Or 
```ts
export class ShoppingController {
  constructor(
    @serviceProxy('pricingService')  private pricingService: pricingService,
    @serviceProxy('shippingService') private shippingService: ShippingService
  ) {}
}
```

We'll configure two datasources and bind them to the context.

- pricingService: REST API
- shippingService: SOAP Web Service API

```ts
context.bind('dataSources.pricingService').to(...);
context.bind('dataSources.shippingService').to(...);
```

## Acceptance Criteria
- Controllers can use `@serviceProxy` decorator for constructor parameters or properties to inject a service proxy for backend services
- The service proxy can be resolved from data source name or instance
- The service proxy can be optionally typed with a hand-written TS type/interface

**Comment by raymondfeng** [comment] 2018-04-23 15:51
See https://github.com/strongloop/loopback-next/blob/970524567a15f1162bc244f060eb602b7647f9c5/packages/service/test/unit/decorators/service-proxy.decorator.unit.ts

**Comment by shimks** [comment] 2018-04-30 17:38
@raymondfeng Could you update the acceptance criteria for estimation? Thanks

**Comment by raymondfeng** [comment] 2018-04-30 18:04
@shimks Updated

**Comment by virkt25** [comment] 2018-05-01 14:51
Is the Service assumed to be created using LB3 constructs? (strong-remoting / strong-soap)?

**Comment by b-admike** [comment] 2018-05-01 17:52
Looking at the PR we have for the weakly typed service integration spike, we already have the `serviceProxy` decorator and have a test [using it](https://github.com/strongloop/loopback-next/pull/1119/files#diff-0d86b9e5dd03df9302f718139dc63a07R24) with a controller as shown above. What else do we need to for this ticket?
>Is the Service assumed to be created using LB3 constructs? (strong-remoting / strong-soap)?

Yeah I think so (see https://github.com/strongloop/loopback-next/pull/1119/files#diff-acfd88705f55f0e2f6831937a276b7fbR19).

**Comment by raymondfeng** [comment] 2018-05-01 17:53
The PR is feature complete and ready for review.

**Comment by bajtos** [comment] 2018-05-04 12:46
Cross-posting from https://github.com/strongloop/loopback-next/issues/1069#issuecomment-385993406:

IMO, the pull request #1119 is only a part of the overall story. While it makes it easy to consume services in controllers, it omits other important use cases.

1] When consuming a service using REST connector with template-based configuration: As an app developer, I would definitely want to have few smoke tests to verify that my templates work as intended and match the API provided by the service at the other side. I would like to write an integration test that's using only the service (not the full app!), something along the following lines:

```ts
import {GeoService} from '../services/geo.service';
import {expect} from '@loopback/testlab';

describe('GeoService', () => {
  let service: GeoService;
  beforeEach(() => service = new GeoService());

  describe('geocode', () => {
    it('returns geo coords for a given address', () => {
      const result = await service.geocode('107 S B St', 'San Mateo', '94401');
      // { lat: 37.5669986, lng: -122.3237495 }
     expect(result.lat).approximately(37.5669986, 0.5);
     expect(result.lng).approximately(-122.3237495, 0.5);
    });
  });
});
```

2] There should be also a new CLI command for creating services, this command should:
 - Create the datasource.
 - Create any artifacts needed to register the service with the app for dependency injection. This may require us to implement support for services in `@loopback/boot`.
 - Create any artifacts needed to write an integration test for the service as I shown above.
 - Ideally, include a scaffolding making it easier for app developers to start writing smoke tests.

**Comment by shimks** [comment] 2018-05-07 14:53
@bajtos Although I agree that what you're proposing should be done as an outcome of the spike, IMO this is out of scope for what we have estimated and I feel that it should live in its own issue to be estimated and groomed.

**Comment by dhmlau** [comment] 2018-05-08 17:13
PR: https://github.com/strongloop/loopback-next/pull/1119

**Comment by shimks** [comment] 2018-05-09 14:44
@raymondfeng Is the (technical preview) feature complete? If so, can you close it please?

**Comment by bajtos** [comment] 2018-05-16 07:40
Closing as done.

**Closed by bajtos** 2018-05-16 07:40 UTC
Labels: DP3
