### ISSUE TITLE
X-Total-Count error loopback4 

### ISSUE THREAD

**Issue by ybarbaria** [strongloop/loopback-next#5571] opened 2020-05-26 20:52 UTC
## Steps to reproduce
I am using loopback4 for my backend and React-Admin to interact with the API.
Every request from ReactAdmin got this error :
> The X-Total-Count header is missing in the HTTP Response. The jsonServer Data Provider expects responses for lists of resources to contain this header with the total number of results to build the pagination. If you are using CORS, did you declare X-Total-Count in the Access-Control-Expose-Headers header?

## Current Behavior
I didn't find any option to add this specific header into loopback4.

## Expected Behavior
It should be possible to manage the header like for almost every framework and language. 

## Additional information
**win32 x64 12.14.1**
**+-- @loopback/boot@2.3.1
+-- @loopback/context@3.8.1
+-- @loopback/core@2.7.0
+-- @loopback/openapi-v3@3.4.1
+-- @loopback/repository@2.5.1
+-- @loopback/rest@5.0.1
+-- @loopback/rest-explorer@2.2.2
+-- @loopback/service-proxy@2.3.0
+-- loopback-connector-mysql@5.4.3**

## Related Issues
I've posted a question on stackoverflow but I didn't have any help.

**Comment by raymondfeng** [comment] 2020-05-26 21:30
@ybarbaria Do you want to add `X-Total-Count` http response header or configure `CORS` to allow it to be sent back to the client?

**Comment by raymondfeng** [comment] 2020-05-26 21:34
For CORS, you can set `exposedHeaders` to include `X-Total-Count`. See https://loopback.io/doc/en/lb4/Server.html#customize-cors and https://expressjs.com/en/resources/middleware/cors.html#configuration-options.

**Comment by ybarbaria** [comment] 2020-05-26 21:42
@raymondfeng Thanks for your response finally I found a solution 
`   this.response.setHeader('Access-Control-Expose-Headers', 'X-Total-Count');
    this.response.setHeader('x-total-count', (await count).length);`

But your solution is definitely better than mine ! :)

**Comment by ybarbaria** [comment] 2020-05-26 21:43
> @ybarbaria Do you want to add `X-Total-Count` http response header or configure `CORS` to allow it to be sent back to the client?

Both :)

**Comment by dhmlau** [comment] 2020-05-28 20:47
Closing as resolved.

**Closed by dhmlau** 2020-05-28 20:47 UTC
Labels: bug

**Comment by albjeremias** [comment] 2021-09-22 20:17
I had hard time to find out.. how..

from the default controller created with lb4 controller:
```
export class RoleController {
  constructor(
---------- add the injected response
    @inject(RestBindings.Http.RESPONSE) private response: Response,
------------
    @repository(RoleRepository)
    public roleRepository : RoleRepository,
  ) {}

async find(
    @param.filter(Role) filter?: Filter<Role>,
  ): Promise<Role[]> {
    
-------- add the header to the response
    return this.roleRepository.find(filter).then((roles) => {
      this.response.setHeader('Access-Control-Expose-Headers', 'X-Total-Count');
      this.response.setHeader('x-total-count', roles.length);
      return roles;
    });
---------
  }
```

**Comment by danysz** [comment] 2021-12-27 04:11
Hello
The issue is closed but I think that is still a problem. I am using the "model-endpoints" so there is no possibility to customize the "Controller" itself. 
I think that a solution should be to create an option for the default controller to expose this information.

Regards

**Comment by raymondfeng** [comment] 2021-12-27 04:38
You can simply inject http response object into your controller class or method parameter to set response headers.see https://loopback.io/doc/en/lb4/Accessing-http-request-response.html

**Comment by danysz** [comment] 2021-12-27 04:43
> You can simply inject http response object into your controller class or method parameter to set response headers.see https://loopback.io/doc/en/lb4/Accessing-http-request-response.html

This is not relevant since the model-endpoint is automatically generated
