### ISSUE TITLE
Routes with parameters are not working in some cases

### ISSUE THREAD

**Issue by ambienthack** [strongloop/loopback-next#2188] opened 2018-12-23 22:26 UTC
## Description / Steps to reproduce / Feature proposal

Create two routes like this

<pre>
  @patch('/users/{userId}/meals/{id}')
  async updateById(
    @param.path.string('userId') userId: string,
    @param.path.string('id') id: string
  ): Promise<void> {
    //anyting
  }

  @patch('/users/{id}')
  async updateById(
    @param.path.string('id') id: string
  ): Promise<void> {
    //anything
  }

</pre>

Make a request PATCH /users/5c1d78842566764efc8b9605

## Current Behavior

<pre>
{
  "error": {
    "statusCode": 404,
    "name": "NotFoundError",
    "message": "Endpoint \"PATCH /users/5c1d78842566764efc8b9605\" not found."
  }
}
</pre>

If the error doesn't arise, try changing parameter names in path patterns, like this:
`@patch('/users/{id}/meals/{mealId}')`
`@patch('/users/{userId}')`

## Expected Behavior

Controller method should be invoked

I believe there is a bug [here](https://github.com/strongloop/loopback-next/blob/master/packages/rest/src/router/trie.ts#L164)

<pre>
    for (const child of children) {
        const result = search(keys, index + 1, params, child.node);
        if (result) {
            Object.assign(params, child.params);
            return result;
        }
    }
</pre>

Should be `if (result && isNodeWithValue(result.node)) {`.

When multiple children are found, if the first child checked is `@patch('/users/{userId}/meals/{id}')`, search() method assumes route is found & doesn't check other routes.

**Comment by Joel-Raju** [comment] 2019-02-07 22:44
I seem to have run into the same issue. These are my controller actions

#### Action 1


    @get('/restaurants/{id}')
    async getRestaurantById(
    @param.path.number('id') id: number,
      ): Promise<Restaurant> {
        console.log(id);
        return await this.restaurantRepository.findById(id);
      }

#### Action 2

    @get('/restaurants/', {
    async find(
    @param.query.object('filter', getFilterSchemaFor(Restaurant))
    filter?: Filter,
    ): Promise<Restaurant[]> {
      return await this.restaurantRepository.find(filter);
    }

****Current Behavior****
Action 1 throws a 404, but Action 2 works fine

    {
      "error": {
        "statusCode": 404,
        "name": "NotFoundError",
        "message": "Endpoint \"GET /restaurants/1\" not found."
      }
    }

## Expected Behavior
Controller method should be invoked

## Other Observations

Even after removing Action 2 and all other actions in the controller that matches the same route Action 1 is still not being invoked.

**Comment by Joel-Raju** [comment] 2019-02-07 22:50
would really appreciate if this could be resolved soon.

**Comment by raymondfeng** [comment] 2019-02-07 23:38
@Joel-Raju Do you have both methods in the same controller class?

**Comment by raymondfeng** [comment] 2019-02-07 23:40
BTW, do you know if `return await this.restaurantRepository.findById(id);` is invoked and returns an instance?

**Comment by raymondfeng** [comment] 2019-02-07 23:47
Can you remove trailing `/` and see?
```ts
@get('/restaurants', {
async find(
@param.query.object('filter', getFilterSchemaFor(Restaurant))
filter?: Filter,
): Promise<Restaurant[]> {
  return await this.restaurantRepository.find(filter);
}
```

**Comment by raymondfeng** [comment] 2019-02-08 00:09
@Joel-Raju Please verify #2355. Let us know wheter the newly added test cover your case or not.

**Comment by Joel-Raju** [comment] 2019-02-08 07:59
@raymondfeng thanks for the quick follow-up

> @Joel-Raju Do you have both methods in the same controller class?

Yes.


> BTW, do you know if `return await this.restaurantRepository.findById(id);` is invoked and returns an instance?

It doesn't seem to hit route `@get('/restaurants/{id})'`, I tried logging before querying the repository


> Can you remove trailing `/` and see?
> 
> ```ts
> @get('/restaurants', {
> async find(
> @param.query.object('filter', getFilterSchemaFor(Restaurant))
> filter?: Filter,
> ): Promise<Restaurant[]> {
>   return await this.restaurantRepository.find(filter);
> }
> ```

When I remove the trailing space, the `@get('/restaurants)'` is being invoked. `@get('/restaurants/{id})'` doesn't work





> @Joel-Raju Please verify #2355. Let us know whether the newly added test cover your case or not.

this covers my use case.

**Comment by raymondfeng** [comment] 2019-02-08 15:42
> When I remove the trailing space, the @get('/restaurants)' is being invoked. @get('/restaurants/{id})' doesn't work

That's weird. What order do you define two routes in the controller? 

Which request URL do you use to invoke the API? With trailing slash or not?

**Comment by Joel-Raju** [comment] 2019-02-08 16:42
I first have `@get(/restaurants)` and then `@get(/restaurants/{id})`. Also tried reversing the order, still doesn't work. 

Even tried just with `@get(/restaurants/{id})` commenting out all other methods in the controller but doesn't work. 

These are the request URLs 

**this works**
`curl -X GET "http://localhost:3001/restaurants" -H "accept: application/json" `

**this doesnt work**
`curl -X GET "http://localhost:3001/restaurants/1" -H "accept: application/json" `

**Comment by raymondfeng** [comment] 2019-02-08 16:45
@Joel-Raju Can you create a simple app that can reproduce your problem and share it with us on github?
You can folk `loopback-next` and add your app to `sandbox` directory.

**Comment by Joel-Raju** [comment] 2019-02-08 19:13
forked and added a sample project that illustrates the issue

https://github.com/Joel-Raju/loopback-next/tree/master/sandbox/test-app

**this route works**
http://localhost:3000/restaurants

**this doesn't work**
http://localhost:3000/restaurants/1

**Comment by Joel-Raju** [comment] 2019-02-08 19:29
Guess I didn't mention that I have a `hasMany` relationship. It worked before I added the relationship.

**Comment by raymondfeng** [comment] 2019-02-08 20:02
@Joel-Raju Thanks for the sample app. I was able to reproduce the problem and fix it in https://github.com/strongloop/loopback-next/pull/2355.

**Comment by raymondfeng** [comment] 2019-02-08 20:12
> Guess I didn't mention that I have a `hasMany` relationship. It worked before adding the relationship.

That's the root cause as you added `/restaurants/{restaurantId}/orders`, which overlaps with `/restaurants/{id}` using **different** var names.

**Comment by Joel-Raju** [comment] 2019-02-08 20:20
oh okay. This will get resolved with #2355 ?

**Comment by raymondfeng** [comment] 2019-02-08 20:22
Yes. Before it's landed, you can probably work around the issue by changing the path `/restaurants/{restaurantId}/orders` to be `/restaurants/{id}/orders`.

**Comment by Joel-Raju** [comment] 2019-02-08 20:25
thanks 👍

**Closed** 2019-02-12 17:47 UTC
Labels: REST, bug, good first issue
