### ISSUE TITLE
Better developer experience in creating a model

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#2131] opened 2018-12-07 15:11 UTC
## Description / Steps to reproduce / Feature proposal

A developer migrating from LB3 will be confused why merely calling `lb4 model` does not end up creating the model and loading it in the app, like how it does in LB3.

Maybe we should optionally include the repository and controller creation steps?

## Current Behavior

```sh
$ lb4 model
....
```

makes it look like everything went well,  but the model is not shown in the API Explorer.

## Expected Behavior

Guide the users, especially LB3 users, when they create a model for the first time.

```sh
$ lb4 model
...
> A LB4 model requires a corresponding repository, would you like to create now? (y/N)
> name of the repository:
...
> A controller must be created for the model, would you like to create now? (y/N)
> name of the controller: 
...
```

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment] 2018-12-07 15:17
@hacksparrow We have discussed to add more composite commands to achieve what LB3 can do. In this case, we can possibly have something like:

```
Do you want to persist the model? (Y/n)
...
Do you want to create a controller from the repository to expose REST APIs? (Y/n)
...
```

The prompt can be possibly skipped with `--repository <repositoryName> --controller <controllerName>` options.

We might want to introduce `lb4 resource` as the composite command.

**Comment by raymondfeng** [comment] 2018-12-07 15:18
Duplicate of https://github.com/strongloop/loopback-next/issues/2036

**Closed by raymondfeng** 2018-12-07 15:18 UTC
