### ISSUE TITLE
LOOPBACK 4 - POSTGREQL ERROR relation "public.XXX" does not exist

### ISSUE THREAD

**Issue by jotamora** [strongloop/loopback-next#5105] opened 2020-04-13 17:02 UTC
Hello,

When you made a simple program in LB4 with postgresql, using the command line interface, you have this error when you try to use the API

**500 error: relation "public.XXX" does not exist**
In my case, with this model:

```
@model({ settings: {} })
export class ImageModel extends Entity {
  @property({
    type: 'string',
    id: true,
  })
  idImage?: string;

  @property({
    type: 'string',
  })
  name?: string;


  constructor(data?: Partial<ImageModel>) {
    super(data);
  }
}
```

I have this problem:
500 error: relation "public.imagemodel" does not exist

If for example I change to a Mongo or to MySQL everything start to works well. Anybody knows what happens with postgre??

Thanks

**Comment by dougal83** [comment] 2020-04-13 19:01
Hi @jotamora 

Have you run the [database migration](https://loopback.io/doc/en/lb4/Database-migrations.html) script? `npm run migrate`

If it is not that can you please make a public repo to on GitHub to enable someone to take a deeper look at the issue?

**Comment by Tpuljak** [comment] 2020-04-14 21:38
I have the same issue, except I. used `lb4 discover` to discover the models from the datasource and then any request towards the database yields the `500 error: relation "public.XXX" does not exist` result.

Also, I tried running `npm run migrate` after the discover but that too yields errors.
`syntax error at or near "null" at character 286` where char 286 points to TIMESTAMP (null) WITH TIME ZONE NOT NULL. Im not sure why (null) is present after TIMESTAMP in the query.... and the other errors are pointing to VARCHAR(undefined) which, I guess, are created from @properties of type `postgresql: {columnName: 'XXX', dataType: 'character varying', dataLength: null,....}`

**Comment by Tpuljak** [comment] 2020-04-14 21:45
I think the issue is with plurality. Most of my tables are in plural form of the model, but queries try to execute on the singular name. Thats why I get an error `500 error: relation "public.user" does not exist`, since the table it should be looking into is "public.users".

**Comment by jotamora** [comment] 2020-04-15 07:20
Hello @Tpuljak ,

I have discover that  lb4 don´t create the table in DB in postgre, if it doesn´t exist, like in Mongo. You need to create the table of the DB first. After that in your model:
```
@model({
  settings: {
    postgresql: {
      table: 'imageModel', <-- the name of the table.
    },
  },
```
})

Careful: For each element in you model, you need to create a column in the table of the DB. If you don´t make that it is going to fail.

I hope loopback team could improve it and could work with postgre like in mongo.

Best,

**Comment by achrinza** [comment] 2020-04-15 07:33
Hi @jotamora, have you tried using the database migration feature in LoopBack 4? That's what's supposed to be used to generate the database.

AFAIK, it requires explicit execution to prevent any accidental data loss.

**Comment by achrinza** [comment] 2020-04-29 23:43
Closing as solved.

**Closed by achrinza** 2020-04-29 23:43 UTC
Labels: db:PostgreSQL, question
