### ISSUE TITLE
Generate tables automatically when the application will be booted

### ISSUE THREAD

**Issue by pharindoko** [strongloop/loopback-next#1941] opened 2018-10-30 10:22 UTC
## Description / Steps to reproduce / Feature proposal
How to generate (mysql) tables automatically

## Current Behavior
In previous version 3 when booting the application I used the automigrate/autoupdate function to create the tables in the database based on the models.

## Expected Behavior
That this will work in a similar way as for lb3 when the application will be booted (app.boot()) or that someone explains me how I get those tables created for lb4.
Do I need a BootMixin ?
Any dynamic way of generating those tables ?

**Comment by pharindoko** [comment] 2018-10-30 10:54
Refers to #1547 - similar topic

**Comment by dhmlau** [comment] 2018-10-30 18:38
Yes, it's a duplicate of #1547.  We'd like to document how to use automigrate/autoupdate in LB4. 
The comments in #1547 mentioned the steps for your reference before we put it in the documentation.  

I'd like to close this issue as duplicate, and please continue the discussion over #1547.  Thanks!

**Closed by dhmlau** 2018-10-30 18:38 UTC
