### ISSUE TITLE
Type safety for services

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#1268] opened 2018-04-20 22:17 UTC
## Description
We need to have TypeScript declarations for the service interface as well as the data model (Developers to craft the declarations?).

Related to #1069 

## Acceptance Criteria
- [ ] Introduce CLI tooling to discover service and introspect the service specifications and generate the corresponding TypeScript artifacts
- [ ] Make this mapping pluggable and extensible to support different api spec flavours (swagger, wsdl, openapi, grpc, graphql, etc)

**Comment by bajtos** [comment] 2018-06-25 11:38
Closing as a duplicate of #1070

**Closed by bajtos** 2018-06-25 11:38 UTC
Labels: Core-GA, Juggler, non-DP3
