### ISSUE TITLE
What environment variables should we use for database configuration?

### ISSUE THREAD

**Issue by ri8ika** [strongloop/loopback-next#2400] opened 2019-02-14 07:53 UTC
After following [medium blog](https://itnext.io/loopback-4-database-configuration-8f085399268), I set the following variables:
```
DATABASE_URL
DB_DATABASE
DB_HOST
DB_PASSWORD
DB_PORT
DB_USER
```

But this is not working.

After some research I found this issue:

https://github.com/strongloop/loopback-boot/issues/4

But I am still not sure what database environment variables are available to use in loopback 4.

---

For further information, I have used the followings inside application.ts inside the constructor:
```
this.bind('datasources.config.db').to({
      name: 'postgres',
      connector: 'postgres',
      hostname: process.env.DB_HOST,
      port: process.env.DB_PORT,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DB_DATABASE,
    });
    this.bind('datasources.db').toClass(PostgresDataSource);
```

I think this is not getting bound, because when try to run migrate on heroku, I get the following error:

```
Connection fails: Error: connect ECONNREFUSED 127.0.0.1:5432
```

**Comment by dhmlau** [comment] 2019-02-14 20:47
I'm transferring your issue to `loopback-next` repo. That's where it should be anyway.

**Comment by dhmlau** [comment] 2019-02-14 20:48
You might also wanna see:
https://github.com/strongloop/loopback-next/issues/2176

Hope it helps.

**Comment by ri8ika** [comment] 2019-02-15 14:06
Hmm, I'm still getting the error even after using Procfile to run index.js when I try to migrate:
```
Error: connect ECONNREFUSED 127.0.0.1:5432
```

**Comment by dhmlau** [comment] 2019-02-15 18:40
Sorry, i misunderstood your issue and it's actually complaining about cannot connect to the Postgresql.  Looking at the code snippet in the original comment, should `hostname` be `host` instead?  It's because in the datasource.json, it's in the form of:
```
{
  "name": "ds",
  "connector": "postgresql",
  "url": "",
  "host": "localhost", <---- HERE
  "port": 5432,
  "user": "root",
  "password": "pass",
  "database": "testdb"
}

```

**Comment by ri8ika** [comment] 2019-02-15 21:22
Good catch. But I'm still having same issue.

**Comment by dhmlau** [comment] 2019-02-16 02:48
@ri8ika, one last thing I can think of.  In this tutorial https://loopback.io/doc/en/lb4/Deploying-to-IBM-Cloud.html#updating-application, it binds the new value in `src/index.ts`:
```
app.bind('datasources.config.db').to(updatedDatasourceDb);
```

I'm not sure what's the difference between setting it here vs in application.ts, perhaps @hacksparrow might be able to answer. 
There are users in the [above mentioned issue](https://github.com/strongloop/loopback-next/issues/2176) who were able to deploy to Heroku, they might have some more insight.

**Comment by ri8ika** [comment] 2019-02-16 05:42
Still  no luck.

**Comment by dhmlau** [comment] 2020-08-24 01:19
@ri8ika, I wasn't able to reproduce this issue. Since this issue was opened more than a year ago, I'd like to close this issue as non-reproducible. If you still encounter this issue, please feel free to ping here or open a new issue. Thanks.

**Closed by dhmlau** 2020-08-24 01:19 UTC
Labels: question
