### ISSUE TITLE
Is it possible to create a simple api path like '/api/*' through controller?

### ISSUE THREAD

**Issue by paulmojo** [strongloop/loopback-next#2248] opened 2019-01-14 08:30 UTC
## Description / Steps to reproduce
I want to catch all GET apis inside a method of a controller. So I provided the path as 'api/*'.
```
@get('/api/*')
async get() {
  // all GET should come here
}
```

## Current Behavior
Only localhost:3000/api/* comes here.
localhost:3000/api/random throws 404

## Expected Behavior
No matter what url I hit, it should appear in that get function of my controller.

**Comment by dhmlau** [comment] 2019-01-15 15:53
@raymondfeng @jannyHou , looking through some of the discussion threads, it might be a limitation in OpenAPI 3.0.  Could you please confirm?  Are there workarounds? Thanks.

- https://stackoverflow.com/questions/42335178/swagger-wildcard-path-parameters: it mentioned a workaround
- https://github.com/OAI/OpenAPI-Specification/issues/892
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#pathsObject

**Comment by dhmlau** [comment] 2019-03-15 03:42
Closing as duplicate of #2183

**Closed by dhmlau** 2019-03-15 03:42 UTC
Labels: question
