### ISSUE TITLE
Using custom (underscored) keys for Relations : "Cannot read property 'target' of undefined"

### ISSUE THREAD

**Issue by esoodev** [strongloop/loopback-next#2169] opened 2018-12-18 07:56 UTC
## Description
I am using an existing MySQL database and its schemas, and am following [the tutorial](https://loopback.io/doc/en/lb4/Relations.html) to build relations.

## Current Behavior
- User has many Review
- Review belongs to User

Due to the existing schema, Review has 'user_id' field that links to User's 'id.' I coded this relation in review.model.ts accordingly. 
```
@belongsTo(() => User, {keyFrom: 'user_id', keyTo: 'id'})
user_id: number;
```
However, doing so gives me `...Cannot read property 'target' of undefined...` error whenever ReviewRepository is called.
Modifying the code and its relevant parts like below does not cause any issues.
```
@belongsTo(() => User, {keyTo: 'id'})
userId: number;
```

## Comments
How can I keep 'user_id' as a valid field for Review? Any help is appreciated.

**Comment by esoodev** [comment] 2018-12-18 08:41
It seems this is related to [this issue](https://www.bountysource.com/issues/6164944-provide-a-way-to-specify-table-and-field-naming-convention-with-automigrate-autoupdate) first mentioned back in 2014.

**Comment by esoodev** [comment] 2018-12-18 09:34
Within ReviewRepository, instead of
`this.user = this.createBelongsToAccessorFor('user', userRepositoryGetter);`

I used

```
this.user = createBelongsToAccessor(
  {
    target: () => User,
    name: 'user',
    type: RelationType.belongsTo,
    source: Review,
    keyFrom: 'user_id',
    keyTo: 'id',
  },
  userRepositoryGetter,
  this,
);
```

This works for now, though not pretty. If anyone can provide an insight for moving this into Review model, it'd be much appreciated!

**Comment by JuliaRakitina** [comment] 2019-01-18 21:13
+1 there is no clear documentation to build relations. 
And by the way, I did not find anywhere in source code function createBelongsToAccessorFor

**Comment by JuliaRakitina** [comment] 2019-01-18 21:53
Please improve documentation
here https://loopback.io/doc/en/lb4/BelongsTo-relation.html  you wrote 
`call the createBelongsToAccessorFor function in the constructor of the source repository class with the relation name (**decorated relation property on the source model**) and target repository instance and assign it the property mentioned above.`

In code snippets source model decorated prorepty is **customerId** , but    
this.customer = this.createBelongsToAccessorFor(
      '**customer**', - I suppose it should be   **customerId**
      customerRepositoryGetter,
    );

**Comment by JuliaRakitina** [comment] 2019-01-18 22:20
Ok, I managed documentation example to work. But I can't configure filter just to query just simple JOIN orders and its customers ((

**Comment by shadyanwar** [comment] 2019-01-22 02:18
> ```
> this.user = createBelongsToAccessor(
> ```
Looks like the latest version of LB4 doesn't have createBelongsToAccessor

**Comment by samarpanB** [comment] 2019-04-01 13:44
For me, having this in review model
```
  @belongsTo(() => User)
  user_id: number;
```
and this in repository
```
this.user = this._createBelongsToAccessorFor(
      'user_id',
      userRepoGetter,
    );
```

works. Is there anything different you are trying to achieve ?

**Comment by b-admike** [comment] 2019-05-08 15:48
Thank you all for chiming in. I've compiled the following criteria for this issue:

# Acceptance Criteria

- [ ] Review the issue and the detailed description to reproduce locally - write a test case in our `repository` package to simulate the behaviour / cover the use case.
- [ ] Explore the proposed solutions and assess if this is a bug or a documentation update and follow up accordingly.

**Closed** 2019-07-15 14:35 UTC
Labels: 2019Q3, Relations, bug, p1
