### ISSUE TITLE
"Error [ERR_STREAM_WRITE_AFTER_END]: write after end" while app scaffolding

### ISSUE THREAD

**Issue by hbakhtiyor** [strongloop/loopback-next#1345] opened 2018-05-20 16:19 UTC
## Description / Steps to reproduce / Feature proposal
* `npm i -g @loopback/cli`
* `lb4 app`
* leaving default values

```
? Project name: myprojects
? Project description: myprojects
? Project root directory: myprojects
? Application class name: MyprojectsApplication
? Select project build settings:  Enable tslint, Enable prettier, Enable mocha, Enable loopbackBuild
   create .npmrc
   create .prettierignore
   create .prettierrc
   create README.md
   create index.ts
   create package.json
   create tsconfig.json
   create tslint.build.json
   create tslint.json
   create test/mocha.opts
   create .gitignore
   create index.js
   create src/application.ts
   create src/index.ts
   create src/sequence.ts
   create test/README.md
   create test/ping.controller.acceptance.ts
   create src/controllers/README.md
   create src/controllers/ping.controller.ts
   create src/datasources/README.md
   create src/models/README.md
   create src/repositories/README.md
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Transform.Writable.write (_stream_writable.js:292:5)
    at DestroyableTransform.ondata (/usr/lib/node_modules/@loopback/cli/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:182:13)
    at addChunk (/usr/lib/node_modules/@loopback/cli/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/usr/lib/node_modules/@loopback/cli/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/usr/lib/node_modules/@loopback/cli/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/usr/lib/node_modules/@loopback/cli/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform._transform (/usr/lib/node_modules/@loopback/cli/node_modules/mem-fs-editor/lib/actions/commit.js:34:12)
    at DestroyableTransform.Transform._read (/usr/lib/node_modules/@loopback/cli/node_modules/readable-stream/lib/_stream_transform.js:184:10)
Emitted 'error' event at:
    at Transform.onerror (/usr/lib/node_modules/@loopback/cli/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Transform.emit (events.js:182:13)
    at writeAfterEnd (_stream_writable.js:245:10)
    at Transform.Writable.write (_stream_writable.js:292:5)
    [... lines matching original stack trace ...]
    at DestroyableTransform.Transform.push (/usr/lib/node_modules/@loopback/cli/node_modules/readable-stream/lib/_stream_transform.js:148:32)

```

@loopback/cli version: 0.11.5
nodejs v10.1.0
ubuntu 18.04

## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment] 2018-05-20 17:18
Fixed by https://github.com/strongloop/loopback-next/pull/1329. It was caused by a dependency breaking change. I'll make a new release.

**Comment by raymondfeng** [comment] 2018-05-20 20:04
Please try `@loopback/cli@0.11.6`.

**Closed by raymondfeng** 2018-05-20 20:04 UTC

**Comment by hbakhtiyor** [comment] 2018-05-21 03:45
still have the issue in 0.11.6 version

```
? Select project build settings:  Enable tslint, Enable prettier, Enable mocha, Enable loopbackBuild
   create .npmrc
   create .prettierignore
   create .prettierrc
   create README.md
   create index.ts
   create package.json
   create tsconfig.json
   create tslint.build.json
   create tslint.json
   create test/mocha.opts
   create .gitignore
   create index.js
   create src/application.ts
   create src/index.ts
   create src/sequence.ts
   create test/README.md
   create test/ping.controller.acceptance.ts
   create src/controllers/README.md
   create src/controllers/ping.controller.ts
   create src/datasources/README.md
   create src/models/README.md
   create src/repositories/README.md
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end




npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bakhtiyor/.npm/_logs/2018-05-21T03_36_17_581Z-debug.log

Application todo-list is now created in todo-list.

Next steps:

$ cd todo-list
$ npm start
[2018-05-21T03_36_17_581Z-debug.log](https://github.com/strongloop/loopback-next/files/2021150/2018-05-21T03_36_17_581Z-debug.log)

```

**Comment by raymondfeng** [comment] 2018-05-21 03:48
I just tried and it works for me.

Did you run `npm i -g @loopback/cli` to upgrade?

**Comment by hbakhtiyor** [comment] 2018-05-21 04:01
```
@loopback/cli version: 0.11.6

@loopback/* dependencies:
  - @loopback/authentication: ^0.10.4
  - @loopback/boot: ^0.10.4
  - @loopback/build: ^0.6.5
  - @loopback/context: ^0.11.2
  - @loopback/core: ^0.8.4
  - @loopback/metadata: ^0.8.4
  - @loopback/openapi-spec-builder: ^0.7.4
  - @loopback/openapi-v3-types: ^0.7.4
  - @loopback/openapi-v3: ^0.10.4
  - @loopback/repository-json-schema: ^0.9.4
  - @loopback/repository: ^0.10.4
  - @loopback/rest: ^0.10.4
  - @loopback/testlab: ^0.10.4
  - @loopback/docs: ^0.7.6
  - @loopback/example-hello-world: ^0.7.4
  - @loopback/example-log-extension: ^0.9.4
  - @loopback/example-rpc-server: ^0.7.4
  - @loopback/example-todo: ^0.9.4
  - @loopback/dist-util: ^0.3.1
  - @loopback/service-proxy-proxy: ^0.4.0
  - @loopback/service-proxy: ^0.5.5
```

**Comment by raymondfeng** [comment] 2018-05-21 04:13
What do you see from the following command:

```sh
$ npm -g root
$ cd <npm-root>
$ grep rename @loopback/cli/lib/utils.js
```

You should see the following:
```
exports.renameEJS = function() {
  const renameStream = new stream.Transform({objectMode: true});
  renameStream._transform = function(file, enc, callback) {
  return renameStream;
```

**Comment by hbakhtiyor** [comment] 2018-05-21 04:32
yeah, saw it,

for second try the cli scaffold without any issues
