### ISSUE TITLE
Loopback model definition is not adding foreign key relation in database table

### ISSUE THREAD

**Issue by malek0512** [strongloop/loopback-next#3594] opened 2019-08-22 14:31 UTC
# Description/Steps to reproduce
It seems loopback is not adding foreign key constraint in Database table as per model definition. 
I am using loopback 4 for API design and data modeling. 
I am using DB2 as my database. 

# Expected result
Foreign key constraints defined in loopback 4 model, should be reflected during table creation.

**Comment by dhmlau** [comment] 2019-08-23 17:08
@malek0512, currently the FK constraints are not being added during table creation. We have the [strong relation epic](https://github.com/strongloop/loopback-next/issues/2331) covering this, and the proposal to implement it: https://github.com/strongloop/loopback-next/pull/2712. 

For now, you might want to add the foreign key constraints in the model decorator. See example: https://github.com/dhmlau/loopback4-coffeeshop/blob/master/src/models/review.model.ts#L4-L15. Hope it helps.

**Comment by dhmlau** [comment] 2019-11-28 02:26
Closing as duplicate of https://github.com/strongloop/loopback-next/issues/2332. 
@malek0512, please feel free to continue the discussion over that github issue. Thanks.

**Closed by dhmlau** 2019-11-28 02:26 UTC
