### ISSUE TITLE
Transaction support in Loopback4

### ISSUE THREAD

**Issue by lalitmcb** [strongloop/loopback-next#2411] opened 2019-02-16 15:15 UTC
- Transaction support using decorators like @Transaction
- Currently I guess it can be done programmatically
- With the transaction decorator, it will be easy to wrap up multiple calls to the repository in an atomic fashion. One way to do this is by using AOP similar to what Spring framework does, though I am not sure if loopback supports AOP.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment] 2019-02-18 09:59
Thank you @lalitmcb for opening this issue. On the second look, I think this may be a duplicate of https://github.com/strongloop/loopback-next/issues/1599

**Comment by lalitmcb** [comment] 2019-02-18 10:06
@bajtos you are right. This is indeed a duplicate. I will mark it as a duplicate of 1599.

**Comment by lalitmcb** [comment] 2019-02-18 10:07
Could not mark it duplicate. It has closed the issue. Hopefully it's the right way to do.

**Closed** 2019-02-18 10:07 UTC
Labels: Repository, feature
