### ISSUE TITLE
LB4 todo-list example gives Error: Property "todoListId" cannot  be changed!

### ISSUE THREAD

**Issue by foobarrrz** [strongloop/loopback-next#2658] opened 2019-03-28 19:56 UTC
I have cloned the project using cli "lb4 example todo-list" without modifying  anything.

After I Inserted new record to "todo-list" model, I got the response.
`{
  "id": 3,
  "title": "newToDoList",
  "color": "red"
}`

then I use id = 3 as an input for `POST /todo-lists/{id}/todos`.

```
Unhandled error in POST /todo-lists/3/todos: 500 Error: Property "todoListId" cannot be changed!
    at Object.constrainDataObject (D:\Projects\NodeJs\lbex\loopback4-example-todo-list\node_modules\@loopback\repository\dist\repositor
ies\constraint-utils.js:49:19)
    at DefaultHasManyRepository.create (D:\Projects\NodeJs\lbex\loopback4-example-todo-list\node_modules\@loopback\repository\dist\rela
tions\has-many\has-many.repository.js:21:59)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I also try to create the relation model myself following the example.
https://loopback.io/doc/en/lb4/HasMany-relation.html
But it also give the same error.

**Comment by nabdelgadir** [comment] 2019-04-02 18:00
When you're trying to do a `POST` request for `/todo-lists/{id}/todos`, there's no need to supply the `todoListId` property since it's the one that replaces `{id}` in `/todo-list/{id}/todos` e.g. `/todo-list/3/todos`. 

So I created your `TodoList` model: `{ "id": 3, "title": "newToDoList", "color": "red" }`. Then I did a `POST` request - `POST /todo-lists/3/todos` with the following body:
```json
{
  "id": 0,
  "title": "sample todo",
  "desc": "sample description",
  "isComplete": false
}
```
To which I received the following response body (and a 200 status code): 
```json
{
  "id": 5,
  "title": "sample todo",
  "desc": "sample description",
  "isComplete": false,
  "todoListId": 3
}
```

I believe when you add the `todoListId` property to your POST body, it passes [this check](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/repositories/constraint-utils.ts#L58), which is where the error comes from.

I'm thinking we can add this information to the documentation, specifically the [HasMany relation](https://loopback.io/doc/en/lb4/HasMany-relation.html) page, what do you think?

**Comment by nabdelgadir** [comment] 2019-04-05 16:56
## Acceptance Criteria
- [ ] Add a section to the [HasMany relation](https://loopback.io/doc/en/lb4/HasMany-relation.html) docs explaining the format of the request body when doing a `POST` request (need to exclude the `id` of the "parent" [Category in the current docs] entity)

**Comment by emonddr** [comment] 2019-04-11 18:26
@b-admike will look to see if there is an existing bug related to the `this check` url mentioned above.

**Comment by bajtos** [comment] 2019-04-12 14:49
Most people don't read docs. Can we instead fix the [constraint check](https://github.com/strongloop/loopback-next/blob/a396274db3ecd0486b686f4e7f0703636e57e97b/packages/repository/src/repositories/constraint-utils.ts#L58) to recognize the situation where the requested data is not changing the immutable key and don't report a false error?

**Comment by nabdelgadir** [comment] 2019-04-12 15:00
@b-admike if you can find the issue that's related to that check, we can close this issue. Otherwise, we can modify this issue to fix the constraint instead of the docs (or close this one and open a new issue).

**Comment by bajtos** [comment] 2019-04-12 15:35
I think the problem is has been described here first: https://github.com/strongloop/loopback-next/issues/1719

**Closed** 2019-04-16 07:25 UTC
Labels: 2019Q2, Docs, Examples
