### ISSUE TITLE
npm start failed cli v0.21.4 bug and workaround

### ISSUE THREAD

**Issue by Charl-Marais** [strongloop/loopback-next#1645] opened 2018-08-25 19:25 UTC
## Description 
When following the getting started tutorial the below error is generated when running npm start.

```
node_modules/@loopback/repository-json-schema/dist8/src/keys.d.ts:6:75 - error TS2307: Cannot find module '../../context/node_modules/@loopback/metadata/src/types'.

6 export declare const JSON_SCHEMA_KEY: MetadataAccessor<JSONSchema, import("../../context/node_modules/@loopback/metadata/src/types").DecoratorType>;
```

Environment used
```
Cloud9
Test Fails - NPM v5.6.0 and Node 8.11.4
Test Fails - NPM v6.4.0 and Node 10.9.0

@loopback/cli version: 0.21.4

@loopback/* dependencies:
  - @loopback/authentication: ^0.11.5
  - @loopback/boot: ^0.12.5
  - @loopback/build: ^0.7.1
  - @loopback/context: ^0.12.5
  - @loopback/core: ^0.11.5
  - @loopback/metadata: ^0.9.5
  - @loopback/openapi-spec-builder: ^0.8.5
  - @loopback/openapi-v3-types: ^0.8.5
  - @loopback/openapi-v3: ^0.12.5
  - @loopback/repository-json-schema: ^0.10.5
  - @loopback/repository: ^0.15.1
  - @loopback/rest: ^0.19.5
  - @loopback/testlab: ^0.11.5
  - @loopback/docs: ^0.16.3
  - @loopback/example-hello-world: ^0.9.5
  - @loopback/example-log-extension: ^0.11.5
  - @loopback/example-rpc-server: ^0.11.2
  - @loopback/example-todo: ^0.16.2
  - @loopback/example-soap-calculator: ^0.2.2
  - @loopback/dist-util: ^0.3.6
  - @loopback/service-proxy-proxy: ^0.4.0
  - @loopback/service-proxy: ^0.7.1
  - @loopback/http-caching-proxy: ^0.3.5
  - @loopback/http-server: ^0.3.5
  - @loopback/example-todo-list: ^0.3.2
```

## Workaround the file reference in keys.d.ts
Edit the file reference in 'node_modules/@loopback/repository-json-schema/dist8/src/keys.d.ts'.
Change the reference: 

> ../../context/node_modules/@loopback/metadata/src/types

to
 
> ../../../metadata/src/types

save and then run npm start again

**Comment by raymondfeng** [comment] 2018-08-25 19:29
Duplicate of https://github.com/strongloop/loopback-next/issues/1643

**Closed by raymondfeng** 2018-08-25 19:29 UTC
