### ISSUE TITLE
lb4 command not found

### ISSUE THREAD

**Issue by rajvarshu** [strongloop/loopback-next#3365] opened 2019-07-01 11:56 UTC
# Description/Steps to reproduce
I installed loopback version 4 with the command *npm i -g @loopback/cli* (on Mac OS).When I try to create an app using the command lb4 app its throwing me an error lb4 command not found

# Expected result
Should be able to create an app

**Comment by dhmlau** [comment] 2019-07-15 22:50
Transferred to `loopback-next` repo, because this is the repo for LB4.

**Comment by gulnurumur** [comment] 2019-07-19 08:25
i am still facing same issue

**Comment by dhmlau** [comment] 2019-07-21 21:14
It seems like we're having a hard time to reproduce the problem, so I'd like to get more information from those who ran into this issue.  Here are a few questions I have in mind (feel free to provide as much information as you have!):
1. are you running nvm for managing the node version you're running?
2. what's the node version? (run `node -v`)
3. which OS are you using?
4. Do you get `command not found` error? or other error?
5. Did you install `@loopback/cli` at the global level? i.e. `npm i -g @loopback/cli`. 

Thanks a lot.

**Comment by aneekbasu** [comment] 2019-08-09 03:52
I am getting the same problem. Please find below the answers to your questions:-

1. are you running nvm for managing the node version you're running? No
2. what's the node version? (run node -v) 10.16
3. which OS are you using? Ubuntu 18.04
4. Do you get command not found error? or other error? Command 'lb4' not found
5. Did you install @loopback/cli at the global level? i.e. npm i -g @loopback/cli. Yes

**Comment by dhmlau** [comment] 2019-08-09 14:53
@aneekbasu, do you have /usr/local/bin on your $PATH? 

I don't have an Ubuntu instance handy to try, here are a few issues that i found that might be useful. Could you please check them out? 
https://github.com/strongloop/loopback/issues/281
https://github.com/strongloop/loopback/issues/2737
https://stackoverflow.com/questions/20934343/how-to-restore-reset-npm-configuration-to-default-values

Hope it helps.

**Comment by raymondfeng** [comment] 2019-08-09 14:56
BTW, I strongly recommend that you use https://github.com/nvm-sh/nvm so that multiple node versions can be installed and isolated on your machine.

**Comment by rashtay** [comment] 2019-08-14 13:01
I am facing this issue too. `npm install -g @loopback/cli`

1. I am using NVM
2. Node: v10.15.3
3. MacOS - Mojave
4. NVM: 0.34.0

▶ lb4 app
zsh: command not found: lb4

**Comment by rashtay** [comment] 2019-08-14 13:54
I fixed the issue. I am using NVM but on digging into the issue further, I realized that though my current version is v10.15.3, my packages were getting installed in v8.x.x. I don't even have v8.x.x version installed but .npmrc was pointing to that folder. I deleted that folder, created a new npm prefix pointing to the current version and Voila, it worked.

**Comment by raymondfeng** [comment] 2019-08-14 15:58
@rashtay What was in your `.npmrc`? For `nvm`, it needs to be activated with a new terminal window  after the installation. Run `command -v nvm` to make sure.

**Comment by rashtay** [comment] 2019-08-16 13:19
@raymondfeng `nvm` was working fine. Unfortunately, it was installing global packages in the folder of a different version of the node. I deleted that folder from `.nvm` and fixed the prefix.

Now, `.npmrc` points to the right node version

`prefix=/Users/rahshett/.nvm/versions/node/v10.15.3`

**Comment by JasonMFry** [comment] 2019-09-11 14:16
This is almost certainly a PATH issue for everyone. I had `/usr/local/opt/node@8/bin` on my path for some reason. Changing it to `/usr/local/opt/node/bin` solved the issue for me. In fact, `node@8` no longer even existed.

For others, you may need to google what your path should look like for node stuff.

1. are you running nvm for managing the node version you're running? **No**
1. what's the node version? (run node -v) **v12.10.0**
1. which OS are you using? **macOS 10.14.6**
1. Do you get command not found error? or other error? **`zsh: command not found: lb4`**
1. Did you install @loopback/cli at the global level? i.e. npm i -g @loopback/cli. **Yes**

**Comment by starcrusherproductions** [comment] 2019-09-21 20:25
3. macOs 10.13.6 (17G8030)
4. Yes
5. Yes
![Screen Shot 2019-09-21 at 3 05 05 PM](https://user-images.githubusercontent.com/31316609/65378063-7ac2f600-dc81-11e9-92a2-f4364666616d.png)

![Screen Shot 2019-09-21 at 3 05 49 PM](https://user-images.githubusercontent.com/31316609/65378078-c1185500-dc81-11e9-886e-4588d7d89134.png)

It has been a while since I've touched NodeJs.  So I may have something in my terminal incorrectly listed.

**Comment by baymabruno** [comment] 2020-01-09 02:13
**Solved**

In my case, installed using the command:
```
$ sudo npm install -g @loopback/cli
```

It not worked:
```
$ lb4
-bash: lb4: command not found
```

But it worked by path:
```
$ /usr/local/opt/node/bin/lb4 app
? Project name: (projects)
```

I created an alias in .bash_profile:

```
alias lb4="/usr/local/opt/node/bin/lb4"
```

And now working fine:

```
$ lb4 app
? Project name: (bayma) 
```

nvm: **No**
node version: **v12.14.1**
macOS: **10.14.6**
error **-bash: lb4: command not found**

**Comment by nfriacowboy** [comment] 2020-01-21 19:48
@baymabruno Thanks a lot, great hint!
That happend to me because i installed nodejs on Mac with Brew command on user A now everithing i do about npm or whatever has to be done on that User and other users don't recognize the installation... well... looks like i finally have an scuse to format the MAC :)

**Comment by dhmlau** [comment] 2020-03-19 21:31
@baymabruno, thanks for your info! 
I'm now closing this issue. Thanks.

**Closed by dhmlau** 2020-03-19 21:31 UTC
Labels: CLI

**Comment by achrinza** [comment] 2021-11-20 03:21
@Robot-dev11 This is typically caused by issues in the PATH. Please check if the global NPM bin directory is in the PATH environment variable. If it is, please try either:

1. Re-installing the CLI
2. Restarting the terminal

If neither works, an alternative would be to run the CLI using `npx @loopback/cli`

**Comment by tsegayegit** [comment] 2022-05-26 21:33
export  PATH="/Users/username/.npm-global/lib/node_modules/@loopback/cli:$PATH"

**Comment by ManelkaKodithuwakku** [comment] 2023-02-16 16:28
`sudo update-alternatives --install /usr/bin/lb4 lb4 /opt/nodejs/node-v19.1.0/bin/lb4 0`

This command will be more useful to solve this problem.
You can replace nodejs path according to your system.(**/opt/nodejs/node-v19.1.0/bin**)
