### ISSUE TITLE
Using near filter in where query cause toEntity(model) bug

### ISSUE THREAD

**Issue by hosiduy** [strongloop/loopback-next#1419] opened 2018-06-12 13:52 UTC
## Description

I have Address model:

`Address extends Entity {`

    @property({
        type: 'number',
        id: true,
        generated: true,
        mysql: {
            "columnName": "m_id"
        }
    })
    mId?: number;

    @property({
        type: 'number',
        mysql: {
            "columnName": "m_belong_to_id"
        }
    })
    mBelongToId?: number;

    @property({
        type: 'GeoPoint',
        required: true,
        mysql: {
            "columnName": "m_geo_point"
        }
    })
    mGeoPoint: GeoPoint;
`}`

## Current Behavior
I try this query: 
`let nearByAddressList = await this.addressRepo.find({`

                where: {
                    and: [
                        {
                            mGeoPoint: {
                                near: location,
                                maxDistance: this.maxDistance,
                                unit: this.unit
                            }
                        }
                    ]
                }
            });
and the console show me the bug: _model.toObject() is not a function on file node_modules/@loopback/repository/dist8/src/repositories/legacy-juggler-bridge.js:160_
If I remove the _where_ filter, the code run normally. 

I checked the code and couldn't find _near_ properties on Where filter class. 
Can I use _near_ in _where_ filter on Lp4 now?
## Expected Behavior
Query run normally with _near_ in query. 

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by hosiduy** [comment] 2018-06-21 10:59
Hi @shimks,
I don't know how to create a sandbox for you to create this issue. Please help to show me how to make one. 

I did fix this problem by change the code in file: _**node_modules/dist8/src/repositories/legacy-juggler-bridge.js**_ -> `toEntity(model)` function. 

Before change: 
`toEntity(model) {`
`return new this.entityClass(model.toObject());`
`}`
My change: 
`toEntity(model) {`
`let check;`
       ` if (!model) return null;`
        `if (typeof model.toObject === 'function') {`
            `check = new this.entityClass(model.toObject());`
        `} else {`
            `check = new this.entityClass(model);`
        `}`
        `return check;`
`}`
Hope this help.

**Comment by shimks** [comment] 2018-06-21 17:44
I was able to reproduce this issue, thanks. Looks like we'll need to check whether the model we get back in `toEntity` is an instance of `model` or not. Would you like to make a PR with the change you've made?

Related to #1378.
cc @raymondfeng @bajtos

**Comment by hosiduy** [comment] 2018-06-22 04:52
Okay @shimks , I will make a PR with the change I've made.

**Comment by virkt25** [comment] 2018-09-13 15:06
@hosiduy Are you still interested / able to work on this issue. I know you forked the repo, once you have made the necessary changes you will have to Open a PR by clicking the `Pull Request` link within your forked repo. 

![image](https://user-images.githubusercontent.com/3311536/45497127-0dfb4e80-b745-11e8-8945-2ac2a03d2135.png)

**Comment by susannaHayrapetyan** [comment] 2018-11-12 13:31
Hi, any news? I'm getting the same issue. Cannot use near filter.

**Comment by hacksparrow** [comment] 2018-12-07 16:48
Please refer to https://github.com/strongloop/loopback-next/issues/1981 for updates discussions.

**Comment by bajtos** [comment] 2019-01-08 16:50
Please note that this issue does not require `GeoPoint` support to be landed. Here, we just need to fix `toEntity` method in our repository implementation.

**Closed** 2019-02-15 16:00 UTC
Labels: TOB, bug, community-contribution, good first issue

**Comment by b-admike** [comment] 2019-02-19 15:20
@hosiduy @susannaHayrapetyan We've fixed this recently in juggler. Please try upgrading your dependencies so that you get `loopback-datasource-juggler@4.5.4` and the issue should be resolved. Feel free to re-open if that's not the case.
