### ISSUE TITLE
passport-login example doesn't run

### ISSUE THREAD

**Issue by rhiwn** [strongloop/loopback-next#5457] opened 2020-05-16 12:35 UTC
trying to get the lb4 passport login example to run, having the following problem.

## Steps to reproduce

lb4 example passport-login
npm start

## Current Behavior

Error: Cannot find module './__tests__/acceptance/fixtures/mock-oauth2-social-app'
Require stack:
- C:\Users\rhiwn\loopback4-example-passport-login\node_modules\@loopback\authentication-passport\dist\index.js
- C:\Users\rhiwn\loopback4-example-passport-login\node_modules\@loopback\authentication-passport\index.js
- C:\Users\rhiwn\loopback4-example-passport-login\dist\authentication-strategies\oauth2.js
- C:\Users\rhiwn\loopback4-example-passport-login\dist\authentication-strategies\index.js
- C:\Users\rhiwn\loopback4-example-passport-login\dist\application.js
- C:\Users\rhiwn\loopback4-example-passport-login\dist\server.js
- C:\Users\rhiwn\loopback4-example-passport-login\dist\index.js
- C:\Users\rhiwn\loopback4-example-passport-login\index.js

## Expected Behavior

not the above :)

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by rhiwn** [comment] 2020-05-16 12:36
node 14.2.0

+-- @loopback/authentication@4.2.3
+-- @loopback/authentication-passport@2.1.3
+-- @loopback/boot@2.2.0
+-- @loopback/context@3.7.0
+-- @loopback/core@2.5.0
+-- @loopback/express@1.1.0
+-- @loopback/openapi-v3@3.3.1
+-- @loopback/repository@2.4.0
+-- @loopback/rest@4.0.0
+-- @loopback/rest-crud@0.8.3
+-- @loopback/rest-explorer@2.2.0
+-- @loopback/security@0.2.8
+-- @loopback/service-proxy@2.2.0
+-- @types/jsonwebtoken@8.3.9
+-- @types/lodash@4.14.151
+-- @types/passport@1.0.3
+-- @types/passport-facebook@2.1.10
+-- @types/passport-google-oauth@1.0.41
+-- @types/passport-google-oauth2@0.1.3
+-- @types/passport-http@0.3.8
+-- @types/passport-local@1.0.33
+-- @types/passport-oauth2@1.4.9
+-- body-parser@1.19.0
+-- client-sessions@0.8.0
+-- debug@4.1.1
+-- express@4.17.1
+-- express-session@1.17.1
+-- jade@1.11.0
+-- lodash@4.17.15
+-- p-event@4.1.0
+-- passport@0.4.1
+-- passport-facebook@3.0.0
+-- passport-google@0.3.0
+-- passport-google-oauth2@0.2.0
+-- passport-http@0.3.0
+-- passport-local@1.0.0
+-- passport-oauth2@1.5.0
+-- path@0.12.7
`-- tslib@1.13.0

**Comment by achrinza** [comment] 2020-05-16 14:07
Duplicate of #5380

**Closed by achrinza** 2020-05-16 14:07 UTC
Labels: bug
