### ISSUE TITLE
loopback-next-hello-extension sample package

### ISSUE THREAD

**Issue by Setogit** [strongloop/loopback-next#532] opened 2017-08-22 13:33 UTC
purpose: example code come along with extension blog post: task #524
refactor `loopback-next-hello-world` so that the two work seamlessly.

**Comment by bajtos** [comment] 2017-08-23 15:57
In this sprint, as part of #525, @virkt25 will be working on `loopback-next-hello-extension` project aiming at new extension developers.

I think this issue is mostly a duplicate of #525, but let's keep it open in case the blog post have different needs and some tweaking of loopback-next-hello-extension is needed.

**Comment by dhmlau** [comment] 2017-10-13 17:05
closing as duplicate of #525.
cc @virkt25

**Closed by dhmlau** 2017-10-13 17:05 UTC
Labels: p1
