### ISSUE TITLE
Id deleted on update on MongoDB

### ISSUE THREAD

**Issue by jdumont0201** [strongloop/loopback-next#3267] opened 2019-06-28 09:44 UTC
## Steps to reproduce
Create a new project with CLI
Using CLI, add model, MongoDB datasource, repository and CRUD controller. Add this route to controller

```ts
@get('/mymodels/test'})
async test(): Promise<void> {
  const data={name:"title"}
  const p:Mymodel=await  this.mymodelRepository.create(data)
  console.log("Saved entity",p)

  p.name="modified title"
  await this.mymodelRepository.update(p)
  console.log("Modified entity",p)
  return 
}
```

## Current Behavior
On MongoDB, the entity had an id after _create_, but looses it after _update_. Result is 
```
Saved entity Mymodel { name: 'title', id: 5d15d7c25ae6d1605cc0b0dc }
Modified entity Mymodel { name: 'modified title' }
```
In memory DB, result is fine:
```
Saved entity Mymodel { name: 'title', id: 5d15d7c25ae6d1605cc0b0dc }
Modified entity Mymodel { name: 'modified title', id: 5d15d7c25ae6d1605cc0b0dc  }
```

In Postgres, result is fine as well (tested with numeric ids):
```
Saved entity Mymodel { name: 'title', id: 1 }
Modified entity Mymodel { name: 'modified title', id: 1 }
```
(We are just talking about the runtime variable. The value in db maintains a valid id. )

## Expected Behavior
id shouldnt be deleted from updated entity 

## Link to reproduction sanbox
https://github.com/jdumont0201/loopback-id-issue-demo
(Just edit the datasource json to plug to a MongoDB, couldnt share connection details here)

## Versions
Win10
@loopback/cli 1.17.1
@loopback/core": 1.8.4
loopback-connector-mongodb": "^5.0.0
loopback-connector-postgresql": "^3.7.0

## Acceptance criteria

- [ ] Fix the problem in loopback-connector-mongodb
- [ ] Add a new test to https://github.com/strongloop/loopback-next/tree/master/packages/repository-tests to ensure consistent behavior across all connectors. 
- [ ] if the fix is in mongoDB connector, also add a test in that connector

**Comment by bajtos** [comment] 2019-06-28 11:44
@hacksparrow since you have been working with MongoDB recently, would you like to take a look at this issue yourself?

**Comment by hacksparrow** [comment] 2019-06-28 13:07
Confirming it is a bug. 

Also confirming, it is reproducible in `loopback-connector-mongodb` 4.2.0` and `3.9.2`.

Thanks for reporting @jdumont0201. I will start fixing it.

**Comment by bajtos** [comment] 2019-07-02 13:40
@hacksparrow besides fixing the problem in our MongoDB connector, please add a new test to https://github.com/strongloop/loopback-next/tree/master/packages/repository-tests to ensure consistent behavior across all connectors. I'll update acceptance criteria in the issue description accordingly.

**Comment by dhmlau** [comment] 2019-09-21 21:03
Would like to get an estimate on the effort to add extra tests so that we can get it done and close this issue. Thanks.

**Comment by hacksparrow** [comment] 2019-12-19 10:17
Hmm, I fixed this in July - https://github.com/strongloop/loopback-connector-mongodb/commit/c5200e26498ffcd2b560e3a3cf8ba2795bbf603f.

Use the latest version of `loopback-connector-mongodb`.

**Closed by hacksparrow** 2019-12-19 10:17 UTC
Labels: bug, db:MongoDB
