### ISSUE TITLE
Problem with where clause

### ISSUE THREAD

**Issue by kogutu** [strongloop/loopback-next#2328] opened 2019-02-01 21:49 UTC
## Description / Steps to reproduce / Feature proposal
Hello, I have problem with where clause on LB4. When I use JSON as discribe where clause,  LB4 return undefined value (I check on controller filter value) , Explorer return request url without filter query parameters.

Ex. this below query is working 
`{
  "where": "1"
 }`
return this url (on explorer): http://localhost:3100/test?filter[where]=1 
and this value on controller:
`{ where: '1' }
or
{ "where": '1' }
`

But when i try use correctly query 
`{ where: {id:"1"} }
or
{ "where": {"id":"1"} }
`  
LB4 return: http://localhost:3110/test and undefined value on controller

I use graphql but this problem there is also exist when i try use where clause on explorer. 

On this place I observe filter query:

`  @get('/test', {
    responses: {
      '200': {
        description: 'Array of test model instances',
        content: {
          'application/json': {
            schema: {type: 'array', items: {'x-ts-type': Test}},
          },
        },
      },
    },
  })
  async find(
    @param.query.object('filter', getFilterSchemaFor(Test)) filter?: Filter,
  ): Promise<Test[]> {
    **console.log(filter);**
    return await this.testRepository.find(filter);`

**Please tell me what I am doing wrong?**

**Comment by raymondfeng** [comment] 2019-02-01 22:00
Duplicate of https://github.com/strongloop/loopback-next/issues/2208#issuecomment-453005884

**Closed by raymondfeng** 2019-02-01 22:00 UTC
