### ISSUE TITLE
Can not get app.static() to serve

### ISSUE THREAD

**Issue by SephReed** [strongloop/loopback-next#5136] opened 2020-04-17 20:45 UTC
## Steps to reproduce

```
export class MyApi extends RestApplication {

  constructor() {
    this.static('/', path.join(__dirname, '../../public'));
  }
}
```

## Current Behavior

NotFoundError
404 Endpoint "GET /" not found.

## Expected Behavior

Maybe internal server error, or the index file at that location

## Additional information
I'm not using any mixins, nor am I able to without breaking the project.

## Related Issues
n/a

**Comment by dhmlau** [comment] 2020-04-18 01:50
@SephReed, if you're using the same structure as a LB app scaffolded using the CLI, the path should be `../public` instead. i.e.

```
    this.static('/', path.join(__dirname, '../public'));
```

**Comment by SephReed** [comment] 2020-04-20 20:55
I'm not using the scaffolding or CLI.

**Comment by achrinza** [comment] 2020-04-21 02:55
It is strongly recommended to use the CLI to scaffold the application to make the issue more reproducible. Otherwise, a minimum-reproducible sandbox would be useful so that we can see the bigger picture (e.g. the structure of the application).

**Comment by SephReed** [comment] 2020-04-22 16:51
I think this should do it.

```
class MyApi extends RestApplication {

  constructor() {
    this.static('/', path.join(__dirname, '../../public'));
  }
}

const app = new MyApi();
app.start();

const url: string = app.restServer.url || '';
console.log(`running at ${url}`);
```

**Comment by dougal83** [comment] 2020-04-22 17:00
@SephReed Just in case you were unaware, there is an [express example](https://github.com/strongloop/loopback-next/tree/master/examples/express-composition).  If that helps in future.

**Comment by SephReed** [comment] 2020-04-22 17:06
This example project is a bit bloated.  I'm avoiding mixins, and anything that isn't a requirement for a functional api.

**Comment by achrinza** [comment] 2020-04-23 03:28
> 
> 
> I think this should do it.
> 

The code seems to be incomplete and non-functional. A GitHub repo as the reproduction sandbox would be incredibly useful to help us understand the bigger picture.

Since we do not know the file structure of the application, we have to make some assumptions.

I've created a test repo with the bare-minimum to create a working, functional API, please take a look:

https://github.com/achrinzatest/gh-loopback-next-issue-5136

There seems to be a misunderstanding on how `__dirname` works. This resource may be helpful:
- https://stackoverflow.com/questions/9874382/whats-the-difference-between-process-cwd-vs-dirname

**Comment by SephReed** [comment] 2020-04-23 16:06
Huh.  So your example is working?  What kind of error do you get if you mess up the path for your `public/index` file?  This is exactly what I was using and was getting a 404 GET response without any server errors.

**Comment by achrinza** [comment] 2020-04-23 23:27
@SephReed Yup, pointing to a nonexistent directory will cause a 404 error.

With the limited info, my recommendation to debug the issue is to print the resulting path to the console (e.g. `console.log(path.join(__dirname, '../../public'));`) to make sure that the value of `__dirname` is consistent with what's expected.

**Comment by achrinza** [comment] 2020-05-03 00:43
Hi @SephReed, does the issue still persist?

**Comment by SephReed** [comment] 2020-05-05 17:39
I'm sorry.  I'd already hacked a solution together by the time this response had come through.  I haven't attempted this yet.

**Comment by achrinza** [comment] 2020-05-08 15:01
Glad you were able to find a solution! To keep the issues backlog clean, let's close this issue. If there's the problem arises again, we can re-open it.

**Closed by achrinza** 2020-05-08 15:01 UTC
Labels: Core, question
