### ISSUE TITLE
Bad update index.ts file on "lb4 discover" command 

### ISSUE THREAD

**Issue by JacquesBonet** [strongloop/loopback-next#5193] opened 2020-04-22 08:51 UTC
## Steps to reproduce

When we launch,  for a second  (3,4,...) time the command "lb4 dicover"

The file index.ts is not update correctly.

## Current Behavior

The path file of the models generated are always put at the end of the file content, without checking if a pathfile already exist.

## Expected Behavior

Replace the existing pathfile if it exist than append new entries systematically

**Comment by dhmlau** [comment] 2020-04-22 14:55
@JacquesBonet, I'm trying to reproduce this problem but failed. Perhaps you could point what I've below is different from yours? Thanks. Note: I'm using postgresql.
1. Run `lb4 discover` to discover `customer`. 
2. Run the above step again. 

Result: I got `identical src/models/customer.model.ts` and index.ts in `models` folder wasn't changed.

3. Run `lb4 discover` to discover `order` (to make sure there are more than one entries in index.ts) 
Result: index.ts got updated with `order.model.ts`  which is as expected.

4. Edit customer.model.ts
5. Run `lb4 discover`  on `customer`
Result: Got `conflict src/models/customer.model.ts`. But `index.ts` doesn't have duplicate entries.

**Comment by JacquesBonet** [comment] 2020-04-29 10:50
I made it again.

``:> lb4 discover``

model/index.ts file content (after sort)

``
export * from './app-feed-back.model';
export * from './app-feed-back.model';
export * from './container.model';
export * from './device.model';
export * from './device.model';
export * from './event-speaker.model';
export * from './event-speaker.model';
export * from './event-translation.model';
export * from './event-translation.model';
export * from './event.model';
export * from './event.model';
``

**Comment by JacquesBonet** [comment] 2020-04-30 02:19
If I modify only one model, there is no problem.

**Comment by dhmlau** [comment] 2020-06-16 02:37
@JacquesBonet, sorry about the late reply. I tried to reproduce the problem again but couldn't. Not sure what's the key to reproduce. 

After I ran `lb4 discover` on multiple tables and edit all the models, I ran the command again. Here is my output:
```
$ lb4 discover
? Select the connector to discover ds
? Select the models which to discover todolist, todo, todolistimage
? Select a convention to convert db column names(EXAMPLE_COLUMN) to model property names: Camel case (exampleColumn) (R
ecommended)
 conflict src/models/todolist.model.ts
? Overwrite src/models/todolist.model.ts? overwrite
    force src/models/todolist.model.ts
 conflict src/models/todo.model.ts
? Overwrite src/models/todo.model.ts? overwrite
    force src/models/todo.model.ts
 conflict src/models/todolistimage.model.ts
? Overwrite src/models/todolistimage.model.ts? overwrite
    force src/models/todolistimage.model.ts
   update src/models/index.ts
   update src/models/index.ts
   update src/models/index.ts

Models TodolistTodoTodolistimage was created in src/models/
```

The `index.ts` doesn't have duplicate entries: 
```
export * from './todolist.model';
export * from './todo.model';
export * from './todolistimage.model';
```

There may not be much changes in the model discovery code in the past few months, but it might worth to try the latest CLI? Thanks.

**Comment by dhmlau** [comment] 2020-08-24 01:16
@JacquesBonet, I wasn't able to reproduce this problem. Given that it's been 4 months that the problem was first reported, I'd like to close this issue as non-reproducible. If you still encounter this issue, please feel free to ping here or open a new issue. Thanks.

**Closed by dhmlau** 2020-08-24 01:16 UTC
Labels: CLI, bug, needs clarification
