### ISSUE TITLE
Getting response header from REST connector.

### ISSUE THREAD

**Issue by zongzw** [strongloop/loopback-next#2645] opened 2019-03-26 08:13 UTC
If the external web app response the things via response headers instead of the response body, is there any way to get them?

Seems loopback only hands over response body to lb4-service, the header is omitted.

**Comment by bajtos** [comment] 2019-03-29 07:56
Closing as a duplicate of https://github.com/strongloop/loopback-connector-rest/issues/131

**Closed by bajtos** 2019-03-29 07:56 UTC
