### ISSUE TITLE
Errors on fresh Install

### ISSUE THREAD

**Issue by wushan** [strongloop/loopback-next#2469] opened 2019-02-25 09:22 UTC
## Description / Steps to reproduce / Feature proposal
when creating new apps or downloading an example with `lb4 app` `lb4 example`, these errors appears during the install progress. and off course the app can't `start` correctly after the errors below.
## Current Behavior
Terminal Errors:
```
> lb4 example hello-world
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm ERR! path /private/var/www/loopback4-example-hello-world/node_modules/highlight.js/tools/build.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/private/var/www/loopback4-example-hello-world/node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
## Expected Behavior
Installs and run the app correctly.

**Comment by yoan-aln** [comment] 2019-02-25 10:16
I have the same problem. 
This would come from the last release of highlight.js and no loopback. 
If someone has a tip otherwise it will wait until highlight.js fixed that.

**Comment by kumardasanand28** [comment] 2019-02-25 10:26
I also have the same issue faced now due to highlight.js

**Comment by SharonItz** [comment] 2019-02-25 11:45
I have the same issue.

**Comment by vacrozet** [comment] 2019-02-25 13:41
@loopback/build !! I have the same Error.

**Comment by jannyHou** [comment] 2019-02-25 15:05
Hi everyone, can you post the node version? 
Have you tried run it with node 10 and above? I am on `v10.15.1` and everything looks good.

**Comment by vacrozet** [comment] 2019-02-25 15:08
Add at your devDependencies or dependencies --> "highlight.js": "9.14.2"
For resolve temporary that issue.

**Comment by raymondfeng** [comment] 2019-02-25 15:38
Duplicate of https://github.com/highlightjs/highlight.js/issues/1984

**Comment by raymondfeng** [comment] 2019-02-25 22:35
Please run `npm i -g @loopback/cli` and try again.

**Closed by raymondfeng** 2019-02-25 22:35 UTC
