### ISSUE TITLE
How to use log-extension in my application? Can any one help me

### ISSUE THREAD

**Issue by sureshkodur** [strongloop/loopback-next#2936] opened 2019-05-22 06:18 UTC
## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment] 2019-05-22 13:49
@sureshkodur, did you have a chance to look at this tutorial? https://github.com/strongloop/loopback-next/tree/master/examples/log-extension#tutorial. 
If yes, please describe the problem you're running into. Thanks.

**Comment by sureshkodur** [comment] 2019-05-23 06:20
@dhmlau , Yes. I'm confused how to use this in my application. I want to log all api requests. Can you please help me. How to implement in my application. Thank you in advance

**Comment by vjtc0n** [comment] 2019-05-26 05:49
@sureshkodur Hello,
I think after you add LogMixin to application.ts, you can use the log in sequence.ts.
Just like authentication and authorization example on the doc :)
Cheers.

**Comment by sureshkodur** [comment] 2019-05-28 05:55
@vjtc0n , Can you explain or share the code snippet in sequence.ts?

**Comment by dhmlau** [comment] 2019-05-28 17:19
FYI - @raymondfeng has a PR to add an example greeting app on top of greeter extension: https://github.com/strongloop/loopback-next/pull/2941

**Comment by dhmlau** [comment] 2019-06-18 15:54
The above PR has merged and the docs contain the changes.
Please see the [example page](https://loopback.io/doc/en/lb4/Examples.html) for the `greeter-extension` and `greeter-app` as reference. Thanks.

**Closed by dhmlau** 2019-06-18 15:54 UTC

**Comment by sureshkodur** [comment] 2019-10-17 10:16
Hi, Can anyone help me how to implement log extension in my app?

**Comment by ochemerys** [comment] 2019-12-02 18:22
Hi,
steps to reproduce:
1. `$ lb4 example log-extension`
2. `$ lb4 app getting-started` 
and select all default settings
3. `$ cd getting-started`
4. `$ npm install ../loopback4-example-log-extension`
5. modified **application.ts** file accordingly to instructions https://github.com/strongloop/loopback-next/tree/master/examples/log-extension (**actually I was not able to follow instructions directly**)
`import {LogMixin, LOG_LEVEL} from '@loopback/example-log-extension';`
...
`export class GettingStartedApplication extends LogMixin(
  BootMixin(ServiceMixin(RepositoryMixin(RestApplication))),
)`
...
added 
`this.logLevel(LOG_LEVEL.ERROR);`
after
`this.projectRoot = __dirname;`
6. modified ping.controller.ts
`import {log, LOG_LEVEL} from '@loopback/example-log-extension';`
...
`  // Map to `GET /ping`
  @get('/ping', {
    responses: {
      '200': PING_RESPONSE,
    },
  })
  @log(LOG_LEVEL.DEBUG)
  ping(): object {`
7. `npm start`
8. `curl -X GET "http://[::1]:3000/ping" -H "accept: application/json"`
and response is
`{"greeting":"Hello from LoopBack","date":"2019-12-02T18:05:37.436Z","url":"/ping","headers":{"host":"[::1]:3000","user-agent":"curl/7.64.1","accept":"application/json"}}`

I'm expecting to see some logging info in terminal where app is started, but nothing happens.
Do I do something wrong?
or 
Did I missed something in code?
or 
Are my expectations wrong? 
or
**Is example actually working?**

**Comment by sureshdmavericks** [comment] 2019-12-03 10:08
@ochemerys , I'm also want like this. Please help us

**Comment by ochemerys** [comment] 2019-12-04 22:53
@sureshkodur The issue is resolved here:
https://github.com/strongloop/loopback-next/issues/4238

**Comment by raymondfeng** [comment] 2019-12-04 23:28
FYI - the longer term solution is proposed her for logging - https://github.com/strongloop/loopback-next/pull/4117

**Comment by ochemerys** [comment] 2019-12-05 16:28
@raymondfeng, Can you please publish it on npm for easy use?
currently
`npm install --save @loopback/extension-logging`
output is
`
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@loopback%2fextension-logging - Not found
npm ERR! 404 
npm ERR! 404  '@loopback/extension-logging@latest' is not in the npm registry.
`

Thank you
