### ISSUE TITLE
docs: Add missing gaps in Context concept page

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-next#651] opened 2017-10-16 18:22 UTC
## Overview
On loopback.io under the Concepts section, `Context` needs to be modified to explain Bindings and add a server-level context section.

Link to Concepts Overview Page: http://loopback.io/doc/en/lb4/Concepts.html

## Acceptance Criteria
- [x] Include a detailed explanation of Bindings
  - [x] .to
  - [x] .toClass
  - [x] .toProvider
  - [x] .inScope
- [x] Add Server-level context section

**Comment by bajtos** [comment] 2017-10-17 15:38
> Include a detailed explanation of Bindings

For Beta, just add a short sentence pointing people to our API docs: http://apidocs.strongloop.com/

**Comment by dhmlau** [comment] 2017-10-27 14:45
@kjdelisle , since the PR has landed, is it good to close?

**Comment by dhmlau** [comment] 2017-10-30 15:17
Confirmed with @kjdelisle, good to close.

**Closed by dhmlau** 2017-10-30 15:17 UTC
Labels: LoopBackNext-beta, p1, review, team-apex
