### ISSUE TITLE
Loopback request fields filter (unexpected behavior)

### ISSUE THREAD

**Issue by ilyesbrh** [strongloop/loopback-next#6512] opened 2020-10-06 18:46 UTC
## Steps to reproduce

**when using query filter**
 
```
{
    "include": [
        {
            "relation": "cases",
            "scope": {
                "fields": {
                    "id": false,
                    "isSaved": false,
                    "name": true,
                }
            }
        }
    ]
}
```

## Current Behavior

**cases** relation wont show because **id : false**

if you set **id : true** it will show **cases** relation in results

## Expected Behavior

setting **id : false** should only hide **id** field not the hole object

**Comment by dhmlau** [comment] 2020-10-07 14:52
@agnes512, could you please take a look? Thanks.

**Comment by agnes512** [comment] 2020-10-12 20:06
This is true. I don't know how your model defined, but my guess is `id` is the pk/fk of the relation `case`. Because the source key was **excluded** when fetching data from the db, the inclusion resolver is not able to find it related models. That's why it fails to include.
From what it is described in [Fields filter](https://loopback.io/doc/en/lb4/Fields-filter.html):
> Notice that fields clause is to include/exclude the result from the database, e.g if you would like to check password for users, the above example would fail as password is undefined. If you need the property and also want to hide it from the response, set it as a hidden property in the model definition.

the primary and foreign keys should be included in `fields` to make sure the relation works as expected. You may want to check out the `hidden property` to hide the id property. 

I am closing the issue as it is not a bug. Feel free to reopen the issue or ask questions if anything is not clear. Thanks.

**Closed by agnes512** 2020-10-12 20:06 UTC
Labels: Repository, bug
