### ISSUE TITLE
Putting it all together...

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#112] opened 2017-04-08 02:23 UTC
Here is a minimal but somewhat complete example for a few features / tweaks that I'd like to see. It includes everything that I can think of as fundamental building blocks...

 - Creating an `Application`
 - Defining a `Model`
 - Defining / Using a `Collection`
 - A `Controller` and method (with decorator sugar)
 - How decorators can easily pass references to the `app` (see: `@app.controller` and other examples
 - Hooks
 - Named hooks
 - Hook ordering / dependencies
 - Express middleware support
 - Dependency injection (see `@app.collection`, `@inject('currentUserId')`)

TBD:

 - `import {app} from 'app'` (ugly, global-ish)
- No simple `app.start()` / `Server` usage (missing)

```ts
// app.ts
import {Application} from 'loopback';
export const app = new Application();
```

```ts
// todo.ts
import {app} from 'app';

@app.model
class Todo {
    txt : string;
    done : boolean = false;
}
```

```ts
// todo.controller.ts
import {Collection} from 'loopback';
import {app} from 'app';
import {Todo} from 'todo';

@app.controller
class TodoController {
    @app.collection
    todos : Collection<Todo>;

    @app.get('/my/todos')
    list(@app.inject('currentUserId') uid) : Collection<Todo> {
        return this.todos.find({where: {owner: uid}});
    }
}
```

```ts
// hooks.ts
import {app} from 'app';

@app.bind('currentUserId')
function getUserId(ctx : Context) : string {
    const token = ctx.get('accessToken');
    if (token) return token.userId;
}

@app.bind('accessToken')
getToken(ctx : Context) : AccessToken {
    return new Token(ctx.get('req'));
}

@app.before('controller.*.list')
function beforeAll(ctx : Context) {
    console.log('before', ctx.get('method.name')); // "before list"
}

@app.before('controller.**', {express: true})
require('morgan')(); // express middleware also supported

// name your hooks for more control
@app.after({name: 'timestamp', match: 'controller.**'})
function afterAll(ctx : Context) {
    const result = ctx.get('result');
    ctx.bind('result').to({
        timestamp: Date.now(),
        data: result
    });
}

// ensure a hook runs after another hook
@app.after({ensure: ['timestamp'], match: 'controller.*'})
function end() {
    console.log('last hook!')
}
```

**Comment by bajtos** [comment] 2017-04-18 14:15
My main concern is how the proposed `app.*` decorator design work with 3rd party components that want to use decorators too (e.g. to contribute a Controller)? I think `app.*` decorators are also creating a dependency cycle - an app requires some controllers, and each controller requires the `app` to actually register itself via decorators.

What I would like to see is a small module providing LoopBack decorators, a module that can be added as a dependency of 3rd party components. See my work in https://github.com/strongloop/loopback-next/pull/54 for a straw-man proposal.

When we have that module, then I guess we can implement `@app.controller` as a shortcut for `@api()` plus registration with the app, if we find it as a useful thing to do.

> can have a similar JS API and TS api

This is true for decorators exported by a small package too. (Of course, we will need some sort of a loaded/bootstrapper to register classes/functions with the `app`, as has been discussed above.)

```ts
const meta = require('@loopback/metadata');

// JavaScript
meta.after('*')(myHook);
function myHook() {
}

// TypeScript
@meta.after('*')
function myHook() {
}

// An example showing how 3rd party components
// can have control over what's registered with the app
module.exports = setupComponent(app) {
  app.bind(SOMETHING, myHook);
};
```

> It makes it easier to implement decorators since they will have direct reference to the Context

That's a good point for things like before/after hook.

I am not sure if it's valid for metadata at class/method/arguments level. AFAIK, such decorators usually store metadata via [Reflection API](https://github.com/rbuckton/reflect-metadata). I suppose we could use `app.bind` instead of Reflection, but I think the solution can become ugly:

```ts
// app.bind(`${class}.${method}.arg${argIndex}`)
app.bind('UserController.login.arg0')
```

> a lot of files will need to import various decorators:

I don't see any issue here, I think `import * as <X> from <Y>` works well.

```ts
// i'd prefer
import {app} from 'app';

// IMO, that's as easy as
import * as meta from '@loopback/metadata';
```

> it makes it easier for you to add your own decorators that compose others

```ts
class MyApplication extends Applications {
  /* usage:
   @app.todoRepo
   public repo : Repository<Todo>;
  */
  todoRepo() {
    return this.repository<Todo>();
  }
}
```

I am afraid your example does not work as intended. The return value of a property-level decorator is used as "the Property Descriptor for the member" in ES6+ and it's discarded in ES5 target. See https://www.typescriptlang.org/docs/handbook/decorators.html#property-decorators

IIUC, it is not possible to write a decorator that would "inject" a default value for property. Quoting from TS Handbook (see my last link, emphasis is mine):
> there is currently no mechanism to describe an instance property when defining members of a prototype, and **no way to** observe or **modify the initializer for a property**. As such, a property decorator can only be used **to observe that a property of a specific name has been declared** for a class.

From my experience so far, decorator implementations have special non-intuitive design that requires different thinking compared to how a typical application code is written. I think that as a result, shortcuts like your `app.todoRepo` will be implementable only rarely.

Having said that, the goal of making it easy to create own decorators is a noble goal to keep in mind. Here is how I would implement your `todoRepo` decorator:

```ts
// metadata.ts
import inject from 'loopback/metadata';
export function todoRepo() {
  return inject("repositories.Todo");
}

// TodoController.ts
import {todoRepo} from './metadata'

class TodoController {
  // property-based injection
  @todoRepo
  public repo: Repository<Todo>;  

  // I would personally choose constructor-level injection instead
  constructor(@todoRepo public repo: Repository<Todo>) {
  }
}
```

**Comment by jonathan-casarrubias** [comment] 2017-04-18 15:16
Hey guys, I'm glad this discussion is taking place... I had the feeling for a long time that the LB2/3 Models were old and needed a much better interface, I tried to solve that using the model decorator within FireLoop, but I was only trying to make a better interface of the current model approach.

Also, I always had the feeling that the controllers were an important missing part of the framework.

Now that we are discussing and trying both problems I would really like to jump in the discussion and talk about what would be my expectations from a controller


````js
import { Controller,  Remote, Authenticate, Inject  } from '@loopback/core';
import { Filter } from '@loopback/models';
import { Todo } from 'app/models';

@Controller({
  base: 'todos'
})

export class TodoController {

    constructor(@Inject(Todo) public todo) {}

    @Remote.get() // [GET] /todos
    @Authenticate 
    find(filter: FilterInterface): Promise<Todo[]> {
      return this.todo.find(filter);
    }

    @Remote.get('something-else') // [GET] /todos/something-else
    somethingElse(filter: FilterInterface): Promise<Todo[]> {
      // Do some logic in here
    }
}
````

I'm just adding a trivial example, of course we might want extend from a base controller that provides CRUDs by default. something like:

````js
import { Controller, BaseController, Remote, Authenticate, Inject  } from '@loopback/core';
import { Filter } from '@loopback/models';
import { Todo } from 'app/models';

@Controller({
  base: 'todos'
})

export class TodoController extends BaseController{

    constructor(@Inject(Todo) public todo) {}

    @Remote.get('something-else') // [GET] /todos/something-else
    somethingElse(filter: Filter): Promise<Todo[]> {
      // Do some logic in here
    }
}
````

Not totally sure about the implications of having the app.* approach, it sounds like that way we would not import so many decorators our-selves but my concern is that not all the decorators might be required for every controller, in some cases it is even possible that the app would have loaded much more decorators than the actual needed for small apps, so maybe letting us decide which decorators should be available would help on that issue.

That is all I can think for now, I'll stay around to see what the progress on this is, I'm very interested to be the controller one of the new greatest features on LB4.

Cheers
Jon

**Comment by bajtos** [comment] 2017-07-18 16:55
Closing this issue. The results of the discussion were captured in wiki pages.

**Closed by bajtos** 2017-07-18 16:55 UTC
Labels: epic.lbnext-example, LoopBackNext-beta, needs-discussion
