### ISSUE TITLE
Example Create Middleware 

### ISSUE THREAD

**Issue by kawasaki23Ven** [strongloop/loopback-next#2061] opened 2018-11-20 19:06 UTC
Hi, I need a Middleware example to all routes of my app.

Example: Verify CORS, Headers,etc. 

I would greatly appreciate your help.

**Comment by codejamninja** [comment] 2018-11-22 14:00
I really would like to know how to add middleware. I can't figure it out.

**Comment by bajtos** [comment] 2018-11-22 14:01
Closing as a duplicate of https://github.com/strongloop/loopback-next/issues/2035.

BTW, CORS middleware is automatically enabled by LB4, see https://loopback.io/doc/en/lb4/Server.html#customize-cors

In general, we are trying to move away from Express middleware and use the concept of a [Sequence of actions](https://loopback.io/doc/en/lb4/Sequence.html) and [Dependency Injection](https://loopback.io/doc/en/lb4/Dependency-injection.html) to drive the request processing flow.

Could you please be more specific about "Headers" scenario you mentioned in the issue description? What are you trying to achieve? For example, to access a specific request header from your controller method, I would recommend to define a `Provider` class. It would really help if you could give us a specific example that we could use to drive the docs.

**Closed by bajtos** 2018-11-22 14:01 UTC
Labels: Examples

**Comment by codejamninja** [comment] 2019-06-21 10:01
I wrote a component that lets you register express middleware in the sequence.

https://github.com/codejamninja/lb4-middleware
