### ISSUE TITLE
The key authentication.currentUser was not bound to any value (mixed auth/noauth controller)

### ISSUE THREAD

**Issue by joeytwiddle** [strongloop/loopback-next#1275] opened 2018-04-24 11:52 UTC
I have started from a generated server and tried following the [authentication instructions](https://github.com/strongloop/loopback-next/tree/master/packages/authentication).

But whenever I try to access ~an authenticated~ a route, I see this error:
```
Unhandled error in GET /whoami: 500 Error: The key authentication.currentUser was not bound to any value.
```
~Where is the CURRENT_USER provider supposed to get added to the registry?~ ☑️ Answered below.

~Is there an example server with working authentication anywhere?~ ☑️ Got one below. Thanks virkt25!

Another thing to note is that the `verify()` function in MyAuthStrategyProvider never gets called. Although it does get called in virkt25's example, so I need to work out what the difference is between our projects.

**Comment by joeytwiddle** [comment] 2018-04-25 05:36
I found [basic-auth.acceptance.ts](https://github.com/strongloop/loopback-next/blob/master/packages/authentication/test/acceptance/basic-auth.acceptance.ts) but the setup is a bit different.

Notably I cannot do this to my app:
```js
app.component(RestComponent);
```
because:
```
Cannot start the application. Error: RestApplication does not support multiple servers! To create your own server bindings, please extend the Application class.
    at TradingServerApplication.server (.../node_modules/@loopback/rest/dist/src/rest.application.js:57:19)
````

**Comment by virkt25** [comment] 2018-04-25 14:34
Hi @joeytwiddle , 

I created an app using the latest `lb4` CLI and followed the instructions in the @loopback/authentication README and everything seems to be working fine for me. Here's my test app so you can spot anything you might be doing different. 

https://github.com/virkt25/lb4-auth-test

If everything you're doing is the same and it's still not working for you can you please provide a reproduction sandbox. Thanks and hope this helps :)

**Comment by shimks** [comment] 2018-04-25 14:35
Taking a quick look, it seems like `AuthenticationBindings.CURRENT_USER` isn't bound to the app context. Have you made sure to register the `AuthenticationComponent` to the app context?

**Comment by joeytwiddle** [comment] 2018-04-26 03:33
Thanks so much! I will look compare and feedback.

Perhaps your demo repository could be linked or imported into the loopback docs, as an example for others. (If the authentication API is stable.)

**Comment by joeytwiddle** [comment] 2018-05-03 11:01
OK, so the reason I was confused is this: my controller has some routes which require authentication, and some which do not (public access).

But it seems if my controller uses `AuthenticationBindings.CURRENT_USER` then I **must** use the `@authenticate` decorator on all its routes. 

If I leave `@authenticate` off one of the routes, then when that route is accessed it will throw:
```
Error: The key authentication.currentUser was not bound to any value.
```

Does that seem like expected behaviour to you guys?

**Comment by joeytwiddle** [comment] 2018-05-16 04:03
Regarding 3, my approach was to create two new auth strategies:

- NoAuthStrategy would always act like authentication had succeeded, and would always resolve, but it would resolve with `user: null`

  That would allow for routes which do not require authentication, but could live within a controller which uses the AuthenticationBindings.

- OptionalAuthStrategy would be an adapter: it would accept a normal auth Strategy in its constructor. At auth time, it would try the provided strategy, but if that failed, it would still resolve, just with `user: null`.

  That would allow for routes which would run with or without an authenticated user.

Unfortunately I haven't had time to complete the module. You are very welcome to use [the code](https://github.com/joeytwiddle/lb4-auth-test/commits/wip-noauth-strategy) or just use the idea.

**Comment by shimks** [comment] 2018-05-16 15:49
I'm going to be investigating this.

Our intended use case was that users wouldn't have to decorate routes that don't require authentication.

Thanks for bring this up!

**Comment by bajtos** [comment] 2018-06-25 12:58
Closing in favour of #1334

**Closed by bajtos** 2018-06-25 12:58 UTC
