### ISSUE TITLE
Unable to Explore API (generated OpenAPI spec is not valid)

### ISSUE THREAD

**Issue by Vandivier** [strongloop/loopback-next#1531] opened 2018-07-15 00:18 UTC
## Description / Steps to reproduce / Feature proposal

1. `lb4 example`, then pick the Todo app.
2. install it and get it running.
3. visit http://localhost:3000/openapi.yaml
4. paste the yaml within http://editor.swagger.io

## Current Behavior

get errors:
![image](https://user-images.githubusercontent.com/5559355/42729349-11e8839a-87a3-11e8-9111-9c393e4259d1.png)

## Expected Behavior

don't get errors :)

**Comment by virkt25** [comment] 2018-07-16 14:41
Able to reproduce. Looks like we aren't generating `responses` property and a few other issues possibly from JSON to YAML conversion. Great catch!

**Comment by dhmlau** [comment] 2018-08-21 19:58
FYI - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#response-object

**Comment by dhmlau** [comment] 2018-08-21 20:11
There are 2 kinds of errors when opening our generated openapi.json in editor.swagger.io:
1. responses object is empty
   - According to the spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#response-object), at least `description` should exist.
   - A quick change for users (to just get rid of the error) is to modify `responses: {}` to:
   ```
   responses: {
        "200": {
          description: "some description"
        }
      }
   ```

2. If `in` field in the parameter object is `path`, the following needs to exist:

```
required: true
```
   
    i.e. 
   ```
    parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true 
    ```

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameter-object

**Comment by bajtos** [comment] 2018-08-23 13:25
> I am proposing to modify our @param.path.* decorators to always set required: true. See packages/openapi-v3/src/decorators/parameter.decorator.ts.

Never mind :) A different solution has been already landed via https://github.com/strongloop/loopback-next/pull/1633 👍

**Comment by virkt25** [comment] 2018-08-28 17:59
## Acceptance Criteria

- Introduce a default `responses` object on the generated OpenAPI Spec (`responses: {200: {description: ''}}`
- Introduce a `@responses` decorator which takes in an OpenAPI responses object for a given controller method. This will take the exact spec. Should be able to resolve {schema: MODEL} to a model in the spec.
- Update CLI to automatically decorate CRUD APIs with `@responses()` decorator
- Introduce a `@response` decorator (must override base class to allow for multiple to be set on a controller method). This is a sugar method with a simplified UX.

**Comment by bajtos** [comment] 2018-08-30 11:15
I am afraid I disagree with the acceptance criteria outlined in the comment above, please see https://github.com/strongloop/loopback-next/pull/1655#issuecomment-417282985

**Comment by bajtos** [comment] 2018-08-30 11:17
> The following will be moved to a new TASK: Introduce a @response decorator (must override base class to allow for multiple to be set on a controller method). This is a sugar method with a simplified UX.

@virkt25 could you please create that follow-up task and/or post a link the GH issue if it already exists?

**Comment by virkt25** [comment] 2018-09-06 17:06
Follow up issue: https://github.com/strongloop/loopback-next/issues/1672

**Closed** 2018-09-13 19:02 UTC
Labels: LB4 GA, OpenAPI, Slipped, bug, p1
